### ISSUE TITLE
T-Echo backlight feature proposal

### ISSUE THREAD

**Issue by runestone74** [meshtastic/Meshtastic-device#1004]
The Soft-RF firmware have a "double-click" for backlight on/off feature that would be nice to have in the Meshtastic firmware as well.

![t-echo-lilygo-55d9c35296f9781827c0cf781994008a](https://user-images.githubusercontent.com/25870931/146641261-db784f6c-84a2-475f-b8e6-9adab9fba035.jpg)

**Comment by andrekir** [comment]
#1010

you can try an early build here (click on 'built'): https://github.com/meshtastic/Meshtastic-device/actions/runs/1596907387

**Comment by runestone74** [comment]
WOOT! Nice job, my old eyes finally can read the e-ink screen :) Thanks!!!
