### ISSUE TITLE
Ham Mode not working

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#1006]
OE1KBC — Yesterday at 4:33 PM
Hi, 1.2.49 ham-mode still working? ... i can not send text messages between two new TBEAM with 1.2.49 
back to 1.2.47 all ok

**Comment by garthvh** [comment]
I think we also need a way to set short name for ham mode as any node with a license as the node name can't be differentiated from the others on the map.

**Comment by garthvh** [comment]
I have also seen a couple of cases where the channel setting were only updated on devices under the control of the ham, and turning of encryption would require sharing those channel settings with the other users of the mesh.

**Comment by sachaw** [comment]
Needs testing, also explicit instructions of what is required for ham mode to work. (Likely entire docs page)

**Comment by caveman99** [comment]
as far as 1.2 is concerned its EOL. Is this a discussion point for 1.3/2.0?

**Comment by garthvh** [comment]
This is all different now

**Comment by garthvh** [comment]
This remains untested, in 1.3 setting ham mode should set lora.islicensed to true, set encryption to off on all channels and set long name to the ham callsign

**Comment by thebentern** [comment]
Tested and it seems to work on 1.3.

1. Set LongName as call sign (and shortname based on that)
2. Dropped encryption from the primary channel
3. Set lora.isLicensed to true
