### ISSUE TITLE
Add maximum hop configuration option

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/Meshtastic-device#1007]
In the real world sometimes we need to increase the max hop count for some nodes. Please make this option configurable via meshtastic-python. Now it's hardcoded to 3 hops.

**Comment by mc-hamster** [comment]
https://github.com/meshtastic/Meshtastic-protobufs/pull/59

**Comment by mc-hamster** [comment]
Done

**Comment by osmanovv** [comment]
Well done! So we lack support from [Python API](https://github.com/meshtastic/Meshtastic-python) for using this setting?

**Comment by mc-hamster** [comment]
I added it to the protocol, so it'll be inherited by the python. No need for anymore changes.

This will roll out in ~2 weeks.
