### ISSUE TITLE
ARM support 

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/Meshtastic-device#1011]
Please include aarch/arm and arrch64/arm64 binary of meshtasticd in next release.

**Comment by mc-hamster** [comment]
What's the use case for this?

**Comment by D4rk4** [comment]
For working with USB dongle on Raspberry PI or HoneyComb LX2

**Comment by kokroo** [comment]
Can't it be easily compiled for those targets? 

@mc-hamster

**Comment by mc-hamster** [comment]
I have not tried compiling for those targets and don't use linux, so it won't be easy for me. The dev who worked on that has been away.

**Comment by D4rk4** [comment]
Up

**Comment by garthvh** [comment]
@D4rk4 Can you add a pull request with what you want?
