### ISSUE TITLE
Send Low Battery Lora Message for Devices with Simple Chargers

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1019]
Several devices supported by Meshtastic do not have sophisticated charging circuitry and without protected cells could deep discharge batteries.  

- Heltec (ESP32)
- LORA32 (ESP32)
- RAK 5005 and 19003 (nrf52)

Proposal would be to send a message from a device somewhat before the battery reaches a potentially damaging level for these devices.  Time thresholds would probably need to be different based on the chip used as 25% with a nrf52 could last much longer than an ESP32 device.

**Comment by mc-hamster** [comment]
Battery level (battery_level) is already included in the position packet. Can that be used?

**Comment by garthvh** [comment]
> Battery level (battery_level) is already included in the position packet. Can that be used?

Seems like the right value to use, this was described to me as how large agricultural lora networks manage Lipo powered remote nodes.

**Comment by jaykayenn** [comment]
battery_level for TLora seems to be scaled incorrectly. My batteries never reach beyond 60%+, and USB wall power shows as 75%. It does not trigger POWERED mode.

**Comment by mc-hamster** [comment]
Closing this issue. Please re-open if the data is not being sent.
