### ISSUE TITLE
Let clients subscribe to multiple channels at once (and possibly change terminology)

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#104]
per good feedback from @cyclomies:

The simplicity of the app, including the other parts of this project as well, is greate. The ability to communicate with all channel users are nice, and all hikers can start using the app with minimal knowledge of the system.

There could be these logical ways to send text messages between users:

a chat for one to all mesh users (default cryptography)
one to one text messages (whoever on the mesh, default cryptography)
public rooms within the mesh (all users can join and use the room, default cryptography)
private rooms for one to many (selected users, private PSK)
unencrypted room for everyone to send emergency messages (totally unencrypted, whoever on the MHz band can open the plain modulation)
Private rooms could be using a different PSK, but the same mesh network settings.

Rooms can be problematic, as they might increase amount of packets. If there are a lot of users within the rooms, unicast messages might become as dense as broadcast messages on the mesh (as almost all messages has to be sent to several nodes).

What about renaming channel to network settings or similar, to empathize the differences between chat rooms, the physical networking settings, and mesh settings? Settings should still be easily set up (working defaults).

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/option-for-chat-rooms-and-unencrypted-messages/134/4

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/public-emergency-chat-room-not-encrypted/713/12

**Comment by yhaenggi** [comment]
Being in the default channel and a private channel would be a good start already. You could communicate with all meshtastic users and with one (and later on more) private channel.

**Comment by stephen304** [comment]
What if you had the public chat as an unremovable room at the top of the rooms list? Then you can add as many chats as you want underneath that? I don't think many of the details of the rooms need to be exposed to the user, I like how Riot/Element keeps its room / dm list.

**Comment by geeksville** [comment]
The development of the clean on device api and gpio service informed me a bit on this.  Implementation plan:

* Allow devices to be in multiple channels, only one of which is designated as the "primary" channel.  primary channel is used to select radio freq/sf etc...
* When receiving messages try to decode against all current channels
* Store 'channel' (either an index or a hash) in MeshPacket - but never send over the lora link
* Use special channel names for security groups (device settings admin, gpio control etc)
* Make a much shorter channel QR code for minimally secure channels

**Comment by geeksville** [comment]
fixed in 1.2
