### ISSUE TITLE
404 not found not working on web file server

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#1044]
When files are not found, a blank page is returned. A more human readable response would be useful. 

“What you’re looking for isn’t here. This is how to get it.”

This is a regression

**Comment by sachaw** [comment]
When the web UI is installed, it should hijack the 404 and display it's own, whatever changes, shouldn't impact this

**Comment by mc-hamster** [comment]
Fixed with

https://github.com/meshtastic/Meshtastic-device/commit/749d127281f851e357a763f30a7e9c4687634875

Change was only to display text when the file can't be found.
