### ISSUE TITLE
Feature: add disable_tx setting

### ISSUE THREAD

**Issue by ernax78** [meshtastic/Meshtastic-device#1065]
The reasoning to implement this would be to enable hot-swapping antennas without risking the radio. Otherwise the safe change of antenna would require a power down. When powering down / up the radio, following the signal quality of other nodes (improvement of antenna) will be less effective. Also, tinkering with the device in an environment where LoRa signals can disturb other equipment (or rule out disturbing other equipment).

References: RadioLibInterface::send

**Comment by mc-hamster** [comment]
thanks!
