### ISSUE TITLE
Add a page to configure radioconf to ap admin mode

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#1068]
Add a page /admin to perform some common configuration changes.

Include: 

- Wifi Client Credentials & Mode
- ~~Always Powered~~
- Smart Position Update
- what else?

Save with: nodeDB.saveToDisk()

Note: Anyone reading this may propose additional preferences in the comments below.

**Comment by Noki** [comment]
- Region
- Uplink/Donwlink enabled
- Is Router

and maybe the store and forward plugin
