### ISSUE TITLE
PeriodicScheduler should use a heap

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#107]
fixme comment from PerodicTask.h:

class PeriodicScheduler
{
    friend class PeriodicTask;

    /**
     * This really should be some form of heap, and when the period gets changed on a task it should get
     * rescheduled in that heap.  Currently it is just a dumb array and everytime we run loop() we check
     * _every_ tasks.  If it was a heap we'd only have to check the first task.
     */
    std::vector<PeriodicTask *> tasks;
}

**Comment by geeksville** [comment]
possibly an ordered stl::set

**Comment by sachaw** [comment]
@mc-hamster Fairly certain this is no longer applicable right?

**Comment by caveman99** [comment]
PeriodicTask is not in the firmware any more, i think (without looking) this was replaced by OSThreads...
