### ISSUE TITLE
LongFast is a potential troublesome modemsetting 

### ISSUE THREAD

**Issue by costonisp** [meshtastic/Meshtastic-device#1081]
Channel Settings has a choice of 6 modem configurations
The 'LongFast' mode is potentially tricky.
This mode uses a bandwidth of 31.25 kHz, which is usually too small for LoRa transceivers with regular Xtal.
Only transceivers with a TCXO can use this bandwidth on a reliable basis.

Choosing this configuration should probably display a warning that reads: "To reliably operate 31 kHz BW, all radios on your network must be equipped with a TCXO"

I have explained this with relevant SemTech documentation in this post: https://meshtastic.discourse.group/t/long-range-optimisation-mega-thread/4632/19?u=costo

**Comment by mc-hamster** [comment]
Closing issue. This is fixed in 1.3.
