### ISSUE TITLE
Regulatory settings upon installing / starting a new device

### ISSUE THREAD

**Issue by ernax78** [meshtastic/Meshtastic-device#1091]
When you first boot up a device, the default setting is USA, center frequency 903. (region) 

That means the device transmits on the USA frequencies which might place the user in a place of hurt should that band be reserved for something else.

This can also be an issue if a device "activates" in transit from the vendor. (T-echo with built in battery) It will then transmit around 903MHz.

Food for thought would be to have the is_tx_disabled set to true until the radio is properly configured using any of the means bt, web, python. Possibly accepting a "disclaimer" with a pointer to a FAQ about which region belongs to which country so the end user is informed about the consequences of ignoring this. 

A scenario could be if you ship a few devices to an user in Europe, he will turn them on, and the ease of use they will happily pair and work (badly probably because badly tuned antennas, 868 base instead of 900) , albeit on "illegal frequency" which can cause the user to get in trouble with regulators / disrupt other transmissions.

A "quick fix" for this would to implement a nasty power limit on "unset" causing the devices to work, but possibly not disturb anyone else.

**Comment by caveman99** [comment]
this is working in 1.3 firmware, inlcuding a user facing notice to set region.
