### ISSUE TITLE
Change 'mode' in serial plugin to an enum

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#1102]

**Comment by mkinney** [comment]
I see mode used 3 times in the code:

https://github.com/meshtastic/Meshtastic-device/blob/master/src/plugins/esp32/SerialPlugin.cpp#L190

and a few lines down below it.

There are 3 values: 0, 1, and 10.

What are the 3 values used for? If you can answer that, I might be able to make this change as a "newbie".

**Comment by garthvh** [comment]
This is updated in 1.3
