### ISSUE TITLE
fix submodule sdk-nrfxlib

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-device#1115]
**Describe the bug**
A submodule needs to be fixed

**To Reproduce**
1. Run the following command:

```
git submodule update --remote --merge
```
2. See error:

```
$ git submodule update --remote --merge
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'sdk-nrfxlib'
```

**Expected behavior**
Should not error when you update submodules.

**Additional context**
Not sure what version we've pinned to or if we can just update to latest.

**Comment by thebentern** [comment]
This is fixed? Can it be closed now?

**Comment by sachaw** [comment]
sdk-nrfxlib is no longer used.
