### ISSUE TITLE
RAK 5005 Based Firmware not getting a GPS Fix

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1121]
Since the firmware split I am not get a GPS fix from my 5005 based RAK device with the 1910 GPS

**Comment by thebentern** [comment]
There are some macros in gps code, if anybody wants to try doing a custom build and pulling the logs
![image](https://user-images.githubusercontent.com/9000580/150550632-3397eaea-da6c-41b0-90d7-83ee10410d47.png)

**Comment by feh123** [comment]
Same for me on my rak5005s.

**Comment by garthvh** [comment]
Closing as it is a duplicate of https://github.com/meshtastic/Meshtastic-device/issues/998 which has more detail
