### ISSUE TITLE
Feature request: Hardware test mode

### ISSUE THREAD

**Issue by ernax78** [meshtastic/Meshtastic-device#1123]
It would be nice to have a hardware test mode on the device firmware that could be invoked in some easy manner, maybe pressing the main button 5 times if region is "unset" or something similar (for a newly installed device) or set some protobuf.

The test could include:
1) Communication woth LoRa modem - see that it can send / recieve signals from the modem, optionally send / recieve signals from another device in "test mode" if the region is set, prefeably in the most reliable way to make sure it can send / recieve.
2) Communicaton with GPS - see that it can send / recieve data from the GPS module, optionally getting info from gps (fix)
3) Flashing all leds installed to make sure the leds are hooked up
4) Testing environmental sensors (if installed)
5) Listing data from battery management etc
6) Testing all buttons, confrming all buttons have got "button pressed"

Possibly something that could be easily scripted and used in a factory setting after flashing the firmware? And also easy enough to verify a device after taking delivery of a new device. Possibly good enough to show the results to a supplier to "prove" the GPS is not soldered correctly or something.

This will save alot of time and grief trying to get devices to work when the quality control sometimes can be "interesting"

**Comment by garthvh** [comment]
There is considerably more auto detection in 1.3, critical faults and serial log provide all this information now.
