### ISSUE TITLE
RFE: Early console init on RAK (nrf family) devices

### ISSUE THREAD

**Issue by a-f-G-U-C** [meshtastic/Meshtastic-device#1146]
Based on a suggestion by @mc-hamster in issue #998 comments.

It appears that the USB serial console on this platform is initialized fairly late in the boot process (relative to other hardware components), causing some early log messages to be lost, for example the GPS initialization.
It would make sense, if possible, to have the USB initialization earlier in the sequence, considering that some of the most interesting log entries occur precisely in the early stages of boot.

**Comment by mc-hamster** [comment]
Self assigned.

**Comment by mc-hamster** [comment]
Resolved by @caveman99 

https://github.com/meshtastic/Meshtastic-device/pull/1327
