### ISSUE TITLE
rangetest.csv not recording gps data

### ISSUE THREAD

**Issue by cyberlink1** [meshtastic/Meshtastic-device#1184]
meshtastic v1.2.52

Not sure if this is the web interface or the range test plugin itself. 

csv contains all 00000 for the gps data, even when the gps has a lock and is showing my location.

attaching file as example.

[rangetest.csv](https://github.com/meshtastic/meshtastic-web/files/7876054/rangetest.csv)
.

**Comment by garthvh** [comment]
Is this still happening on 1.2.55?

**Comment by charminULTRA** [comment]
This same issue occurred for me using both Heltec v2.1s and a T-Beam, on 1.2.60 firmware.

**Comment by sachaw** [comment]
This should be fixed, can anyone else chime in?
