### ISSUE TITLE
In router mode  incoming messages are not displayed on web messages tab

### ISSUE THREAD

**Issue by ryanjjennings** [meshtastic/Meshtastic-device#1189]
If I put my device in "is router" mode the incoming messages do not display on the messages tab in the browser.  I am able to send messages.  Sent messages show up in the web messages dialog and are transmitted to my other device.  If I reply from the remote device the message is displayed on the router oled, but not in the web dialog.

**Comment by garthvh** [comment]
The router mode is meant to not use bluetooth and wifi and sleep and relay messages, it is not a great fit for a client connected device.

**Comment by RicInNewMexico** [comment]
Just want to add:

If the goal of using "is router" was to prevent device sleep it can also be accomplished by changing the mesh_sds_timeout_secs as noted here: https://meshtastic.org/docs/software/settings/power

That should keep the device awake and able to tx/rx messages via the web interface

**Comment by ryanjjennings** [comment]
Thanks for the quick help! I will look at the other sleep settings to accomplish what I was after.
