### ISSUE TITLE
Add a reboot_after_secs persistent preference

### ISSUE THREAD

**Issue by joshpirihi** [meshtastic/Meshtastic-device#1193]
Add the ability to make the node reboot after a certain period every time.  So you could do a meshtastic --set reboot_after_secs 86400 and it will reboot every 24 hrs.

Probably need to hard code a minimum of 60s or something like that.  accidentally setting it to 1 second would be super annoying and very hard to get out of.

**Comment by joshpirihi** [comment]
On behalf of a user on the forum.  They're having the odd stability issue that a regular reset seems to fix

**Comment by garthvh** [comment]
You can reboot remote nodes from the python APU

https://meshtastic.org/docs/software/python/python-cli#--reboot

**Comment by D4rk4** [comment]
@garthvh it's not solution for autonomous of the grid nodes

**Comment by garthvh** [comment]
> @garthvh it's not solution for autonomous of the grid nodes

Sure it is https://meshtastic.org/docs/software/device/device-remote-admin

**Comment by garthvh** [comment]
Admin message works for this, closing

**Comment by cracky22** [comment]
> Admin message works for this, closing

Hey garth, can you please tell me how I can restart via admin message?
Best Regards and merry Christmas 🎄🎁
