### ISSUE TITLE
Direction arrow seems incorrect

### ISSUE THREAD

**Issue by ricknun** [meshtastic/Meshtastic-device#1194]
The direction arrow on the Meshtastic radio display is in error.
https://meshtastic.discourse.group/t/direction-arrow-seems-incorrect/5027 gives all details.

**Screenshots**
See the forum link for an image.

**Device info:**
See the forum post.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/direction-arrow-seems-incorrect/5027/32

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/direction-arrow-seems-incorrect/5027/34
