### ISSUE TITLE
Feature Request: Some ideas for web panel and endpoints (ota, auth, hidden ssid)

### ISSUE THREAD

**Issue by LolloDev5123** [meshtastic/Meshtastic-device#1195]
Here are some ideas I've had for the meshtastic web panel and endpoints, I'm not that familiar with complex portduino stuff (I've only programmed on an Arduino Mega from the official IDE, even though I regularly use vscode and other languages and I could easily break stuff)  

1. Setting for the device hotspot to be hidden (hidden ssid, stop broadcasting ssid/respond to probe requests), with this the only way to connect to the hotspot is to enter it's name (and password?) manually either by knowing the mac address or by reading the AP name on the screen
2. Hotspot password setting and possibly custom hotspot name or prefix instead of "Meshtastic_", also for bluetooth too?
3. Username & Password for accessing any endpoint (http authentication, with logout?) Example with esp32 http server being used: https://github.com/fhessel/esp32_https_server/blob/master/examples/Authentication/Authentication.ino
4. Related to above, also support Web Authentication js API (https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API) for dedicated platforms?
5. OTA Updates in Webpanel, either update from web/releases or from uploaded bin file (a beautiful example that can be adapted to fit the meshtastic web style: https://github.com/ayushsharma82/AsyncElegantOTA)

**Comment by garthvh** [comment]
Much of this is included in the lashes 1.3.39 build.
