### ISSUE TITLE
Feature Request: incoming packets' RSSI through Python API/CLI

### ISSUE THREAD

**Issue by ub3aiw** [meshtastic/Meshtastic-device#1215]
It would be extremely helpful to have incoming packets' RSSI available through Python API and/or CLI -- for antenna tuning and experimentation. For instance, as per SX1276/77/78/79 datasheet, both SNR and RSSI are required to accurately evaluate a received packet's signal strength (P. 87 [here](https://semtech.my.salesforce.com/sfc/p/E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE?__hstc=212684107.1346a557561f33f4b505dadcadb95b84.1644953215825.1644953215825.1644953215825.1&__hssc=212684107.3.1644953215825&__hsfp=3719723820)). Moreover, I might be mistaken, but I'm not seeing any references to SNR being used alone, uncoupled from RSSI.

**Comment by garthvh** [comment]
Pretty sure this is not available for all supported radios.

**Comment by mc-hamster** [comment]
Closing this issue. Please look at SNR instead of RSSI. They are functionally equivalent except SNR takes into account the noise floor
