### ISSUE TITLE
Feature request:  Every time the node gets a gps position, send it to the phone api clients

### ISSUE THREAD

**Issue by joshpirihi** [meshtastic/Meshtastic-device#1223]
For certain use cases, this would mean the phone could turn it's gps off and hence save a bit of power

**Comment by joshpirihi** [comment]
Happy to do this myself, just added the issue so I don't forget

**Comment by thebentern** [comment]
@joshpirihi has this been implemented yet? For some reason I thought this made it into a release.

**Comment by joshpirihi** [comment]
It made it into 1.2, but not 1.3.  The PR is https://github.com/meshtastic/Meshtastic-device/pull/1242 

I haven't been able to keep up with the rapid pace on 1.3 so have stepped back somewhat

**Comment by thebentern** [comment]
No worries. I'll add integrating the fix into 1.3 on my queue.
