### ISSUE TITLE
[Bug]: T-Echo cannot power on after turn off (sleeping)

### ISSUE THREAD

**Issue by roomme13** [meshtastic/Meshtastic-device#1236]
### Category

BLE

### Hardware

T-Echo

### Firmware Version

1.2.52.b63802c

### Description

Symptoms:
- T-Echo cannot turn on again, after long press button 2 (turn off) on battery or USB
- If on USB, it will boot to programing mode after turn on.
- T-Echo always reset when USB plugged
- Red Led will pulsing fast after turn on

How to reproduce:
- Turn on T-Echo on battery
- Long press button 2 (turn off), release after shut down info appear and wait for blue led turn off
- Normal press button 2 to turn on
- T-Echo will stuck on sleeping, but red led pulsing fast
- Connect to USB, plugin USB will reset T-Echo automatically and t-echo can use normally
- Wait for several minutes
- Long press button 2 (turn off) again, you need to release button after pressing more than 5s, if not it will not turn off 
- Normal press button 2 to turn on
- T-Echo will stuck on sleeping, if USB connected to PC it will mount the programing drive and red led pulsing slow, if not red led will pulsing fast.
- Normal Press button 1 to do reset. and T-Echo back to normal again.

Adding another issue related to charging. When t echo charge using usb, voltage on gps screen shown 4.6v, unlike t beam its only 4.2v at max. 
I don't now its real number or not, but i believe it should not over the max voltage of the battery.

**Comment by garthvh** [comment]
https://github.com/meshtastic/Meshtastic-device/issues/990
