### ISSUE TITLE
5 digit bluetooth passkey through serial debug

### ISSUE THREAD

**Issue by Dafeman** [meshtastic/Meshtastic-device#126]
Using the build "firmware-tbeam-US-0.6.2" with no screen connected, through the serial debug I got "onPassKeyNotify 71714". I'm guessing this should be padded with a 0 to make the minimum 6 digits required?

**Comment by Dafeman** [comment]
Just had a 5 digit passkey again and can confirm that a leading 0 worked.

**Comment by geeksville** [comment]
oops thanks!

**Comment by geeksville** [comment]
I'll fix next week unless someone gets to it first and changes the %d in screen.cpp to %06d. and sends in a PR.

**Comment by geeksville** [comment]
fixed by @dafeman!
