### ISSUE TITLE
Migrate to SparkFun u-blox Arduino GNSS Library

### ISSUE THREAD

**Issue by sachaw** [meshtastic/Meshtastic-device#1287]
Old lib deprecated
https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library

**Comment by mkinney** [comment]
Seeing lots of `processUBX: counter hit MAX_PAYLOAD_SIZE` when the `ublox.enableDebugging(Serial)` is enabled on HEAD of 1.2-legacy

That might be related to our poor GPS lock. Still researching

**Comment by mkinney** [comment]
forked https://github.com/meshtastic/SparkFun_u-blox_GNSS_Arduino_Library

**Comment by mkinney** [comment]
https://github.com/meshtastic/Meshtastic-device/pull/1304

**Comment by thebentern** [comment]
Is this duplicated by #1314?
