### ISSUE TITLE
AP Mode uses SSID/pw that's not the one that's in the config and displayed on the TFT

### ISSUE THREAD

**Issue by raldi** [meshtastic/Meshtastic-device#1289]
I'd like my Meshtastic device to host a test WiFi network with SSID=mt-2 and password=M, so based on the instructions at https://meshtastic.org/docs/settings/wifi I ran `meshtastic --set wifi_ap_mode true --set wifi_ssid mt-2 --set wifi_password M` and it reported success so I rebooted the device. 

The TFT says it's in Soft AP mode with that SSID and password, but it's actually broadcasting a network called ESP_047915 with no password. I even tried pulling the battery out and putting it back in, but the behavior persists.

**Comment by raldi** [comment]
Bugfix PR: https://github.com/meshtastic/Meshtastic-device/pull/1290

**Comment by mc-hamster** [comment]
Closed in favor of: https://github.com/meshtastic/Meshtastic-python/issues/301
