### ISSUE TITLE
Enhancement: HTTP Backend Authorization

### ISSUE THREAD

**Issue by LolloDev5123** [meshtastic/Meshtastic-device#1307]
When accessing an endpoint like the webpanel, authenticate the IP for N hours before asking again,
![immagine](https://user-images.githubusercontent.com/26120324/159124033-d8ee687b-4747-4373-90cd-0ea8fb5fcda7.png)

The webserver that meshtastic uses supports this, here's an example https://github.com/fhessel/esp32_https_server/blob/master/examples/Authentication/Authentication.ino

**Comment by garthvh** [comment]
Appears to use http basic authentication, is this correct?

**Comment by sachaw** [comment]
Not a fan of basic auth, would prefer a session cookie

**Comment by mc-hamster** [comment]
Same. Really would prefer not using this. 

Kevin has proposed handling sessions within protobufs. Let’s explore that.

**Comment by sachaw** [comment]
I like that, some kind of "Auth" module:
Takes a key/password in one message,
returns a session token
Then the client can store it how they like and refresh at x interval

**Comment by sachaw** [comment]
Maybe make it a part of the initial config step, the default is blank so it will work without providing one.
