### ISSUE TITLE
Enhancement: Hidden hotspot

### ISSUE THREAD

**Issue by LolloDev5123** [meshtastic/Meshtastic-device#1308]
A setting/proto for the device hotspot to be hidden (hidden ssid, stop broadcasting ssid/respond to probe requests), with this the only way to connect to the hotspot is to enter it's name (and password?) manually either by knowing the mac address or by reading the AP name on the screen

**Comment by mc-hamster** [comment]
https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/wifi.html

Need to set ssid_hidden in WiFiAPClient.cpp reconnectWiFi()

**Comment by garthvh** [comment]
Implemented
