### ISSUE TITLE
Enhancement: Personalized network branding

### ISSUE THREAD

**Issue by LolloDev5123** [meshtastic/Meshtastic-device#1309]
A setting that over-rides the "Meshtastic_" prefix in bluetooth or wifi hotspots, or even change the whole name?

**Comment by garthvh** [comment]
Duplicate of https://github.com/meshtastic/Meshtastic-device/issues/657

**Comment by LolloDev5123** [comment]
This does not apply only to Bluetooth, includes some other ideas which I was asked to open in a diff issue
