### ISSUE TITLE
Enhancement: OTA/Boot firmware from uSD Card

### ISSUE THREAD

**Issue by LolloDev5123** [meshtastic/Meshtastic-device#1310]
An ESP32's storage/sram can be increased using memory cheaps wired to SPI, an uSD Card uses SPI, why not use an uSD Card for larger firmware capacity? Custom meshtastic PCBs should try to achieve this
https://forum.arduino.cc/t/boot-esp32-from-sd-card/594960
https://arduinojson.org/v6/how-to/use-external-ram-on-esp32/

**Comment by caveman99** [comment]
The ESP32 can **not** boot from SDCard or execute code that's not located in its internal Flash storage. The other link refers to PSRAM which we use alreay if it is available.
