### ISSUE TITLE
[Bug]: ExternalNotificationPlugin doesn't work (T3_V1.6.1)

### ISSUE THREAD

**Issue by amerinoj** [meshtastic/Meshtastic-device#1316]
### Category

Hardware Compatibility

### Hardware

T-Lora v2 1.6

### Firmware Version

1.2.59.d81c1c0

### Description

I tried to config the External Notification Plugin with an LED connected to GPIO 13 but the port always has 3,5v. When a message is arrived el port don't change the state.

I putted the next configuration via meshtastic CLI
config:
ext_notification_plugin_active: True
ext_notification_plugin_alert_message: True
ext_notification_plugin_active: True
ext_notification_plugin_output_ms: 5000
ext_notification_plugin_output: 13

More informatión about hardware and firmware:
Device(T3_V1.6.1)20210104
"firmwareType":Tlora-v2-1-1.6 
"firmwareVersion": "1.2.59.d81c1c0

**Comment by caveman99** [comment]
Although that device does not have a GPS Chip, the code is enabled in the firmware, in case you hook up an external module. The GPS pins are 13 and 15 and that clashes with your LED. You can find the Pin definitions for your device here: https://github.com/meshtastic/Meshtastic-device/blob/master/variants/tlora_v2_1_16/variant.h . Try GPIO23, that should be free to use.
