### ISSUE TITLE
[Bug]: Bootloop when enabling Wifi Client Mode on master

### ISSUE THREAD

**Issue by michaelkleinhenz** [meshtastic/Meshtastic-device#1342]
### Category

BLE

### Hardware

Heltec v2.1

### Firmware Version

1.3.4 master

### Description

I noticed this before but now as I am testing the changes to the REST endpoints, it's more apparent: If I flash current master and enable Wifi client mode, the device boots into a bootloop.

The log when looping is:
```
??:??:?? 5 [PowerFSM] Configuring the Mesh bluetooth service
abort() was called at PC 0x401bdf9a on core 1

ELF file SHA256: 0000000000000000

Backtrace: 0x4008fde7:0x3ffd60c0 0x4009016d:0x3ffd60e0 0x401bdf9a:0x3ffd6100 0x4012cc2b:0x3ffd6120 0x4012cc75:0x3ffd6140 0x4012cea8:0x3ffd6170 0x401bf68c:0x3ffd61a0 0x40102e27:0x3ffd61c0 0x400d5703:0x3ffd6200 0x400d5a72:0x3ffd6240 0x400d4149:0x3ffd6260 0x400f1813:0x3ffd6280 0x400f18a9:0x3ffd62a0 0x400f18da:0x3ffd62c0 0x400dd1ed:0x3ffd62e0 0x400d5156:0x3ffd6300 0x400f5651:0x3ffd6320 0x400dd429:0x3ffd6350 0x40127521:0x3ffd6370

Rebooting...
```

If I add a `return` on line 160 of `esp32/ESP32Bluetooth.cpp` (right after the last log entry is generated), it boots properly (without BT that is).

**Comment by caveman99** [comment]
This is being tracked in #1294. Temporary workaround if you build the firmware yourself is to disable   `-DUSE_NEW_ESP32_BLUETOOTH` in https://github.com/meshtastic/Meshtastic-device/blob/0e3ac246b5304ba6e1ef7a9781f307a6be775555/platformio.ini#L97
