### ISSUE TITLE
[Bug]: CLI commands in documentation do not match output - very difficult to find how to use device

### ISSUE THREAD

**Issue by fangme** [meshtastic/Meshtastic-device#1362]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

1.2.59

### Description

I've been searching for a couple of days trying to find the command to set the "longname" that is output with the --info command.  Found out after posting that it is "set-owner".  I searched high and low trying to find something with "name" in the CLI command - to find out the actual setting has NOTHING to do with the output name.

There should be consistency between documented commands and the output when being viewed via various outputs.  I know it isn't really feasible to change all of those at this point - but possibly just adding "alias" commands would help?  So the old command and the new would do the same thing?

**Comment by garthvh** [comment]
It is in the docs and under —help 

https://meshtastic.org/docs/software/python/python-cli#--set-owner-set_owner

**Comment by fangme** [comment]
I never said it wasn't documented - what I'm saying is that the command does not match the output - so how does one find it?  Even though it is documented - it isn't in a place one would expect it to reside. 

From the docs:
--set-owner
Set device owner name.

And where is the output - either in the Android app - or the CLI meshtastic --info that shows any output regarding "owner"?   It is eitehr "Your Name" or "longname".  The bug/defect here is a complete disconnect between the UI and the documentation.  Which isn't a "bug" per se, but a documentation defect.
