### ISSUE TITLE
add time zone preference?

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-device#1376]
Add timezone preference?

**Comment by sachaw** [comment]
I think the way to handle this is:

Nodes with GPS should set there own TZ property on `NodeInfo`
nodes without GPS should take the TZ from nodes that are considered close.
no need for preference.

**Comment by thebentern** [comment]
Phone could be a tertiary source as well?

**Comment by mkinney** [comment]
Could probably add something to -python to detect and "set" time, if necessary, using the computer time.

**Comment by Commander-Crash** [comment]
I cant set time even with my 2 t-beams. It never pulls GPS. meshtastic --settime is not a valid command.

**Comment by garthvh** [comment]
This seems like a hairball of code and the phones do a lot of this work for us, closing unless someone is super passionate about implementing it. Bridged networks would need to be considered in this functionality as well.
