### ISSUE TITLE
do not set ntp so frequently

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-device#1377]
Looks like if wifi_ssid is set, the ntp is updated every 30 seconds. This seems like too frequent. Perhaps add a preference?

**Comment by sachaw** [comment]
High frequency NTP polling is 64-1024 seconds, non frequent, can be several days.

I'd say there's no need for a preference.

Time should always be synced on AP connect, and periodically, every few hours would be plenty

**Comment by mc-hamster** [comment]
Whatever is decided for the frequency, unless there's an actual use case where configuring it is required -- let's not have a preference.

**Comment by caveman99** [comment]
Preference needed not for the frequency, but the server ip or name ... :-)

**Comment by sachaw** [comment]
This has been resolved in https://github.com/meshtastic/Meshtastic-device/commit/7799e1b7e6a2ad219aa8da6e2ed4ec80e797dbbd
Interval is now `1024` seconds, default server is `0.pool.ntp.org`, and configurable under `deviceConfig`
