### ISSUE TITLE
[enhancment]: add speed data to smart positioning

### ISSUE THREAD

**Issue by djscoutmaster** [meshtastic/Meshtastic-device#1384]
### Category

Hardware Compatibility

### Hardware

Not Applicable

### Firmware Version

1.2

### Description

Once gps speed i formation is added ( #1379) then also add logic to not send any location update messages if speed is below 1mph.

this will aid in reducing congestion in the network when the use case are tracking traveling groups. (Bikes, cars, humans). 

When everyone spreads back out and mphs jump up, it can start reporting again.

Mph ticket
https://github.com/meshtastic/Meshtastic-device/issues/1379

**Comment by mc-hamster** [comment]
How would knowing the speed in a short frequency help? Smart position requires moving a certain amount of distance in a certain amount of time, so it's a large frequency measure.

Removing the bug label. Existing feature works as expected.

**Comment by mc-hamster** [comment]
Closing this. After conversation with @djscoutmaster, he suggested a bug rather than a need for an enhancement.
