### ISSUE TITLE
1.3 Feature Request - Add get firmware version method to admin messages

### ISSUE THREAD

**Issue by rainerfritz** [meshtastic/Meshtastic-device#1390]
Hi!

As we need here to know on which firmware each node is, I want to ask you to add firmware version information into the User section of the nodeinfo message. 

THX a lot
BR
Rainer

**Comment by mc-hamster** [comment]
What's the use case for this?

**Comment by rainerfritz** [comment]
We are running a HAM network with 40 to 60 nodes. You can have a look on it here: https://srv08.oevsv.at/mqtt/
We want to know on which firmware version each node is to react on the mqtt server for discrepances in the messages or if HAM ops update firmware we are able to keep track which node needs to be updated.

**Comment by mc-hamster** [comment]
@rainerfritz Thanks!

Note to who ever implements this: It's ok to broadcast firmware version, but please don't add it to node info. It'll bloat that further which is already big. A separate plugin would be ideal.

**Comment by caveman99** [comment]
The idea was to have it off by default, so the empty field would not take up space in the message.

**Comment by mc-hamster** [comment]
so ... if nodedb is 80 entries and the version is 24 bytes (8bit.8bit.8bit) then that's 2k of ram at minimum.

**Comment by rainerfritz** [comment]
What if we make a plugin which triggers a message to submit firmware data and all of other data needed. So no storing needed. Would cause a lot of airtime in the network, but we don't need that so often.

**Comment by mc-hamster** [comment]
> What if we make a plugin which triggers a message to submit firmware data and all of other data needed. So no storing needed. Would cause a lot of airtime in the network, but we don't need that so often.

great idea ... please have that module be disabled by default

**Comment by caveman99** [comment]
not that much airtime, cause that info is fairly static. A trigger every few hours would be enough. Battery Level is included already, and that's the only thing updating faster :-)

**Comment by garthvh** [comment]
Might be useful to also request the protobuf version that is included in config now as well

**Comment by garthvh** [comment]
Hey @rainerfritz will this work? 

https://github.com/meshtastic/Meshtastic-device/pull/1607

**Comment by rainerfritz** [comment]
Hey Garth!
Yes that sounds great! Thx a lot for implementing it! Much appreciated!

**Comment by thebentern** [comment]
This has been integrated
![image](https://user-images.githubusercontent.com/9000580/183417277-b43ea8d7-4bea-4ff9-b0f0-48a8491ad341.png)
