### ISSUE TITLE
[Feature Request]: Screen rotation option

### ISSUE THREAD

**Issue by cnf** [meshtastic/Meshtastic-device#1406]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

v1.2.59

### Description

Hi,

I am mounting a ttgo Lora in [this case](https://www.printables.com/model/131389-ttgo-lora32-v2116-case-for-meshtastic) with the DIN mount.

Because of the position of the antenna, mounted the screen is upside down for reading.

Would it be possible to add a config option to flip the screen 180 degrees, so it is presented better in those situations?

Relevant [discord talk here](https://discord.com/channels/867578229534359593/920180403799728210/967808852001173555)

Thanks!

**Comment by caveman99** [comment]
This will be considered for 1.3 pending the protobuf config reshuffle.

**Comment by cnf** [comment]
Thanks a lot! All I can ask for 😄

**Comment by sachaw** [comment]
Protobufs implemented

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/1-3-42-how-to-flip-the-screen/6568/4
