### ISSUE TITLE
[Feature Request]: Long Range FHSS supporting

### ISSUE THREAD

**Issue by boby1975** [meshtastic/Meshtastic-device#1416]
### Category

Other

### Hardware

T-Echo

### Firmware Version

1.2.59

### Description

Hi
I did not find **"Long Range FHSS settings"** in **[Protobuf API](https://meshtastic.org/docs/developers/protobufs/api#channelsettings)** documentation. 
Such technology is suppurted in Semtech modules **SX1261/2**. It would be nice to add this if possible. 
Thanks.

**PS.**
Tell me how to set it up if it already exists

**Comment by caveman99** [comment]
We support more radio chips than the SX126x. Plus FHSS is kinda difficult to coordinate in an opportunistinc P2P Mesh Approach.

**Comment by sachaw** [comment]
If we could get a comparison between what modules support LR-FHSS contrasting those that we support as a project, it assist us in evaluating the viability.

**Comment by garthvh** [comment]
Using FHSS would subject us to a 400ms dwell time limit from the FCC, which would be several times less than our packet size often requires.
