### ISSUE TITLE
[Bug]: GPS Longitude has incorrect sign

### ISSUE THREAD

**Issue by logikal** [meshtastic/Meshtastic-device#1423]
### Category

Other

### Hardware

T-Echo

### Firmware Version

1.2.63.9879494

### Description

Longitude has incorrect sign. 

My T-ECHO running 1.2.63.9879494 is displaying and reporting the right numerical digits, but with the wrong sign for the longitude.

Should be *-*122.xx, is 122.xx.

<img width="1033" alt="Screen Shot 2022-04-29 at 14 57 52" src="https://user-images.githubusercontent.com/419745/166074909-47411fb9-b1f6-4d2e-bf47-2c529d60596d.png">
Incorrect sign on the left, correct sign on the right.

**Comment by logikal** [comment]
confirmed that firmware 1.2.62.3ddd74e had the correct longitude sign

**Comment by caveman99** [comment]
can you please try https://github.com/meshtastic/artifacts/blob/device/pr/pr1455-firmware-1.2.64.179a262.zip?raw=true

**Comment by logikal** [comment]
confirmed fixed in 1.2.64. Thank you!
