### ISSUE TITLE
[Board]: Disaster Radio Board ESP32 V3

### ISSUE THREAD

**Issue by code8buster** [meshtastic/Meshtastic-device#1442]
### SOC

ESP32

### Lora IC

Ebyte E22 900M30S + E22 900M22S

### Product Link

https://github.com/sudomesh/disaster-radio/tree/master/hardware/board_esp32_v3

### Description

This is a prototype with 2 LoRa ICs, one of which is already in use on the Hydra 1W board.
It was not intended to be a device with a screen or I/O for GPS. Most of the I/O is taken up by the 4 bit native microSD slot.

It has two pads for battery leads. Anything using the meshtastic cli tools won't work because they don't force the FTDI chip to deassert DTR. I monitor the USB serial with picocom and toggle DTR off manually to get any output. Esptool works fine for flashing, perhaps it does this by default.

**Comment by thebentern** [comment]
Closes with #1443
