### ISSUE TITLE
[Bug]: LILYGO® TTGO Lora v1.0 does not enter low power mode (says USB when unplugged)

### ISSUE THREAD

**Issue by scottsweb** [meshtastic/Meshtastic-device#1460]
### Category

Hardware Compatibility

### Hardware

T-Lora v1

### Firmware Version

1.2.6.4.fc48fcd

### Description

This board is not correctly detecting when it is unplugged from USB. I have a LiPO plugged in and when I remove the USB and stop charging, Meshtastic says `USB` on the screen. The device also never enters its low power state, with the screen staying on indefinately.

**Comment by caveman99** [comment]
have you set is_always_powered?

**Comment by scottsweb** [comment]
It is currently using all default settings. `is_always_powered` is off.

**Comment by scottsweb** [comment]
Just testing `1.2.6.0` and it is behaving the same too.

**Comment by caveman99** [comment]
mh, not sure the TTGO 1.0 has a ADC pin for battery sampling...

**Comment by caveman99** [comment]
https://github.com/meshtastic/Meshtastic-device/blob/master/variants/tlora_v1/variant.h - the 1.0 does nt have a BATTERY_PIN so there's no way of telling if it is powered or not. This was introduced in v1.3 of the board.

**Comment by garthvh** [comment]
Yeah this is a know issue with the hardware

**Comment by scottsweb** [comment]
Ok, that makes sense! thanks for the fast replies. Is there a setting I can set to force it into a low power mode after a short while?

**Comment by caveman99** [comment]
i think in 1.2 is_router will do that.

**Comment by garthvh** [comment]
Low power turns off bluetooth and wifi quickly, so if you are using the device with a client application it is problematic.

**Comment by scottsweb** [comment]
Ahh interesting, I had no idea they were the same setting. `Powered by Low Power (solar)` seems to be turning the screen off, but as @garthvh, this might not be ideal for a client. I will keep tinkering. 

Thanks again for all your replies.

**Comment by garthvh** [comment]
The is always power setting was created because the detection on these boards is bad without a battery pin, they tend to work best powered by USB.

**Comment by garthvh** [comment]
duplicate of #581
