### ISSUE TITLE
Power limits for EU868 too low for certain countries such as UK and CH

### ISSUE THREAD

**Issue by phenosys** [meshtastic/Meshtastic-device#1533]
In the Region info in Radiointerface.cpp (1.3.20), for EU there is:
`
RDEF(EU868, 869.4f, 869.65f, 10, 0, 16, false, false)`

But as far as I understand for Switzerland from the official OFCOM site:
[https://www.ofcomnet.ch/api/rir/1008/09 1](https://www.ofcomnet.ch/api/rir/1008/09)
we are allowed up to 500mW erp with a 10% duty cycle on the 869.400 - 869.650 MHz band.
The same goes for the UK in the UK's Ofcom document IR2030 (page 15-17)
https://www.ofcom.org.uk/__data/assets/pdf_file/0028/84970/ir-2030.pdf

> IR2030/1/19 allows 869.40-869.65 MHz up to 500mW e.r.p up to 10% duty cycle too.

This is also compatible with ETSI:
https://www.etsi.org/deliver/etsi_en/300200_300299/30022001/02.04.01_40/en_30022001v020401o.pdf
on page 29:
> 869,400 MHz to 869,650 MHz Non-specific use 500 mW ≤25 kHz
The whole stated frequency band may be used as wideband channel for high speed data transmission 10 % or LBT + AFA (see note 3)

Would it be possible to add regions CH868 and UK868 with settings that allow to fully use the above limits, based for example on a antenna and cable combined gain of e.g. 3 or 4 dB?

**Comment by caveman99** [comment]
if ETSI allows it, we can just raise the max TX on that band. I remember when this was first discussed there was confusion between the wider 868 allocation (which allows only 1% DC). This may have been overlooked creating the new settings.

N.B. duty cycle needs to be implemented on a 1h sliding window. Right now we only watch channel utilization.
