### ISSUE TITLE
1.3 Feature Request:  BLE Pin / Just Works Configurable Functionality for all devices

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1548]
* [x] Enable Users to configure a device as needing a pin or just works
* [x] Choose a default
* [x] Potentially allow a user to set a specific pin to be used by BLE (requested frequently for sealed devices)

**Comment by tropho23** [comment]
I agree, please add this feature.  Pairing PIN toggle would be useful for all devices, especially those without screens (no PIN) and those remotely deployed (screen or not, PIN would add security).  Thanks!

**Comment by garthvh** [comment]
Screen is detected over i2c, devices with no screen get a default pin of 123456 you can override this default by setting your own fixed pin
