### ISSUE TITLE
[1.3 Feature Request]: Advertise DFU BLE Characteristic for NRF OTA Firmware upgrades

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1566]
### Category

BLE

### Hardware

Rak4631

### Firmware Version

1.3.26

### Description

Add DFU Characteristic to the device firmware and verify that the process works with the NRF Connect android and iOS apps.

**Comment by garthvh** [comment]
It looks like we may be using a legacy dfu characteristic

**Comment by caveman99** [comment]
a good writeup on DFU-OTA is on https://novelbits.io/ota-device-firmware-update-part-1
