### ISSUE TITLE
[Bug]: Unable to set parameters using windows CLI 

### ISSUE THREAD

**Issue by CptScotchTape** [meshtastic/Meshtastic-device#1573]
### Category

Serial

### Hardware

T-Beam

### Firmware Version

1.3.22.c725a6b

### Description

![Bug](https://user-images.githubusercontent.com/83840645/181663729-a960f1ba-6eec-4e3e-8390-958de5110ed8.PNG)

After flashing to any Alpha version of 1.3, no parameters can be set using the windows command line interface.

**Comment by garthvh** [comment]
Only —info —nodes and —noproto are working with 1.3
