### ISSUE TITLE
[Board]: Meshtastic Mesh Device Station Edition G1

### ISSUE THREAD

**Issue by neilhao** [meshtastic/Meshtastic-device#1579]
### SOC

ESP32

### Lora IC

SX1262 

### Product Link

https://uniteng.com/wiki/doku.php?id=meshtastic:station

### Description

The Station Edition series is a compact Lora device with high power PA (Maximum TX Power: 35dBm@915MHz or 868MHz for Station G1 Edition), Rugged SMA Antenna Socket, rich external IO interface, wide input voltage range (8VDC-20VDC).

**Comment by caveman99** [comment]
G1-Station is included in the build portfolio now. Congrats! :-)
