### ISSUE TITLE
Feature Request - Ability to disable Bluetooth radio

### ISSUE THREAD

**Issue by vociferous-viking** [meshtastic/Meshtastic-device#1592]
Referencing [this post](https://meshtastic.discourse.group/t/is-it-problematic-to-remove-bl-antenna/5718/4) (I'm not the OP). Requesting the ability to disable the Bluetooth radio without negatively impacting the rest of the network.

**Comment by garthvh** [comment]
Duplicate of https://github.com/meshtastic/Meshtastic-device/issues/1435
