### ISSUE TITLE
1.3 Add an enabled property to the wifi config.

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1595]
I think there is a case for adding an enabled Boolean property to the wifi config.

_Originally posted by @sachaw in https://github.com/meshtastic/Meshtastic-device/issues/1590#issuecomment-1204808327_

**Comment by garthvh** [comment]
Since there is now field length validation for ssid and psk and the old method of setting them to "" no longer works, we need an enabled boolean so clients can disable wifi without flashing firmware

**Comment by Noki** [comment]
I think it would be a good idea to consolidate this, ap_mode and ap_hidden into a single ENUM:

wifi.mode (`off`,`client`,`ap`,`ap_hidden`)

In my opinion this would be a lot easier to understand for most users.

**Comment by garthvh** [comment]
Complete

**Comment by caveman99** [comment]
this is only the settings for now, please leave ths open until the setting is wired to the firmware :-) I was planning on doing that after the weekend.

**Comment by mc-hamster** [comment]
Updated title to represent the implementation.

**Comment by sachaw** [comment]
As @Noki said, I too believe this is the way forwards https://github.com/meshtastic/Meshtastic-device/issues/1601

**Comment by garthvh** [comment]
Enabled is not part of an enum anywhere else are we going to make this change to all 6 modules with enabled? They does not match our other config at all.  Has anyone mocked up a UI with this structure, seems confusing.

**Comment by sachaw** [comment]
Enum is now implemented, we still require the logic to be implemented to support the disabled property
