### ISSUE TITLE
[Bug]: 1.3 ESP32 NimBLE API hangs

### ISSUE THREAD

**Issue by andrekir** [meshtastic/Meshtastic-device#1598]
### Category

BLE

### Hardware

T-Beam

### Firmware Version

1.3

### Description

ESP32 Bluetooth connection hangs using new NimBLE API. same behavior confirmed on Android and iOS:

- connection is present
- phones stop receiving data after NimBLE hangs (users can send but not receive data)

switching back to the previous Bluetooth stack works (removing `-DUSE_NEW_ESP32_BLUETOOTH` from `platformio.ini`).

**Comment by garthvh** [comment]
The classic bluetooth stack is not a fix for apple os's, SwiftUI does not support classic bluetooth at all and 1.2 devices are crashing on average once every session, so we need to get the new stack working correctly, reverting to our old stack is not a solution for the apple apps.

**Comment by garthvh** [comment]
These are all BLE 4.0 specific errors in my testing, Invalid Handle and The request is not supported are the errors I am getting from tbeams mostly.

**Comment by thebentern** [comment]
I have a PR up for updating our NimBLE lib_dep version. We're quite a bit behind. I have no idea if it'll fix this issue or not, but it's worth a shot.

**Comment by diamondbarcode** [comment]
This happen to TLora too

**Comment by garthvh** [comment]
Log from discord

MESHTASTIC MESH ACTIVITY LOG
✅ BLE Connecting: Meshtastic_e214 - 8/8/22 5:10:34.8420 
✅ BLE Connected: Meshtastic_e214 - 8/8/22 5:10:35.1760 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:10:35.5240 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:10:35.5290 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:10:35.5330 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.5850 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.5970 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.6040 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.6440 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.6490 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.6530 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.7620 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.7690 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:35.7760 
ℹ️ BLE Disconnected: Meshtastic_e214: User Initiated Disconnect - 8/8/22 5:10:53.9410 
✅ BLE Connecting: Meshtastic_e214 - 8/8/22 5:10:55.9940 
✅ BLE Connected: Meshtastic_e214 - 8/8/22 5:10:56.5980 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:10:56.9500 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:10:56.9560 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:10:56.9600 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:10:56.9630 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.0100 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.0140 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.0200 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.0730 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.0790 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.0850 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.1340 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.1430 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.1470 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.2510 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.2570 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:10:57.2610 
💾 Saved a new myInfo for node number: 3304579604 - 8/8/22 5:10:57.4220 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:10:57.6150 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:10:57.8500 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:10:58.1240 
💾 BLE FROMRADIO received and nodeInfo inserted for Meshtastic e214 - 8/8/22 5:10:58.4300 
💾 BLE FROMRADIO received and nodeInfo inserted for Meshtastic f090 - 8/8/22 5:10:58.5190 
💾 Updated Device Config for node number: 3304579604 - 8/8/22 5:10:58.5280 
🗺️ Custom Position config received 3304579604 - 8/8/22 5:10:58.5950 
💾 Updated Position Config for node number: 3304579604 - 8/8/22 5:10:58.5980 
📶 Default WiFi config received 3304579604 - 8/8/22 5:10:58.6880 
💾 Updated WiFi Config for node number: 3304579604 - 8/8/22 5:10:58.6950 
💾 Updated Display Config for node number: 3304579604 - 8/8/22 5:10:58.7500 
📻 Custom LoRa config 3304579604 - 8/8/22 5:10:58.8080 
💾 Updated LoRa Config for node number: 3304579604 - 8/8/22 5:10:58.8140 
🤖 Default Serial Module config 3304579604 - 8/8/22 5:10:58.9280 
💾 Updated Serial Module Config for node number: 3304579604 - 8/8/22 5:10:58.9460 
💾 Updated External Notification Module Config for node number: 3304579604 - 8/8/22 5:10:58.9970 
💾 Updated Range Test Config for node number: 3304579604 - 8/8/22 5:10:59.1230 
💾 Updated Telemetry Module Config for node number: 3304579604 - 8/8/22 5:10:59.1750 
💾 Updated Canned Message Module Config for node number: 3304579604 - 8/8/22 5:10:59.2370 
🤜 BLE Config Complete Packet Id: 8 - 8/8/22 5:10:59.2890 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3304579604 - 8/8/22 5:10:59.4110 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3045257360 - 8/8/22 5:10:59.4150 
🕸️ ROUTING PACKET received for RequestID: 4220625949 Error: This message is not a failure - 8/8/22 5:10:59.4680 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3045257360 - 8/8/22 5:10:59.5320 
💾 Telemetry Saved for Node: 3045257360 - 8/8/22 5:10:59.5950 
💾 Updated NodeInfo SNR 6.0 and Time from Node Info App Packet For: 3045257360 - 8/8/22 5:10:59.6570 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3045257360 - 8/8/22 5:10:59.7240 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3304579604 - 8/8/22 5:10:59.7840 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3045257360 - 8/8/22 5:10:59.8440 
📲 New messageId 2443818163 sent to Meshtastic f090 - 8/8/22 5:11:30.4860 
💾 Saved a new sent message from 3304579604 to 3045257360 - 8/8/22 5:11:30.4980 
🕸️ ROUTING PACKET received for RequestID: 2443818163 Error: This message is not a failure - 8/8/22 5:11:33.3730 
💾 ACK Received and saved for MessageID 2443818163 - 8/8/22 5:11:33.3850 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3045257360 - 8/8/22 5:11:35.0880 
📲 New messageId 2788017956 sent to Meshtastic f090 - 8/8/22 5:12:07.5730 
💾 Saved a new sent message from 3304579604 to 3045257360 - 8/8/22 5:12:07.5850 
🕸️ ROUTING PACKET received for RequestID: 2788017956 Error: This message is not a failure - 8/8/22 5:12:11.4430 
💾 ACK Received and saved for MessageID 2788017956 - 8/8/22 5:12:11.4510 
📲 New messageId 199439702 sent to Meshtastic f090 - 8/8/22 5:15:15.0660 
💾 Saved a new sent message from 3304579604 to 3045257360 - 8/8/22 5:15:15.0860 
🕸️ ROUTING PACKET received for RequestID: 199439702 Error: This message is not a failure - 8/8/22 5:15:19.5900 
💾 ACK Received and saved for MessageID 199439702 - 8/8/22 5:15:19.5950 
💾 Telemetry Saved for Node: 3304579604 - 8/8/22 5:16:40.3590 
📲 New messageId 4186817580 sent to Meshtastic f090 - 8/8/22 5:23:04.8830 
💾 Saved a new sent message from 3304579604 to 3045257360 - 8/8/22 5:23:04.9020 
📲 New messageId 4279979827 sent to Meshtastic f090 - 8/8/22 5:24:17.6430 
💾 Saved a new sent message from 3304579604 to 3045257360 - 8/8/22 5:24:17.6580 
📍 Sent a Position Packet from the Apple device GPS to node: 3304579604 - 8/8/22 5:35:20.7690 
📍 Sent a Position Packet from the Apple device GPS to node: 3304579604 - 8/8/22 5:37:20.6690 
ℹ️ BLE Disconnected: Meshtastic_e214: User Initiated Disconnect - 8/8/22 5:38:05.9050 
✅ BLE Connecting: Meshtastic_e214 - 8/8/22 5:38:10.9550 
✅ BLE Connected: Meshtastic_e214 - 8/8/22 5:38:11.6530 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:12.0090 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:12.0110 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:12.0120 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:12.0140 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:12.0160 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.0710 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.0720 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.0740 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.1620 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.1650 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.1680 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.2210 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.2230 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.2250 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.2820 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.2870 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.2940 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.4020 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.4090 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:12.4150 
ℹ️ BLE Disconnected: Meshtastic_e214: User Initiated Disconnect - 8/8/22 5:38:20.4290 
✅ BLE Connecting: Meshtastic_e214 - 8/8/22 5:38:23.9050 
✅ BLE Connected: Meshtastic_e214 - 8/8/22 5:38:24.5390 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:24.9250 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:24.9260 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:24.9280 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:24.9300 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:24.9320 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:38:24.9340 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:24.9860 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:24.9870 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:24.9890 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.0460 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.0470 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.0490 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.1070 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.1070 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.1090 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.1670 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.1680 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.1690 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.2270 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.2280 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.2290 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.3450 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.3460 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:38:25.3470 
ℹ️ BLE Disconnected: Meshtastic_e214: User Initiated Disconnect - 8/8/22 5:38:37.0010 
✅ BLE Connecting: Meshtastic_e214 - 8/8/22 5:39:03.4920 
✅ BLE Connected: Meshtastic_e214 - 8/8/22 5:39:03.7690 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:04.1590 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:04.1610 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:04.1630 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:04.1640 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:04.1660 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:04.1680 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:04.1700 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.2200 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.2220 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.2250 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.2800 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.2840 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.2880 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.3400 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.3420 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.3450 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.4000 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.4030 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.4050 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.4600 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.4620 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.4640 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.5190 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.5210 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.5240 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.6380 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.6400 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:04.6420 
ℹ️ BLE Disconnected: Meshtastic_e214: User Initiated Disconnect - 8/8/22 5:39:25.1770 
✅ BLE Connecting: Meshtastic_e214 - 8/8/22 5:39:26.8270 
✅ BLE Connected: Meshtastic_e214 - 8/8/22 5:39:27.3310 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:27.7080 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:27.7090 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:27.7120 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:27.7140 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:27.7160 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:27.7170 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:27.7190 
✅ BLE Service for Meshtastic discovered by Meshtastic_e214 - 8/8/22 5:39:27.7210 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.7700 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.7720 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.7740 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.8300 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.8330 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.8360 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.8900 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.8930 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.8950 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.9500 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.9530 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:27.9550 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.0100 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.0130 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.0150 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.0720 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.0780 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.0810 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.1320 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.1360 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.1400 
✅ BLE did discover TORADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.2530 
✅ BLE did discover FROMRADIO characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.2580 
✅ BLE did discover FROMNUM (Notify) characteristic for Meshtastic by Meshtastic_e214 - 8/8/22 5:39:28.2610 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:39:28.3870 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:39:28.6610 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:39:28.8800 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:39:29.1510 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:39:29.4210 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:39:29.6900 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:39:29.9600 
💾 Updated myInfo for node number: 3304579604 - 8/8/22 5:39:30.2310 
🚫 didUpdateNotificationStateFor error: The request is not supported. - 8/8/22 5:39:30.4090 
💾 BLE FROMRADIO received and nodeInfo inserted for Meshtastic e214 - 8/8/22 5:39:30.4770 
💾 BLE FROMRADIO received and nodeInfo inserted for Meshtastic f090 - 8/8/22 5:39:30.6520 
💾 Updated Device Config for node number: 3304579604 - 8/8/22 5:39:30.6680 
🗺️ Custom Position config received 3304579604 - 8/8/22 5:39:30.6700 
💾 Updated Position Config for node number: 3304579604 - 8/8/22 5:39:30.6720 
📶 Default WiFi config received 3304579604 - 8/8/22 5:39:30.8250 
💾 Updated WiFi Config for node number: 3304579604 - 8/8/22 5:39:30.8270 
💾 Updated Display Config for node number: 3304579604 - 8/8/22 5:39:30.8300 
📻 Custom LoRa config 3304579604 - 8/8/22 5:39:30.8900 
💾 Updated LoRa Config for node number: 3304579604 - 8/8/22 5:39:30.8920 
🤖 Default Serial Module config 3304579604 - 8/8/22 5:39:31.0100 
💾 Updated Serial Module Config for node number: 3304579604 - 8/8/22 5:39:31.0180 
💾 Updated External Notification Module Config for node number: 3304579604 - 8/8/22 5:39:31.0790 
💾 Updated Range Test Config for node number: 3304579604 - 8/8/22 5:39:31.1940 
💾 Updated Telemetry Module Config for node number: 3304579604 - 8/8/22 5:39:31.2600 
💾 Updated Canned Message Module Config for node number: 3304579604 - 8/8/22 5:39:31.3200 
🤜 BLE Config Complete Packet Id: 34 - 8/8/22 5:39:31.3750 
💾 Telemetry Saved for Node: 3045257360 - 8/8/22 5:39:31.6060 
💾 Updated NodeInfo SNR 4.75 and Time from Node Info App Packet For: 3045257360 - 8/8/22 5:39:31.6090 
💾 Telemetry Saved for Node: 3304579604 - 8/8/22 5:39:31.6110 
💾 Telemetry Saved for Node: 3045257360 - 8/8/22 5:39:31.6140 
💾 Updated NodeInfo SNR 5.0 and Time from Node Info App Packet For: 3045257360 - 8/8/22 5:39:31.6710 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3304579604 - 8/8/22 5:39:31.7320 
💾 Updated Node Position Coordinates, SNR and Time from Position App Packet For: 3045257360 - 8/8/22 5:39:31.7920 
📲 New messageId 1564935107 sent to Meshtastic f090 - 8/8/22 5:39:40.9950 
💾 Saved a new sent message from 3304579604 to 3045257360 - 8/8/22 5:39:41.0130 
🕸️ ROUTING PACKET received for RequestID: 1564935107 Error: This message is not a failure - 8/8/22 5:39:43.8560 
💾 ACK Received and saved for MessageID 1564935107 - 8/8/22 5:39:43.8680 
📍 Sent a Position Packet from the Apple device GPS to node: 3304579604 - 8/8/22 5:46:40.4550 
💾 Telemetry Saved for Node: 3304579604 - 8/8/22 5:46:40.7960 
📲 New messageId 1645745365 sent to Meshtastic f090 - 8/8/22 5:57:59.9650 
💾 Saved a new sent message from 3304579604 to 3045257360 - 8/8/22 5:57:59.9810 
📲 New messageId 640478451 sent to All - Broadcast - 8/8/22 5:58:19.4040 
💾 Saved a new sent message from 3304579604 to 4294967295 - 8/8/22 5:58:19.4160 
📍 Sent a Position Packet from the Apple device GPS to node: 3304579604 - 8/8/22 5:59:45.5840

**Comment by tropho23** [comment]
I also experienced this bug; it happens for my T-Beam v1.1, Tlora v2.1-1.6 and Heltec v2.1 boards with 1.3.34 alpha firmware.

**Comment by diamondbarcode** [comment]
i test firmware 1.3.31 / android app 1.3.30 .. the 2 Tloralv2.1.1.6 app did not received message at all but can send out however when message send i can see on LCD screen. I reboot phone i got flood with all missing message.

T-Beam problems seem solve - 3h test just reboot 1 time - i observed 2 this and phone see if anything change

**Comment by ndoolin** [comment]
I am also having this issue... messages appear on the device screens but have issues getting to their apps on iOS and Android.
1.3.34 fw on t-beam and tlora v2.1.6 devices running current apps on iOS and Android Devices.  Closing the App completely and reconnecting to the device usually helps get the message to the app.

**Comment by thebentern** [comment]
Latest attempted fixes are being pushed to this PR (see artifacts)
https://github.com/meshtastic/Meshtastic-device/pull/1629

Enhanced logging is enabled on this build, so serial logs when bugs are encountered are very helpful for debugging.

**Comment by andrekir** [comment]
solved.
