### ISSUE TITLE
1.3.34 Wifi wiped out [Bug]: 

### ISSUE THREAD

**Issue by nomore1007** [meshtastic/Meshtastic-device#1612]
### Category

WiFi

### Hardware

T-Beam

### Firmware Version

1.3.34

### Description

New update wiped wifi info out, and will not accept new wifi settings from python.

**Comment by garthvh** [comment]
Settings are indeed wiped out when upgrading from 1.2 to 1.3

The syntax has changed for the new CLI 

meshtastic --set wifi.psk "yourpassword"
meshtastic --set wifi.ssid "ssid"
meshtastic --set wifi.enabled true

**Comment by nomore1007** [comment]
set the ssid and psk via this method, but it is not retaining it. I use --info

**Comment by nomore1007** [comment]
wifi.enabled true is for the softAP, correct?

**Comment by garthvh** [comment]
> I set both. I did not set enabled, that's if you want the softAP? I am connecting it to a wifi network, after I set it, I check with --get, and its still blank.
> 
> Also, I upgraded from 1.3.30 to 1.3.34, that's when it disappeared.

No enabled has been added to wifi in general because the new validation on ssid and psk prevents the old method to disable wifi of setting them to "" the mode is now an enum that defaults to client so you should not need to set it unless you want to turn on the soft ap.

**Comment by nomore1007** [comment]
Ok I did leave it unset. I noticed that it also lost the Name and defaulted back to "Meshtastic ####". I downgraded back to .30 and its working again.

**Comment by nomore1007** [comment]
```
meshtastic --port /dev/ttyACM1 --set wifi.enabled true
Connected to radio
Aborting due to: local variable 'localConfig' referenced before assignment
```

**Comment by garthvh** [comment]
It is updated on the device, looks like the protobufs need to be updated on the python API.  The new settings are in iOS.
