### ISSUE TITLE
[Bug]: Web panel not functional, contains broken link

### ISSUE THREAD

**Issue by scarolan** [meshtastic/Meshtastic-device#1626]
### Category

WiFi

### Hardware

T-Beam

### Firmware Version

1.2.65.0adc5ce

### Description

Steps to reproduce:

1. Enable wifi and connect to SSID (not in AP mode)
2. Open meshtastic.local in a browser window
3. Bypass the security warning page, see this:

Web server is running.

The content you are looking for can't be found. Please see: [FAQ](https://meshtastic.org/docs/getting-started/faq#wifi--web-browser).

[admin](https://192.168.86.47/admin)

The FAQ link leads to a 404 page.  Also there seems to be a problem with the self-signed certificate you generate.  It only has a CN (Common Name) field but no SAN (Subject Alternative Name). This causes problems for Chrome users because it's not considered secure enough to only set the CN.  I have tried importing the cert even as a Trusted Root Authority and the browser still won't give me the green lock.

The admin link on that page leads to some very limited functionality.  Is this the entire webapp or am I missing something?

![image](https://user-images.githubusercontent.com/403332/184448481-41ae88de-bcc1-44a0-a32c-00faf5a75beb.png)

**Comment by scarolan** [comment]
I explored a little further and managed to install the web app using the Manage Web Content link.

But attempts to connect to either Serial or WiFi just get this spinner:

![image](https://user-images.githubusercontent.com/403332/184450626-b7240cce-7184-487d-98d6-dc36416c42af.png)

**Comment by scarolan** [comment]
And I just realized this probably should go to the meshtastic-web repo.  I will re-post over there instead.

**Comment by vkasatschew** [comment]
I think the issue may also be in the format of the certificate generated on the device. Duplicating the CN in the SAN field during generation would make it possible to add the certificate as trusted in the client browser.
