### ISSUE TITLE
Remove the page transition animations

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#1648]
The screen page transition animations are slow, clunky and don't look "elegant".

Let's disable the page transitions and simply do a full swap.

**Comment by thebentern** [comment]
@mc-hamster as a part of this removal, I'm assuming we should also yank the CPU speed bursts to facilitate them?

**Comment by mc-hamster** [comment]
> @mc-hamster as a part of this removal, I'm assuming we should also yank the CPU speed bursts to facilitate them?

Oh yea! 

![image](https://user-images.githubusercontent.com/12804989/186737554-86588cf4-e101-4ff6-a16e-38010860dba8.png)
