### ISSUE TITLE
Feature Request: Imperial units option for device display

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/Meshtastic-device#1665]
Would be nice to have a toggle in the display configuration to change the ESP32 screen display units from metric to imperial.

**Comment by sachaw** [comment]
Protobufs implemented

**Comment by ajmcquilkin** [comment]
@ghostop14 New to this repo but potentially interested in taking this on. Do you have a list of displayed measurements that would need to be converted?

**Comment by ghostop14** [comment]
This may actually be 3 issues.  
1. On the device LCD screen, currently it shows km (that was the one I was originally thinking of, as a device setting)
2. In the iOS app, if you go under nodes, distance is in ft (imperial).  If we had a global imperial/metric, this should probably toggle with that
3. On the android app in the people (node) section, distance is not displayed at all

**Comment by ajmcquilkin** [comment]
Yeah that definitely seems like three issues. I'm happy to take the new `DisplayConfig.DisplayUnits` config field and convert metric units into imperial for display on the screen based on that value, assuming that a user would be able to set that field within the app or the cli

**Comment by mc-hamster** [comment]
right on! freedom units!

**Comment by garthvh** [comment]
iOS is based on your phone settings, not the setting for the device screen.
