### ISSUE TITLE
[Bug]: Screen on Nano G1 flips out on initial boot

### ISSUE THREAD

**Issue by CowboyPilot** [meshtastic/Meshtastic-device#1666]
### Category

Hardware Compatibility

### Hardware

Other

### Firmware Version

1.3.39ddc3727

### Description

After initial boot on Nano G1 the screen is garbled.  Mostly snow except for about 3 horizontal lines.  Changing the region seems to restore the screen functionality but after a subsequent boot the screen comes back as garbled.
![PXL_20220901_132933101](https://user-images.githubusercontent.com/27159995/187930093-3807cadb-8533-4109-aaa3-b53c784e5d27.jpg)

**Comment by garthvh** [comment]
A pull from @neilhao is incoming for this issue

**Comment by neilhao** [comment]
This problem is expected to be fixed with #1670

**Comment by sachaw** [comment]
This is now merged, please reopen if this is now fixed

**Comment by CowboyPilot** [comment]
Just tested it, works great!
