### ISSUE TITLE
[Bug]: Heltec 2.1Firmware 1.3.39 Reboots when message with mismatched PSK received

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/Meshtastic-device#1668]
### Category

Other

### Hardware

Heltec v2.1

### Firmware Version

1.3.39.ddc3727

### Description

I statically set a custom PSK on two Heltec boards both running the same firmware version (1.3.39). On one board, the PSK got reset to a random key.  When sending a message from that board to the second board (now with mismatched keys), the receiving 2nd board rebooted.  It was consistently repeatable.  Resetting the key on the sender so they matched and the receiving board functioned correctly.

**Comment by caveman99** [comment]
i can't reproduce this any more with 1.3.42-pre - is this still happening? if so, can you send a serial log of the crashing node?

**Comment by ghostop14** [comment]
I have 1.3.41 installed on it now.  I'll retest and see if it is still reproducible.

**Comment by ghostop14** [comment]
Seems like 1.3.41 isn't causing the reset now with mismatched keys.  However, the python looks like it's throwing an exception parsing the response.  Would it make sense if you think that's the case to close this one and open one on the python side?

```
meshtastic --sendtext testing
ERROR file:stream_interface.py __reader line:171 Error while handling message from radio 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/meshtastic/stream_interface.py", line 169, in __reader
    self._handleFromRadio(self._rxBuf[HEADER_LEN:])
  File "/usr/local/lib/python3.8/dist-packages/meshtastic/mesh_interface.py", line 537, in _handleFromRadio
    self._handlePacketFromRadio(fromRadio.packet)
  File "/usr/local/lib/python3.8/dist-packages/meshtastic/mesh_interface.py", line 683, in _handlePacketFromRadio
    portnum = decoded["portnum"]
TypeError: 'NoneType' object is not subscriptable
Connected to radio
Sending text message testing to ^all on channelIndex:0

```

**Comment by caveman99** [comment]
is the CLI 1.3.39? if not, upgrade it please, there should be no exception here. But glad the original firmware mismatch is cleared up.

**Comment by ghostop14** [comment]
Running latest CLI 1.3.39 and 1.3.44 firmware on the devices, and retested.  Issue looks closed.  Thanks!
