### ISSUE TITLE
1.3 Position Flags - Position Seq Never sends

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1669]
Position Seq posSeqNos Never sends even if it is enabled, should not be affected by empty data like some of the other flags.

**Comment by garthvh** [comment]
uint32 seq_number = 22 in protobufs I think this is the last field in position flags that is not properly sending.

**Comment by caveman99** [comment]
this might be a victim of our default refactoring - i might habe a typo or the wrong value when i adjusted the device firmware. I remeber that field being different than the others.
