### ISSUE TITLE
Feature request: add ability to clear seen nodes without factory reset

### ISSUE THREAD

**Issue by tropho23** [meshtastic/Meshtastic-device#1722]
Requesting a feature to clear seen nodes, both via CLI and mobile apps.  Not sure if an admin message might be leveraged for this so mobile apps can add a convenient 'clear see nodes in mesh' or similar under the Advanced Settings (for Android app) or other location (for iOS app).  CLI would also be convenient for those who script or flash many devices.

**Comment by garthvh** [comment]
Dup of https://github.com/meshtastic/Meshtastic-device/issues/1299
