### ISSUE TITLE
1.3 Remaining Position Flag Issues

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1740]
SeqNo, Speed and Heading are not working when their flags are enabled.  The latest iOS 16 app release allows for download of all the fields on the position log.  You can set the position flags under settings > position

It might also be good to include satsinview by default as it is so prominent on the device screen.

**Comment by caveman99** [comment]
some of the values were not computed, or passed. can you try https://github.com/meshtastic/Meshtastic-device/actions/runs/3176531657 ?

**Comment by garthvh** [comment]
SeqNo is working perfectly.

Speed has a number now, but my tbeam is not moving and the value has been between 80 and 600 (meters per second?)

Heading keeps coming in as 0, I will test on a drive later.

**Comment by garthvh** [comment]
Heading came in with values

**Comment by caveman99** [comment]
i updated the speed calculation, i copy/pasted wrong stuff. the value from the lib is already in km/h ...

**Comment by caveman99** [comment]
Heading should only update while moving faster than 'by foot' - even the comments in the code say this is for vehicle operation only. I have some compass modules with I2C here i intend to add, not for telemetry but for (optional) heading while stationary...

**Comment by caveman99** [comment]
Please reopen if not satisfied :-)

**Comment by garthvh** [comment]
It all seems to be working, not sure the format for the heading but it periodically gets data, speed and seqno seem good now

**Comment by garthvh** [comment]
Speed and heading seem good, seqNo goes 1-8 and then starts over again

**Comment by garthvh** [comment]
After testing more this seems fine
