### ISSUE TITLE
Need tool to audit stack free space (not urgent)

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#176]
Just to make sure we are not blowing out a stack.

Walk the task table occasionally and call https://www.freertos.org/uxTaskGetStackHighWaterMark.html

**Comment by geeksville** [comment]
vTaskList is undefined - so arduino project needs the update listed here: https://github.com/espressif/arduino-esp32/issues/1089

**Comment by geeksville** [comment]
but looks okay for now:
main thread has about 5KB free, net thread has about 2K free

**Comment by sachaw** [comment]
Partitions reworked.
