### ISSUE TITLE
[Bug]: i2c does not work without gps on rak4631

### ISSUE THREAD

**Issue by lesykm** [meshtastic/Meshtastic-device#1846]
### Category

Hardware Compatibility

### Hardware

Rak4631

### Firmware Version

1.3.48.2c1bbf1a-d

### Description

If GPS is not connected I2C cannot be initialized, PR is coming.

**Comment by feh123** [comment]
I have a 5005/4631 with a 13002 adaptor attached. I wanted to add a bme280 temperature sensor. Using 1.3.46.d4ea956 I tried to set this up. But as soon as I add complete the connection of the bme280 the screen powers off and the unit freezes. Removing say the vcc connection the unit restarts on reset. I thought this bug maybe the problem but I added a gps 1910 to the 5005 and still get the sema problem. I there still an issue with i2c? Thanks. I paste the noproto with the gps in place.
[noproto output with gps in place.txt](https://github.com/meshtastic/Meshtastic-device/files/9845997/noproto.output.with.gps.in.place.txt)
