### ISSUE TITLE
[Bug]: Pressing too fast on the middle button restarts the device

### ISSUE THREAD

**Issue by MihaiRF** [meshtastic/Meshtastic-device#1848]
### Category

Other

### Hardware

T-Beam

### Firmware Version

1.3.46.d4ea956

### Description

Pressing too many times (too fast) on the middle button (for changing between screens) is causing a device reset.

**Comment by thebentern** [comment]
I think I might have observed this behavior in the past. Would you mind getting some serial logs via meshtastic --noproto when this occurs?

**Comment by MihaiRF** [comment]
So,
If I press once:
![image](https://user-images.githubusercontent.com/98894701/197380458-6c113fcc-6007-4167-8f4e-4d8be864dd26.png)

If I press twice (quickly):
![image](https://user-images.githubusercontent.com/98894701/197380518-c1e8a72b-3e1c-4f84-8203-4d121df1e3a9.png)

If I press three times (quickly):
![image](https://user-images.githubusercontent.com/98894701/197380548-fca382b5-aa45-483f-8580-ac509bd36649.png)
and it reboots...

**Comment by thebentern** [comment]
This is actually a _feature_ that I had forgotten about. Unfortunately I can't find any documentation about it other than a thread on the discourse group when it was implemented originally. A fast triple click is set up to clear the device bluetooth bonds and restart the device. This was likely more useful when our bluetooth stack was a bit less stable in previous versions.
@garthvh where should we put this in the docs? Or I'm also totally open to revisting this functionality as well... I'm not particularly fond of our current user button scheme. I'm not convinced anyone actually uses the long-press oled brightness toggle for instance.

**Comment by garthvh** [comment]
There is a YouTube video

**Comment by MihaiRF** [comment]
I didn't know about the Oled brightness functionality, cool thing :)
As for the triple click feature, is not really a problem once you know about it. I would leave it as it is, at least for the time being. 
Thanks.

**Comment by thebentern** [comment]
If you're in the Discord group, we're actually talking about re-evaluating some of these user-button functions and switching them to more useful options in light of the evolution of the firmware / apps that's occurred since they were originally added.
https://discord.com/invite/UQJ5QuM7vq

**Comment by MihaiRF** [comment]
> If you're in the Discord group in the #meshtastic-1_3 room, we're actually talking about re-evaluating some of these user-button functions and switching them to more useful options in light of the evolution of the firmware / apps that's occurred since they were originally added. https://discord.com/invite/UQJ5QuM7vq

Thanks for the invitation. I'll try to follow as my time allows.
