### ISSUE TITLE
Improvement of nested Protobuf structures to eliminate ambiguity in one-stage off-device decoding.

### ISSUE THREAD

**Issue by arduionoGP** [meshtastic/Meshtastic-device#1854]
I've noticed some perhaps unneeded device-code complexity and decoding quirks when attempting to decode proto messages that come through the mqtt.proto message "Service Envelope". A one-step decoder, when given the mqtt.proto (which has include mesh.proto which has includes for channel,config, module_config, protnums, and telemetry protos.) chokes on the nested payload because of ambiguity. It produces a partially decoded outpu twhen decoded by a standard one stage decoder and produces something like this:

{"packet":{"from":2130621128,"to":4294967295,"decoded":{"portnum":"TELEMETRY_APP","payload":"**DX2QVWMSAA==**"},"id":1576523471,"hopLimit":3,"priority":"MIN"},"channelId":"LongFast","gatewayId":"!7efeb2c8"}.
The payload **DX2QVWMSAA==** does not get decoded into: {"air_util_tx": 0, "battery_level": 0, "channel_utilization": 0, "voltage": 0}, because of ambiguity.

Likewise, 
{"packet":{"from":2130621128,"to":4294967295,"decoded":{"portnum":"NODEINFO_APP","payload":"**CgkhN2VmZWIyYzgSD01lc2h0YXN0aWMgYjJjOBoEYjJjOCIGlLl+/rLIKAo=**","wantResponse":true},"id":845534553,"hopLimit":3,"priority":"BACKGROUND"},"channelId":"LongFast","gatewayId":"!7efeb2c8"}

**CgkhN2VmZWIyYzgSD01lc2h0YXN0aWMgYjJjOBoEYjJjOCIGlLl+/rLIKAo=**   should have been decoded into {"hardware": 10, "id": "!7efeb2c8", "longname": "Meshtastic b2c8", "shortname": "b2c8"},

Solution would be a slight modification to the protobufs to allow for unambiguous identification of different payloads and their compositions.

**Comment by caveman99** [comment]
That's a massive change very late in the 2.0 release cycle. Right now you look at the portnum and act/decode accordingly. The content of the payload does not have to be another protobuf, it could be json, plaintext or something entirely different like on the ATAK Port. Really the module being resposible for that port knows what is inside the payload and handle it accordingly.
