### ISSUE TITLE
GPS is bad message on OLED 

### ISSUE THREAD

**Issue by feh123** [meshtastic/Meshtastic-device#187]
Hi

I have a tbeam running 0.7.6 beta. I have tried updating today but continue to get gps is bad message and no position icon on mapbox. I am running the app with 0.7.76.

Is it possible to update to a device version with the latest commits? Thanks.

**Comment by geeksville** [comment]
Two things to check:

* Confirm that you have the TBEAM ROM installed (not TTGO-LORA32 - that is a different board)
* Take the unit outside and set it on the ground, it can need quite some minutes for the GPS to get is initial lock and GPS almanac download.  Thereafter the GPS keeps that data in a battery backed up RAM so it should acquire a lock more quickly.  You'll know it has a lock when the red led by the GPS starts blinking.

**Comment by geeksville** [comment]
If that doesn't work, please connect to the board with a serial terminal at 921600 and post the messages the board prints out into this bug and I can probably advise.

**Comment by feh123** [comment]
Hi 
I can for sure make errors but the Lilygo order was a T-beam and I have successfully updated from 0.6.2 or so. I have tried it outside and that did not fix it. I attach the putty log file. 
I should say that the red light is flashing next to the gps. Any advice very much appreciated.
[putty.log](https://github.com/meshtastic/Meshtastic-device/files/4788261/putty.log)

**Comment by feh123** [comment]
Hi tried going through the back versions - 0.7.5 also gave "gps bad" but 0.6.8 has worked and my app (0.7.78) is displaying the correct location for my device. I attach the putty log file for 0.6.8.
I will try a few more versions.
[putty 17-Jun-v0.6.8.log](https://github.com/meshtastic/Meshtastic-device/files/4791165/putty.17-Jun-v0.6.8.log)

**Comment by feh123** [comment]
Hi I have checked the versions and 0.7.4 is working fine, 0.7.5 gives gps bad.

Much relief - I was beginning to think I had faulty devices!

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/alpha-tester-thread-no-new-tests-needed-please-upgrade-to-release-version/298/70

**Comment by cedarknoll** [comment]
I too am having this bug. (I assume it is the same bug anyway) It started with 0.7.5, I have three tbeams they are all currently on 0.7.6. I have had all three of them running outside all morning (several hours). They do have a blinking red light, but they all say "GPS bad" on display. I will attach a log from one of them.
[gps_bug.txt](https://github.com/meshtastic/Meshtastic-device/files/4794799/gps_bug.txt)

anyway hope that is helpful.

**Comment by geeksville** [comment]
@cedarknoll super useful thanks - I'll fix this later today.

**Comment by geeksville** [comment]
Ok - I found the problem, it seems to be a race condition in the Sparkfun_ublox library and apparently now that we are more multithreaded it shows up.  Alas, I won't be fixing this tonight but it is now my #1 bug :-) and I'll fix it tomorrow (probably).

**Comment by geeksville** [comment]
oops - as it turns out I was using their API in a dumb way.  fxing today.
