### ISSUE TITLE
[Board]: External GPS module 

### ISSUE THREAD

**Issue by edegraaff** [meshtastic/Meshtastic-device#1872]
### SOC

ESP32

### Lora IC

LilyGO TTGO LoRa32 868MHz ESP32

### Product Link

https://nl.aliexpress.com/item/1005001512375345.html?spm=a2g0o.order_list.0.0.21ef79d2WU9gis&gatewayAdapt=glo2nld

### Description

I would like to connect this gps to the lora board so i get at on the meshtastic client gps coordinates in real time, i now use static ones.  On the TTGO board there is a tx and rx connection availible  as far as i have seen or should i use the pins as mentionsed in the code pen 15 and 13?  
#undef GPS_RX_PIN
 	#undef GPS_TX_PIN
 	#define GPS_RX_PIN 15 // per @der_bear on the forum, 36 is incorrect for this board type and 15 is a better pick
 	#define GPS_TX_PIN 13

**Comment by garthvh** [comment]
https://meshtastic.org/docs/hardware/gps-modules
