### ISSUE TITLE
Elaborate on NEO-M8N recommendation

### ISSUE THREAD

**Issue by rorosaurus** [meshtastic/Meshtastic-device#189]
Why is the NEO-M8N recommended over the NEO-6M (in the README)?  
  
I have a preference for the model that comes with the built-in OLED (NEO-6M), but I'm not clear on what trade off I'd be accepting - worse battery life / GPS lockon speed?  
  
It might be useful to elaborate on this lightly in the README for people trying to decide what to buy!

**Comment by geeksville** [comment]
The GPS in the 8M is a little better, but they are both pretty close.  I mostly have TBEAMs with the 6m and they are quite fine.

**Comment by geeksville** [comment]
fixed by @rorosaurus!
