### ISSUE TITLE
When we send position updates to other nodes, we should also send it to the phone

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#198]
So that if the phone is connected for a long time, it has a chance for its nodeinfos to get updated.  Currently it doesn't look like those messages are being put into the ToPhone queue.

**Comment by aHVzY2g** [comment]
Could you elaborate on this issue a bit more? If I understand it right it is related to [MeshService::sendOurPosition](https://github.com/meshtastic/Meshtastic-device/blob/9061b3d8c3e23812d8c8d8467bc11e7f524c0714/src/mesh/MeshService.cpp#L269) ?

**Comment by geeksville** [comment]
oh yes. whenever the node either broadcasts its position (very occasionally - once every 15 min) or some other node asks this node to send its position (we will unicast a reply in this case).  This is great, but our rule for "what things should go in the 'forward to phone queue'" is currently only 'stuff that was sent TO this node'.  That's not really ideal, because whenever we send out a position update others we should also have that same message provided to the local phone so it will have current map position for the local user.

I can elaborate more later.

**Comment by aHVzY2g** [comment]
Ah, got it. I will dig in tomorrow, doesn't sound too hard to fix

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/live-map-view-location-warning-and-timestamp-problems/537/7

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/andriod-map-refresh/643/1

**Comment by geeksville** [comment]
fixed long ago
