### ISSUE TITLE
Latest 0.7.7 beta release has no compiled firmware associated

### ISSUE THREAD

**Issue by kalon33** [meshtastic/Meshtastic-device#200]
Latest release doesn't have compiled firmware associated, and seems to be the only one in this situation. Is that on purpose?

**Comment by geeksville** [comment]
Yes.  0.7.7 had "problems" (see alpha tester thread in forum) so for for
the time being I quickly recalled it. 😆.  I'll test more thoughly and put
something out in a couple of days.

(Sent from a phone - please ignore typos)
