### ISSUE TITLE
Singletons for tracking gps and node status

### ISSUE THREAD

**Issue by Professr** [meshtastic/Meshtastic-device#203]
PowerStatus is maintained throughout the app as a singleton for display purposes, and it seems logical to do the same for GPS and NodeDB for consistency's sake.  I have it working, though it needs a little clean-up.  Thoughts?

**Comment by geeksville** [comment]
I see where you are coming from and I think that's a great for GPS (But I though there was a gps singleton pointer already?).  But eventually I'd like to be able to run multiple nodes in one process (for simulation mesh purposes), so I'm in favor of keeping nodedb not a singleton (because each 'node' needs its own copy of the DB)

**Comment by Professr** [comment]
I was thinking more of a status struct that wouldn't change the way the node db object worked.  For example, in my test code the only change is adding 
`    nodesStatus.nodesOnline = getNumOnlineNodes();
    nodesStatus.nodesTotal = getNumNodes();`
to the part where a node gets added / times out.  That way, the screen code doesn't have to call the more expensive methods to show user stats, it just has to pull from the nodesStatus singleton.

The GPS class definitely functions that way, but I wasn't certain whether the way it's instantiated made it as available as PowerStatus.  Maybe I'm missing the picture, I just thought it looked right to have 
`// Global power status singleton
meshtastic::PowerStatus powerStatus;

// Global GPS status singleton
meshtastic::GPSStatus gpsStatus;

// Global nodes status singleton
meshtastic::NodesStatus nodesStatus;
`
right at the top of main.cpp

**Comment by geeksville** [comment]
ooh I see.  Yes that sounds great!

**Comment by Professr** [comment]
Okay, I'll see if I can do that without changing much.  If it doesn't end up being worth it, no biggie :)
