### ISSUE TITLE
Make oled brightness adjustable

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#207]
via a new field in the UserPreferences protobuf and fixing the OLED library to give us a brightness API.  See the SSD1306 datasheet for instructions.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/dim-screen-tbeam/488/2

**Comment by Professr** [comment]
Can confirm that the library's setBrightness method works on T-Beam T22_V1.1

**Comment by geeksville** [comment]
ooh!  I didn't even notice it had one! ok - that makes this bug much easier ;-)
