### ISSUE TITLE
Awesome project but no 915mhz version?

### ISSUE THREAD

**Issue by ZebNZ** [meshtastic/Meshtastic-device#225]
Hi all,

I just went to try out this awesome looking project with a LoRa32 but there appears to be no 915mhz version.

Is that correct?

Thanks,

Zeb

**Comment by geeksville** [comment]
Thanks for the interest.  No, see the README here, all of the recommended boards (a few different models by a couple of vendors) sell three frequency bands, one is 915: https://www.meshtastic.org/

**Comment by geeksville** [comment]
or here: https://github.com/meshtastic/Meshtastic-device/blob/master/README.md
