### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by ZebNZ** [meshtastic/Meshtastic-device#226]
Hi all,

I have got this cool project up and running but I want to modify somethings.

Is there a .ino or .sln file or something like that?

Thanks,

Zeb

**Comment by Professr** [comment]
This project is set up to work with the PlatformIO extension in the VSCode IDE, and it was surprisingly easy for me to get it set up and working initially.  Just follow the [Build Instructions](https://github.com/meshtastic/Meshtastic-device/blob/master/docs/software/build-instructions.md) :)
