### ISSUE TITLE
[Bug]: Text Format Issue on Screen for GPS Disabled by Button

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-device#2260]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.0.18

### Description

Not sure if this is by design or not but it when GPS is disabled on the T-Beam via user button triple ( #2173 ), it's printing the "GPS Disabled by Button" on both "pages" of the screen. On the first "page" it clashes with other text being printed on the screen. I would assume the expected location for this message to be printed would only be the second "page" on the screen, as shown in the image below and similar to how "No GPS Lock" and "No GPS Module" are only printed on that second screen. 

<img src="https://user-images.githubusercontent.com/6912600/217304929-5a51f5a3-4445-47ab-95ec-2e907a6fc2ef.jpg" width=40% height=40%><img src="https://user-images.githubusercontent.com/6912600/217305842-e078957b-1462-4aff-b89c-545d4d536b4a.jpg" width=40% height=40%>

**Comment by code8buster** [comment]
We believed it important to make sure people knew on either screen that the GPS could be re-enabled.
I could change it back such that only the second screen will print the second line, and "GPS Disabled" only appears in the upper right on P1
