### ISSUE TITLE
Need WiFi to add people to group?

### ISSUE THREAD

**Issue by ZebNZ** [meshtastic/Meshtastic-device#227]
Hi all,

It seems that you can create a group and other people can enter the group name but you need WiFi to intialize the group so it will work.

Is that correct?

Zeb

**Comment by ZebNZ** [comment]
So basically you need WiFi to create and add members to a group?

**Comment by ZebNZ** [comment]
Sorry I have confirmed that you do not need WiFi!

**Comment by geeksville** [comment]
btw Zeb, if you want another resource besides github, our discussion forum is pretty active for these sorts of questions: [meshtastic.discourse.group](https://meshtastic.discourse.group)
