### ISSUE TITLE
Heltec V3 and WSLv3 Update Wipes 2.0.23+ and Settings not Saving.

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-device#2325]
### Category

Other

### Hardware

Other

### Firmware Version

2.0.23

### Description

Updated both the Heltec V3 and WSLv3 via the web browser and device-update scripts. Although for each device and method update only was selected, all devices were wiped during the process so that no configured settings remained.

**Comment by thebentern** [comment]
#2340 fixes the device install script installing the wong ota partition bin.
