### ISSUE TITLE
nodes not properly reporting battery level until we have GPS lock

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#249]
Battery level icon is there for all nodes (awesome) but it wasn’t showing the percentage of my battery powered TBeam node until I chucked it outside and it got GPS. I’m assuming this is a device side bug though.

per @dafeman

**Comment by yhaenggi** [comment]
I have the same experience on my two TBeams.

**Comment by DDVanMS2018** [comment]
Same issue here.  
T-Beam V1.1 w/ NEO-6M
Label on the board: T22_V1.1 20191212 915Mhz
android app: 0.9.01
f/w: 0.9.1

**Comment by geeksville** [comment]
Thanks sorry - I took two weeks off - will be fixed soonish now that I'm back.
