### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Harsh-28** [meshtastic/Meshtastic-device#253]
Please - if you just have a question (i.e. not a bug report or a feature proposal), post in our [forum](https://meshtastic.discourse.group/) instead.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device info:**
 - Device model: [e.g. TBEAM]
 - Software Version [e.g. 0.7.8]

**Smartphone information (if relevant):**
 - App Version [e.g. 0.7.2]

**Additional context**

**Comment by geeksville** [comment]
oops - sorry about bugs.  Do you mean to describe one in particular? ;-)
