### ISSUE TITLE
stop building region specific ROMs

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#260]
(forked this from a comment in #243) Someday I'd like to switch to a model where we just have one build per board type (not the IMO outlived its usefulness) prebuild roms for each frequency range.  Once @Professr's menu layer is available we could have a check at startup:

* Is the region set for this board?  If not, wait until user sets it.
* User could then set region either from the screen or from the app (just by changing RadioConfig)
* We store that info in the persistent flash 

I've encouraged hardware vendors to start putting in stuffing resistors so we could detect at runtime which frequency range the board was made for.

**Comment by sachaw** [comment]
Duplicate #416
