### ISSUE TITLE
Is this comment still valid? My device works EU433 (T3_V1.6 20180606)

### ISSUE THREAD

**Issue by slavino** [meshtastic/Meshtastic-device#261]
https://github.com/meshtastic/Meshtastic-device/blob/4388e72decbbccf32ab812f19c34cc61b0332092/platformio.ini#L124

PIN layout:
https://github.com/LilyGO/TTGO-LoRa32-V2.1

**Comment by geeksville** [comment]
oh no- not valid any more, please delete ;-)
