### ISSUE TITLE
long messages need to wrap on the OLED

### ISSUE THREAD

**Issue by paulcart1** [meshtastic/Meshtastic-device#263]
**Describe the bug**
If the message length is longer than the OLED display there is no indication it has been truncated and no was to see the remaining text. The message is displayed correctly in the app.

**To Reproduce**
Send a long message from the app

**Expected behavior**
Option 1:  Character limit option in the app
Option 2:  Ability to use middle button to se the next part of the message.

**Device info:**
 - Device model: TBEAM
 - Software Version 0.7.10

**Smartphone information (if relevant):**
 - Device: Samsung S8
 - OS: Android v9
 - App Version 7.88

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/long-message-issue-on-oled/633/3

**Comment by geeksville** [comment]
btw thanks @Professr thanks for being so proactive during my hiatus!
