### ISSUE TITLE
Show hash suffix & speed code at end of channel name

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#269]
to prevent user channel confusion.  per forum post.

**Comment by geeksville** [comment]
The rule for suffix will be:

channelname-XY

Where X is a letter from A-Z (base 26) representing a hash of the PSK for this channel - so that if the user changes anything about the channel (which does force a new PSK) this letter will also change.  Thus preventing user confusion if two friends try to type in a channel name of "BobsChan" and then can't talk because their PSKs will be different.

This also allows the option of someday if people have the PSK off (zero), the users COULD type in a channel name and be able to talk.

Y is a lower case letter from a-z that represents the channel 'speed' settings (for some future definition of speed)

**Comment by cyclomies** [comment]
Related to the PSK: users could be allowed, to enter their own PSK at will (instead of a automatically generated PSK)?
