### ISSUE TITLE
[Feature Request]: Disable Range test messages except on the Receiver node.

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-device#2708]
### Platform

NRF52, ESP32

### Description

Public MQTT and Range Test module isn't a good idea. Someone's up to over 13k sequences. 

Possible solutions:

1. Implement a timeout for the range test sending via MQTT via a limit on the number of sequences.
2. Disable Range Test for MQTT, at least if using the public MQTT server. 
3. Do not allow range test on primary channel with default encryption
4. Anything else that might be viable.

**Comment by garthvh** [comment]
The time may have passed for the text message sending part of the range test.

**Comment by caveman99** [comment]
Please don't make it dependant on a seemingly unrelated feature (MQTT) - this will be support hell.

**Comment by garthvh** [comment]
I think this is the best solution https://github.com/meshtastic/firmware/commit/c578400af47d03caca50b057a8bf0a27c95ebf8c

**Comment by garthvh** [comment]
I vote we connect this issue to the pull from @caveman99 and then see if we need a mitigation of some kind in MQTT.

**Comment by thebentern** [comment]
This has been effectively solved going forward with firmware version 2.2.2. RangeTest sends the same old text payloads but over the RangeTest_App portnum and we only _want_ those packets if the RangeTest module is enabled on our device.
