### ISSUE TITLE
The buzzer on incoming messages is very necessary.

### ISSUE THREAD

**Issue by luxonn** [meshtastic/Meshtastic-device#271]

**Comment by geeksville** [comment]
alas - we don't have any hardware control on the current devices.  So for now closing as kinda related to https://github.com/meshtastic/Meshtastic-Android/issues/96

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/notification-and-beacon-mode/768/2
