### ISSUE TITLE
Brightness slider activates on TTGO-LoRa32-V2.1 with serial Puttty connection.

### ISSUE THREAD

**Issue by thomslik** [meshtastic/Meshtastic-device#272]
Anytime TTGO-LoRa32-V2.1 is connected with a serial connection with Putty or the Python API, the brightness slider activates and repeatedly  cycles from low to high. Attempting to edit the screen by pulling the GPIO0 low to ground does nothing. Ending the Putty or Python session returns the unit to normal operation.

This may not be an appropriate issue, as TTGO-LoRa32-V2 is listed as supported, but no mention of V2.1. If so, sorry , Please ignore and close.

**Comment by aHVzY2g** [comment]
I guess the issue can be closed https://meshtastic.discourse.group/t/alpha-tester-thread-please-try-device-code-0-7-11/298/179?u=ahvzy2g ?

**Comment by thomslik** [comment]
> I guess the issue can be closed https://meshtastic.discourse.group/t/alpha-tester-thread-please-try-device-code-0-7-11/298/179?u=ahvzy2g ?

This is a totally unrelated issue. It has nothing to do with the T-Beams. It seems to be caused by different pin outs between the TTGO-LoRa32-V2.1 and V2.0.

**Comment by aHVzY2g** [comment]
could you verify that this is the version you have https://github.com/LilyGO/TTGO-LoRa32-V2.1 , I will try to add support for it.

**Comment by geeksville** [comment]
oh yes good point.  slider going up endlessly means the GPIO assignment for the button on the lora32-v2.1 is wrong.

**Comment by aHVzY2g** [comment]
@thomslik please test #274 and let me know if it works

**Comment by thomslik** [comment]
> could you verify that this is the version you have https://github.com/LilyGO/TTGO-LoRa32-V2.1 , I will try to add support for it.

Yes. That is the version I have.

**Comment by thomslik** [comment]
> @thomslik please test #274 and let me know if it works

Sorry for my ignorance, but where do I find the bin to try?

**Comment by thomslik** [comment]
Updated earlier reply, to include tried to build.

**Comment by aHVzY2g** [comment]
@thomslik I will send you a bin asap

**Comment by aHVzY2g** [comment]
Here you go I have two separate bin files. Please test both an tell me if they work. Before each flash use the [esp download tool](https://www.espressif.com/sites/default/files/tools/ESP32%26ESP8266_RF_Performance_Test_EN.zip) to erase the flash of your board.

[build.zip](https://github.com/meshtastic/Meshtastic-device/files/4918400/build.zip)

**Comment by thomslik** [comment]
Thanks. Both versions still do the same. The unit appears to be working fine until the serial connection. Then the same problem with the brightness slider.

**Comment by aHVzY2g** [comment]
[build.zip](https://github.com/meshtastic/Meshtastic-device/files/4918553/build.zip)
sry my mistake, did a copy-paste error

**Comment by geeksville** [comment]
Thanks y'all!

(Sent from a phone - please ignore typos)
