### ISSUE TITLE
loss of GPS lock not updated in the GUI

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#284]
but the problem isn't the GUI.  It is that we only publish GPS updates when we have lock.  Once we lose lock we stop publishing.  Really - we should do one last publish when the state changes from locked to not locked (so the rest of the app establishes the new proper !locked state).

This fix should go into 1.0 (master).

From this forum report:

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/bug-tbeam-never-returns-to-no-sats-state/741/2

**Comment by Professr** [comment]
Mind if I fix this one?

**Comment by geeksville** [comment]
Feel free to fix any one you want! ;-)

**Comment by Professr** [comment]
Hmm.  NEMA already looks ok, but UBlox always reports its last known fix.  Fortunately it seems to update the number of satellite locks it has, so I integrated that into the logic that determines whether the module has a lock or not.  It takes 5-10 minutes to really pick up on the loss of lock, but it does go back to "No sats" at that point.
