### ISSUE TITLE
Interest to support WS2812b neopixel

### ISSUE THREAD

**Issue by aHVzY2g** [meshtastic/Meshtastic-device#292]
Hey, Guys for a custom project I will add support for ws2812b aka. neopixel. Is there interest to include this feature in meshtastic? 

FYI standby consumption per pixel is 1ma, I know that this is too high for meshtastic, but for my purpose it is fine.

**Comment by geeksville** [comment]
Sure - you it might be useful for misc status.  Initially guarded by something like #ifdef NEOPIXEL_CS (for chip select)
