### ISSUE TITLE
Missing battery info with position

### ISSUE THREAD

**Issue by lgoix** [meshtastic/Meshtastic-device#295]
**Describe the bug**
Having a T-Beam v1.0 firmware_version: "0.8.2" , battery level showed 4%. 

Later, the phone is still paired with the device and in Android, the battery level is showing as plugged
![image](https://user-images.githubusercontent.com/16083263/88358286-5837b880-cd3c-11ea-8bf5-a910254f7ed0.png)

but the device is not plugged
![image](https://user-images.githubusercontent.com/16083263/88358422-e3b14980-cd3c-11ea-8855-24c9092a7715.png)

Device does not transmit its position. But a node is receiving this node_info transmitted to the phone :
`node_info { num: -1409794164   position { time: 1595560935   }   user {  id: "!2462abf83f8c"  long_name: "ble"  macaddr: "$b\253\370?\214" short_name: "b" } }`

**Expected behavior**
position could have at least battery_level : 1 if they are on a battery

**Device info:**
 -  T-Beam v1.0 
 - firmware_version: "0.8.2"

**Smartphone information (if relevant):**
 - Android 6.0 phone
 - App Version : dev version

**Comment by geeksville** [comment]
thanks!  yep - the device code needs to send updates even when it doesn't have GPS lock.

already tracking in #249
