### ISSUE TITLE
Feature: Node Sensor Data Distribution

### ISSUE THREAD

**Issue by chron0** [meshtastic/Meshtastic-device#311]
After building my first meshtastic prototype I'd now like to hack around and see if nodes could act as sensor nodes to publish metrics into channels as well. After all, esp32 are capable platforms for all kinds of sensors they could query as a side task to extend the network not only for communication but for metrics as well.

Is there already something like this there or where would be a good place to hack around and extend this functionality?

**Comment by geeksville** [comment]
oh yes - I think that is best captured by this issue: https://github.com/meshtastic/Meshtastic-device/issues/182

Adding this would be awesome!

How about we merge the conversation over there?
