### ISSUE TITLE
Meshtastic User Groups

### ISSUE THREAD

**Issue by chron0** [meshtastic/Meshtastic-device#312]
Sorry if this isnt the best place to suggest this, but here it goes anyways:

Playing, debugging, testing and extending mesh networks is much more fun and feasible when not doing it alone. I love the idea of this kind of mesh network, similar to the basic idea of freifunk etc. so I think it would be great if we would try to get some local user groups going in our areas.

I'm giving it a start with: Munich, Germany

And for anyone else more oldschool like me: #meshtastic on freenode

**Comment by geeksville** [comment]
@chron0 I think that's a great idea.  How about I make a "Local users group" section on the forum?  And then you can make a thread for Germany?

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/about-the-regional-topics-category/1329/1

**Comment by geeksville** [comment]
Created a regional topic area (linked above).  Sorry it took so long.
