### ISSUE TITLE
Mixed frequency mesh

### ISSUE THREAD

**Issue by benner** [meshtastic/Meshtastic-device#319]
In EU it is possible to use 433 MHz and 868 MHz frequencies. It would be great if it will be possible to form mesh with mixed frequency into B.A.T.M.A.N routing (need special gateways with both bands). Now we did same kind of test/relay by just connecting two devices and using  `Meshtastic-python` to resend (bridge) blindly to different frequency device. By using this we loose valuable mesh/routing information.

**Comment by PA7John** [comment]
433Mhz can be used in my country too, like the idea, specially if it can be setup on say a PI.

**Comment by geeksville** [comment]
agree.
