### ISSUE TITLE
Publish APK on F-Droid

### ISSUE THREAD

**Issue by Alixpat** [meshtastic/Meshtastic-device#321]

**Comment by insanity54** [comment]
I would like to see Meshtastic on F-Droid

**Comment by geeksville** [comment]
> I would like to see Meshtastic on F-Droid

Alas, that probably won't be happening soon.  I'm on mobile now but the meshtastic-android GitHub issues has a good description on why...

I will keep doing apk releases though.

**Comment by insanity54** [comment]
Ah yes, thank you. I see the issue https://github.com/meshtastic/Meshtastic-Android/issues/6
