### ISSUE TITLE
[Bug]: ESP32 OTA Issues

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-device#3224]
### Category

Other

### Hardware

T-Beam, Heltec V3, Other

### Firmware Version

2.2.16+

### Description

Not sure if this is a firmware issue or an issue with the ESP32 DFU app. Opening here first as I'm unsure if it's the firmeware or the app. But it would appear that ESP32 OTA updating is broken. I've tried multiple devices using all of the most recent firmware versions and they all fail to update. 

Rebooting to OTA mode works, as does connecting to the device via BLE. Once I start the update it appears to work but then immediately stops and does nothing further. It does enough to prevent you from restarting the device though because it just goes to "Failsafe OTA" mode which means the only way to get it working again is to do a full wipe and install.

Appears to be an issue with both non-S3 and S3 devices. 
Devices Tried:
T-Beam
Heltec V3
Heltec WSLV3
Hydra
T-Deck

### Relevant log output

```Shell
*** App connected
80:b9:89:93:93:c2
main loop started
Writing to partition subtype 16 at offset 0x10000 
--Data received---
Final byte arrived
E (30503) esp_image: invalid segment length 0xffffffff
OTA end failed 
Writing to partition subtype 16 at offset 0x10000 
E (30952) esp_ota_ops: OTA image has invalid magic byte (expected 0xE9, saw 0x4d)
Error: write to flash failed
Writing to partition subtype 16 at offset 0x10000 
E (31284) esp_ota_ops: OTA image has invalid magic byte (expected 0xE9, saw 0x25)
Error: write to flash failed
Writing to partition subtype 16 at offset 0x10000 
E (31614) esp_ota_ops: OTA image has invalid magic byte (expected 0xE9, saw 0x20)
Error: write to flash failed
```
```

**Comment by aHVzY2g** [comment]
For me, it seems like the ESP32 is missing out on the first send chunk. I included some debugging inside writeDataToPeriheral() and this is the output reporting the first byte of each chunk sent to the ESP.

```
Start sending .bin file to device
First byte of subData package: E9
File transfer progress: 0.02%
First byte of subData package: 4D
File transfer progress: 0.05%
First byte of subData package: 25
File transfer progress: 0.07%
First byte of subData package: 20
```

**Comment by aHVzY2g** [comment]
Could be related to https://github.com/ClaesClaes/Arduino-ESP32-NimBLE-OTA-iOS-SwiftUI/issues/3

**Comment by aHVzY2g** [comment]
Most likely related, we also send `Chunk size: 509, 0x1FD` and have the same check in https://github.com/meshtastic/firmware-ota/blob/2fbe7fc4bf0848d48994a5c41690169ffc777a9c/src/main.cpp#L168
