### ISSUE TITLE
Information on device screens are "auto toggling".

### ISSUE THREAD

**Issue by drewsed** [meshtastic/Meshtastic-device#333]
Hi, 

I have Tbeam v 1.1 sx1262 and heltec hardware. On both the device info screens are not still and the information is toggling automatically. 

It does not matter which of the three device screens are selected in my mesh of 4 devices. on every page the info is changing once a second or less.

Already mentioned here:
https://meshtastic.discourse.group/t/setting-displaying-node-names/1113

Edit: added gif to demonstrate the issue:

![screenshift](https://user-images.githubusercontent.com/16530810/90986090-a381f880-e580-11ea-8d8d-a42cf4bc1271.gif)

**Comment by geeksville** [comment]
that's really strange.  Is it possible that there is a 3d printed button that is sticking down?

**Comment by geeksville** [comment]
interesting - I'll create a 4 node net and try to repro/fix.

**Comment by drewsed** [comment]
Good point, I also thought about that, but it is the same behavior on both TBeams (inside or outside the case) and on both Heltec devices. (Also the dots are only changing on a real button press, so there is no crosstalk on the pcb or so.)

There isn't a specific frequency or something related to an LED or so. On the heltec it switches the screens 1, 2, 3 with 1Hz and then there is a pause for about 3 seconds. After that again 1, 2, 3, pause, ...

On Tbean it is constantly 1 second between the change.

**Comment by eriktheV-king** [comment]
same happens here when I connect 1x SX1262 and 1x SX1278 and 2x SX1276:
 on SX1262 auto toggling at 1/second
but on SX127x's it changes at 1/sec and then pauses during 5 to 7 seconds

**Comment by PA7John** [comment]
My TTGO T3 Lora32 board (possible other models too) does not have a button to switch screens,  the switching screen  is/was a solution to that I think. Now my screen does not autochange an I only have access to the 1st screen, can not even see the battery status.
TBeam board does/did not autoswitch.

**Comment by drewsed** [comment]
Hi,
I don't think that this was a feature, because it toggled very fast some time. I read somewhere in the forum, that in this case adding a pushbutton is the way to go.

**Comment by PA7John** [comment]
I downgraded to  0.9.3 and the screens switch now as before. Is the pusbutton documented in detail?

**Comment by geeksville** [comment]
Alas @PA7John you'll need to add a switch if you want to see different screens.  I think only the lora32 is missing a switch.  We could add an enhancement to "auto cycle between screens every N seconds" and use that feature on boards without a switch.  If you want that would you mind putting in a bug so we don't forget (though it won't be super soon unless someone else does it)

**Comment by drewsed** [comment]
> I downgraded to 0.9.3 and the screens switch now as before. Is the pusbutton documented in detail?

That might help adding a pushbutton. I am not very familiar with the board names, but this thread covers a lot of boards.

https://meshtastic.discourse.group/t/ttgo-lora32-v2-v1-6-button/522/8

**Comment by PA7John** [comment]
Ok, thank you. Will look into the push button.
