### ISSUE TITLE
GPS position only updates on device reset or after a long time.

### ISSUE THREAD

**Issue by drewsed** [meshtastic/Meshtastic-device#339]
On TBeam v1.1, sx1262, NEO-8M with device-0.9.3 and android-0.9.04 the GPS position did not change for 15 minutes. On reset the position updates immediately.

I did test again for about 1.5 hours and the position did not change until pressing reset button.

(Also realized that my stationary node shows "No GPS" after being online for about 24 hours. After reset it got immediately 6 SATs and correct location. Lets see tomorrow... I will open a separate issue if this is not related.)

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/alpha-tester-thread-0-9-3-device-code-ready-for-testing/298/286

**Comment by geeksville** [comment]
see bug #150 for a dup

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/map-refreshing-delay/1073/8
