### ISSUE TITLE
reenable deep-sleep if no phone found

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#340]
we should reenable the timer that forces deep sleep if the radio hasn't been connected to a local PC.

**Comment by geeksville** [comment]
easy but too big a change before 1.0 so deferring

**Comment by sachaw** [comment]
@mc-hamster What's the current behavior surrounding this? Should it be fixed before or after the breaking release?

**Comment by thebentern** [comment]
Closing this. We've actually removed phone_sds_timeout_secs pref in 1.3.
