### ISSUE TITLE
integrate with Internet based text messaging services (riot.im etc...)

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#353]
Eventually this bug will be plan for the text message to internet gateway feature.  But for now misc notes:

* Work with a riot.im bridge?
* Investigate scuttlebutt: https://ssbc.github.io/scuttlebutt-protocol-guide/ - it could be ideal and already has the concept of store-and-forward

**Comment by android606** [comment]
Is this a duplicate of #8 ? That one mentions tox instead of riot, but aren't those both matrix clients and basically the same?

**Comment by geeksville** [comment]
@android606 oh yes, thanks! it is.  closing as dup of #8
