### ISSUE TITLE
Feature request: Method to set static Bluetooth pins

### ISSUE THREAD

**Issue by nconder** [meshtastic/Meshtastic-device#357]
Feature request: Method to set static Bluetooth pins in firmware so we can use devices without screens.

**Comment by geeksville** [comment]
good idea.

**Comment by BeardyWalrus** [comment]
I've tested a possible hack for this, if no screen is found, disable passcode requirements. 
This isn't ideal, as the screen is not used to show the passcode anyway. 
Would this be a valid fix? 
Should this patch be combined with the passcode shown on the screen if there is one?

**Comment by mc-hamster** [comment]
Closing issue. This was done in pr #450
