### ISSUE TITLE
Code typo: NEMA vs NMEA

### ISSUE THREAD

**Issue by a-f-G-U-C** [meshtastic/Meshtastic-device#362]
[NEMA](https://en.wikipedia.org/wiki/NEMA) is the National Electrical Manufacturers Association.
[NMEA](https://en.wikipedia.org/wiki/NMEA) is the National Marine Electronics Association.

NMEA designs protocols for navigation sensors and systems. NEMA designs powerplugs. :)

The Meshtastic source code frequently mis-references the **NMEA** standard GPS protocol as “NEMA”. While this is unlikely to cause any technical problems, I believe it should be corrected for the sake of accuracy.

**Comment by geeksville** [comment]
thanks!
