### ISSUE TITLE
Don't disable button while serial API is in use

### ISSUE THREAD

**Issue by andreyf2** [meshtastic/Meshtastic-device#371]
**Describe the bug**
PRG button, that normally switches screens on Heltec ESP32 LoRa makes nothing after sending the message from the Android App. But its other funktion is working.

**To Reproduce**
1. Connect the Heltec ESP32 LoRa Module to Android phone via OTG USB cable
2. Go to 'Meshtastic'  Android App
3. Select the /dev/bus/usb/<....> device in Radio selection menu
4. Go to 'Messages'
5. Write something and send the Message.
6. Try to scroll through screens

**Expected behavior**
The screen switching is working as usual

**Device info:**
 - Device model: [Heltec ESP32 868/915 LoRa Module without GPS]
 - Software Version [0.9.5]

**Smartphone information (if relevant):**
 - Device: [Alcatel 3v 5099d]
 - OS: [Android 8.0.0]
 - App Version [0.9.05]

**Additional context**
It looks like that the same problem is appearing after just waiting for too long while being connected to the App via USB

**Comment by geeksville** [comment]
thanks - yeah - I thought it would be a good idea to disable the button while the user is using API access to the device, but in retrospect that as a bad idea.  I'll fix.
