### ISSUE TITLE
TBeam shows "No GPS" in the upper right corner after some random time.

### ISSUE THREAD

**Issue by drewsed** [meshtastic/Meshtastic-device#373]
TBeam v1.1 sx1262 neo8m shows "No GPS" after some random time.
Sometimes this happens after a fresh boot, but most of the time a reset is fixing the issue for another random time.

My Setup is a mesh with 2/4 devices:
- 2 TBeams (online)
- 2 Heltecs (offline)

I was trying to capture some debug output, but as always it does not occour. 
**BUT** I captured the debug output having this issue on a fresh boot:
```
Emitting reboot packet for serial shell

ERROR: No UBLOX GPS found
Hoping that NEMA might work

```

I will update this post, if the error occurs during the evening or night, lets see.

I also thought about not getting the issue while plugged into a 5V charger.
My second device running on 18650 cell had the issue twice during the investigation ^^

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/timed-reboot-feature/1226/5

**Comment by drewsed** [comment]
Hmm, still no "No GPS" after running for about 14 hours.

**Comment by drewsed** [comment]
"Ni GPS" never appeared for me again since 0.9.6 and 0.9.7.

I will close this.
