### ISSUE TITLE
Implement HTTP server

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#374]
Features:

- Utilizes the esp32 web server library
- Feature toggle so this can be turned on/off from configuration.h

Assumptions:

- Initial assumption is this will be USB powered. No power savings will be implemented.
- More specific features will come in future tickets.
- This is only to get the framework of being able to serve HTTP.

Risks:

- It's known the existing esp32 http server uses a lot of blocking methods. For production production use (before a proper feature is rolled for general use), response handler for the http server should be moved into a FreeRTOS thread.

@geeksville Please assign this to me.

**Comment by geeksville** [comment]
I think this is a good idea.  With one caveat/opinion - we should only serve up static HTTP goo necessary to provide all the services either client side or client side talking to our existing meshtastic API service on port 4403.

Or perhaps: we could provide a small surface area REST API which just accepted a PUT to /ourresetapi/toradio and also a streaming GET reply of a series of fromradio protobufs.  We could provide those two REST endpoints with either bare protobuf framing or as JSON (but JSON based on the automatic JSON protobuf code).  This would allow us to keep essentially 'one' API across bluetooth, USB, TCP and HTTP.

**Comment by syssytheboss** [comment]
@mc-hamster It would be cool if the HTTP server could be accessed also by non-lora devices.I have a dummy TTGO T-Display that is only equiped with Wifi(I think it may have BT),so it would be cool to use an API(implemented by the server) and get messages displayed.

As a suggestion pure nodejs with express would be the best suit for this project.

For this moment I would really like to see a demo working system that use wifi and that can connect to the server for querring and placing messages.

Later on you could implement autentification and even communication chanels inside that specific server.

**Comment by mc-hamster** [comment]
See PR #384
