### ISSUE TITLE
Implement WIFI_MODE_STA

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#375]
Features:

- Toggle in configuration.h to enable wifi mode
- Configure SSID and Password from configuration.h
- Roam / Reconnect to AP when disconnected from current AP and connect to another AP
- Don't hang the device if unable to connect to an AP

Assumptions:
- This will be a bit more than enough to get started with implementing various services over IP.
- AP mode will be implemented at a later date.
- For the initial implementation, we will assume that the device will be powered by USB and we won't deal with power management.
- Initial target is to support reliable connections for a TCP/HTTP server
- It may be useful to support other protocols in the future. 

@geeksville Please assign this to me.

**Comment by syssytheboss** [comment]
@mc-hamster Looking forward to your ideeas.

**Comment by retrodime** [comment]
+1

**Comment by mc-hamster** [comment]
See PR #384
