### ISSUE TITLE
Gps power management problems

### ISSUE THREAD

**Issue by a-f-G-U-C** [meshtastic/Meshtastic-device#376]
There have been reports of sub-par performance of the ublox NEO-M8N GPS module under Meshtastic, and I have experienced some of it myself.

**Device model:** T22_V1.1 20191212 w/ u-blox NEO-M8N-0-10 GPS

Here are my observations and tentative fixes.

## "No UBLOX GPS"
Sometimes, on startup, the Sparkfun u-blox library fails to initialize the GPS module, causing a fallback to standard NMEA (on a finger-crossing basis, as NMEA may be disabled in the GPS settings). The relevant error message is:
```
ERROR: No UBLOX GPS found
Hoping that NEMA might work
```
This happens fairly frequently, for me it's a little more than **one in two cases**. 

The suspected cause is a problem in the Sparkfun library, which is currently being tentatively mitigated by repeating the initialization command twice in quick sequence.
https://github.com/meshtastic/Meshtastic-device/blob/288363b3a67d978ffa3b174d2280e2d647836ee4/src/gps/UBloxGPS.cpp#L48-L50

This mitigation is moderately effective, and I was able to improve it by adding a delay between the attempts:
```
    // try it a few times
    for (int i = 0; (i < 3) && !tryConnect(); i++)
        delay(500);
```
This fixed the UBLOX initialization problem for me.

## Long acquisition time, unstable tracking with frequent loss of lock

In areas with weak GPS signals, Meshtastic takes an exceptionally long time to acquire a satellite lock, much longer than other GPS receivers - up to 20 hours in one case. It also seems to have a weaker tracking ability, and the time to recover from a signal loss is painfully long, over 1h in some cases.
These periods of no-fix are visually indicated by a slow blink of the red GPS LED (5s on, 15s off).

What fixed this problem, in my case, was disabling the GPS power-saving mode, here:
https://github.com/meshtastic/Meshtastic-device/blob/288363b3a67d978ffa3b174d2280e2d647836ee4/src/gps/UBloxGPS.cpp#L84
(changing `true` to `false` above caused the GPS to perform as expected)

I suspect the cause of the problem is a too ambitious implementation of the power saving mode on the NEO-M8 GPS, which in my case resulted in a degraded experience. Fortunately, with the new GPS models from u-blox, the power-saving mode is not an on-off affair; it comes with a lot of fine-tuning options, and a good power-performance balance is probably achievable - just not with the default settings.

Further info: [u-blox M8 Power Management doc](https://www.u-blox.com/en/docs/UBX-13005162)

**Additional information**

May be related and relevant to the following issues: #373, #339

**Comment by geeksville** [comment]
ooh great!  I will definitely apply your hack and your power save fix.  I'll also repurpose this bug to (eventually) look into careful power management experiments for the M8 boards.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/timed-reboot-feature/1226/6

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/higher-power-consumption-than-expected/1424/5
