### ISSUE TITLE
display->drawStringMaxWidth does not work well with our screen transitions

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#379]
display->drawStringMaxWidth does not work well with our screen transitions.

When long or multi-line text is displayed on a screen using the display->drawStringMaxWidth method and we transition from the received text screen to the next screen, the text spills over into the next screen during the transition.

This is on the a custom build based on the 0.9.81 firmware.

Video of symptom:

http://www.casler.org/temp/IMG_0079.MOV

**Comment by garthvh** [comment]
Is this still an issue?

**Comment by mc-hamster** [comment]
Yes it is

**Comment by garthvh** [comment]
Deleted!
