### ISSUE TITLE
Some screen and usability suggestions

### ISSUE THREAD

**Issue by drewsed** [meshtastic/Meshtastic-device#387]
Random order of device screen tabs, sort alphabetical instead
===

In a mesh with more than 3 nodes, every node will have 2 device tabs, one for each remote device.

If you scroll the tabs around, there will always be a random order. Would be nice, if they would stay in the same order all the time. I would suggest, sorting them alphabetically.

Rearrange screen tabs
=====

Also I would suggest to rearrange the order overall. In a mesh with many devices, you habe to click many times to fet to the info screen. Moving them into the front would enable us to get infos on a single click frome "home":
1. Message screen (Home if exists)
2. Info screen (Home)
3. Info sceeen advanced
4. device A
5. ...

Add long press click event to button and use as home event
====

For quickly returning to the home screen I suggest adding a second click event to the button. Log press would be nice I think. Other clicks (double, tripple) will have huge impact on the responsive single click feedback, so I would avoid this.

**Comment by geeksville** [comment]
also - we might want to sort the node tabs by distance.

**Comment by mc-hamster** [comment]
closing for now. @thebentern has made some changes to this recently.

feel free to reopen if needed.
