### ISSUE TITLE
Feature Request: Power Profiles

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#389]
For configuring the Lora radio, there are 4 preset Lora radio configurations from "Short Range" down to "Very long range".

I propose that we have the same for overall power management with a range from "No Power Restrictions" where all power saving is disabled to "Sip Power" where the device will run for 8 days on a single 18650.

Possible options

- No Power Restrictions ... Never power down to save power. High GPS update frequency.
- Minimal Power Restrictions ... Never power down to save power. Low GPS update frequency.
- Medium Power Restriction ... Current default settings
- Sip Power ... Rarely turn on BLE. If there's a GPS, update once per hour.

I have no vested interest in the names or the definitions. Who ever works on this has creative license.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/device-profiles-in-app/1604/2
