### ISSUE TITLE
If app/API sets device settings, they should be saved immediately.

### ISSUE THREAD

**Issue by timgunter** [meshtastic/Meshtastic-device#393]
I have noticed that when I change "Your Name" using the Android App 0.9.90, the name change takes effect immediately. However, when I power cycle my heltec lora32(firmware v1.0.0), it forgets the name change and reverts back to the original name.

**Comment by geeksville** [comment]
This is kinda by design (though that might be a mistake).  We only save settings to flash when the radio goes to sleep normally.  If the power just gets yanked they won't get saved.

I'll change to save settings immediately if the app sets them.
