### ISSUE TITLE
dev-wifi: wifi does not come back up after power down (arduino-esp32 lib bug)

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#407]
WiFi doesn't come back up after being shut down.

This is due to a bug in the Espressif SDK was introduced in October 2019. Here's the PR to fix the issue in the SDK.

Seems like this bug was introduced when the wifi long range feature was rolled out and it's unknown how this fix will affect the long range feature.

espressif/arduino-esp32#4114

**Comment by mc-hamster** [comment]
The error message I was getting that lead me to the PR from espressif:

[WiFiSTA.cpp:158] begin(): disconnect failed!

**Comment by geeksville** [comment]
@mc-hamster that fix looks good to me.  I'll merge it into our local fork of arduino-esp32 this weekend.

**Comment by mc-hamster** [comment]
@geeksville I commented on the upstream issue and it seems like they've merged it into espressf:master a few days ago! We should update our fork.

**Comment by mc-hamster** [comment]
I'm going to take assignment on this.

**Comment by mc-hamster** [comment]
I'm chickening out of that. Just did a diff between the two -- there's a ton of changes on both sides on the ble area. I wouldn't be able to confidently merge the two.

**Comment by mc-hamster** [comment]
@crossan007 Thanks for your feedback of the http server not coming back up. This is now fixed too.
