### ISSUE TITLE
remove support for 8 bit node id/packet nums

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#415]
(now that 1.0 is out the old original system can be deprecated)

**Comment by sachaw** [comment]
@mc-hamster is this still applicable?

**Comment by mc-hamster** [comment]
generatePacketId(); // FIXME - ugly way to init current_packet_id;
/// Generate a unique packet id
// FIXME, move this someplace better
PacketId generatePacketId()
{
    static uint32_t i; // Note: trying to keep this in noinit didn't help for working across reboots
    static bool didInit = false;

    assert(sizeof(PacketId) == 4 || sizeof(PacketId) == 1);                // only supported values
    uint32_t numPacketId = sizeof(PacketId) == 1 ? UINT8_MAX : UINT32_MAX; // 0 is consider invalid

    if (!didInit) {
        didInit = true;

        // pick a random initial sequence number at boot (to prevent repeated reboots always starting at 0)
        // Note: we mask the high order bit to ensure that we never pass a 'negative' number to random
        i = random(numPacketId & 0x7fffffff);
        DEBUG_MSG("Initial packet id %u, numPacketId %u\n", i, numPacketId);
    }

    i++;
    PacketId id = (i % numPacketId) + 1; // return number between 1 and numPacketId (ie - never zero)
    return id;
}

**Comment by thebentern** [comment]
@mc-hamster is this still an active issue?

**Comment by garthvh** [comment]
Can we delete this now that 1.3 is the master branch?

**Comment by garthvh** [comment]
Code is totally gone, closing
