### ISSUE TITLE
Wifi in station mode sometimes enters loops of repeatedly joining...

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#420]
seen about 50% of boots:

```
************ [WiFi-event] event: 5 ************
Disconnected from WiFi access point
JOINING WIFI: ssid=geeksville
Started Joining WIFI
************ [WiFi-event] event: 5 ************
Disconnected from WiFi access point
JOINING WIFI: ssid=geeksville
Started Joining WIFI
************ [WiFi-event] event: 5 ************
Disconnected from WiFi access point
JOINING WIFI: ssid=geeksville
Started Joining WIFI
************ [WiFi-event] event: 5 ************
Disconnected from WiFi access point
JOINING WIFI: ssid=geeksville
Started Joining WIFI
************ [WiFi-event] event: 5 ************
Disconnected from WiFi access point
JOINING WIFI: ssid=geeksville
Started Joining WIFI
************ [WiFi-event] event: 5 ************
Disconnected from WiFi access point
JOINING WIFI: ssid=geeksville
Started Joining WIFI
************ [WiFi-event] event: 5 ************
Disconnected from WiFi access point
JOINING WIFI: ssid=geeksville
```

I'll bet it has to do with both BLE and wifi being connected at once and the final fix will be to "if configured for wifi, do not start BLE"

cc @mc-hamster

**Comment by mc-hamster** [comment]
Few possibilities for this:

1) Wifi ssid / password combination was entered wrong
2) Device is just outside the range of the AP and is having trouble maintaining an established connection.

**Comment by mc-hamster** [comment]
I've been able to reproduce this but for maybe only 10% of reboots. 

I think there's a race condition somewhere.

**Comment by mc-hamster** [comment]
Fixed it.

If it fails to associate the first time, it immediate calls the disconnect event and tries to reinit the wifi stack. Within the initwifi, I was attaching the the event handler.

WiFi.onEvent(WiFiEvent);

It's ok for that to be called multiple times, but not always. Very odd.

I refactored the initwifi function to create reconnectWiFi() for that situation.

**Comment by mc-hamster** [comment]
Also added a RSSI display on the screen which helped me debug this.

**Comment by mc-hamster** [comment]
Fixed. Checked into dev-wifi
