### ISSUE TITLE
Display multiple GPS coordinate formats

### ISSUE THREAD

**Issue by Kak1234** [meshtastic/Meshtastic-device#437]
@mc-hamster It would be nice to have the option to see the GPS coordinates in the Meshtastic radio screen in different formats that are compatible with topographic maps.

The suggested formats in **WGS84 geodetic datum**:

**LatLong in Decimal degrees** truncated to [4 decimal places](https://wiki.openstreetmap.org/wiki/Precision_of_coordinates) for  10 m precision (not usable with paper maps but good for computers & apps) (ie **48.8582, 2.2945**)
**UTM** with space between easting and northing (usable with maps and most navigators are familiar with) (ie **31U 448252 5411935**)
**MGRS** / USNG [truncated to 10m](https://www.maptools.com/tutorials/mgrs/quick_guide) and with a space between easting and northing (very readable, easy to learn, and easy to use with paper maps, NATO and Search and Rescue standard) (ie **31U DQ 4825 1193**)

I'm suggesting this formats because they are pretty international and standard in the professional and recreation world.

The coordinate formats could be chosen through the API or phone app.

**Comment by aHVzY2g** [comment]
Just for fun, and as it's kind of useful. I would love to see "plus code"/OLC
https://en.m.wikipedia.org/wiki/Open_Location_Code

**Comment by geeksville** [comment]
@aHVzY2g thanks for mentioning plus codes, I had never heard of them and it is nice to learn a new thing.

**Comment by mc-hamster** [comment]
DMS format would require 37 characters. In the current layout, we have 22 characters to work with. Implementing this would require redesigning the screen with the gps information.

Example worse case:

122° 6' 25.7832'' S 122° 6' 25.7832'' W

We can reduce the this by slightly changing the spacing, but that won't get close to 22 characters.

**Comment by sachaw** [comment]
+1 for MGRS

**Comment by mc-hamster** [comment]
Hmm ... Maybe the altitude can be hidden when longer coordinate formats are being displayed.

**Comment by sticilface** [comment]
I think this would be a great addition.  I would also appreciate if the UK grid reference system, or indeed others were possible.  An OS grid reference would allow you to find someone in the UK on a paper map which would be quite useful.  Especially in an emergency with no nearby working phone!  

I also think displaying the position of the other node, maybe with a magnetic bearing so you can use your compass to find them would be a good idea.

**Comment by tomasbrincil** [comment]
+1 for MGRS

**Comment by mc-hamster** [comment]
closed.

this is done.
