### ISSUE TITLE
Add mdns service

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#458]
Add an mdns service.

respond to:

Meshtastic-0000.local

(where 0000 is the device ID)

**Comment by mc-hamster** [comment]
This is done on the dev-https branch.

Instead of the hostname I suggested, I simplified it even further. If you have a device on the network, you can open your browser to:

http://meshtastic.local

This will be a much better user experience. The down side is this won't work if you have multiple mesh nodes on your network, but if that's the case -- you probably know what you're doing and don't need mdns name resolution.

**Comment by geeksville** [comment]
ooh this is super useful!
