### ISSUE TITLE
[Feature Request]: Add position to userPrefs.h

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-device#4580]
### Platform

NRF52, ESP32, RP2040, Linux Native

### Description

We need to add the ability to set the device's position (latitude, longitude, altitude) in the userPrefs.h file. This feature would serve two important purposes:

Provide a hardcoded fallback if something happens to the device that has a manually set position (such as remotely deployed nodes).
Which also solves the issue of the complaints about not being able to set the position remotely.

**Comment by gergy008** [comment]
I'm still a bit of a git newbie - I just come across this while I was adding custom MQTT server to the userprefs.h file. If no-one else solves this issue I'll attempt my first pull request after some testing and see if I can resolve this
