### ISSUE TITLE
TBeam T22_V1.0 20190612 NEO 6M

### ISSUE THREAD

**Issue by henkiejan1** [meshtastic/Meshtastic-device#459]
Hi,

I have a TBeam T22_V1.0 20190612 NEO 6M and can´t find that version in the manual and support list. What firmware version do i need??

Thank you very much!

**Comment by geeksville** [comment]
TBeam 1.0 is the right build for that board.  (And posting in github is fine - but in the future I bet you'll get quicker response in our friendly forum:[ meshtastic.discourse.group](https://meshtastic.discourse.group))
