### ISSUE TITLE
Enable the RX LNA

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#466]
The RX LNA on the SX1262 is disabled.

Enable this.

lora.setRxGain(true)

**Comment by mc-hamster** [comment]
Fix for this is in my branch.

**Comment by geeksville** [comment]
awesome!

**Comment by mc-hamster** [comment]
Going to Fort Fungston tomorrow. Will try it out there.

**Comment by mc-hamster** [comment]
This is done
