### ISSUE TITLE
Question: Heltec Lora support

### ISSUE THREAD

**Issue by abhatikar** [meshtastic/Meshtastic-device#508]
Hello,

Would Meshtastic work on Heltic wireless stick https://heltec.org/project/wireless-stick/ ?
I have this https://www.amazon.co.uk/MakerHawk-Development-0-49inch-Bluetooth-Intelligent/dp/B07ML6528K/ref=sr_1_4?dchild=1&keywords=HELTEC&qid=1604263915&s=electronics&sr=1-4
Would the heltec firmware prebuilt binary work on it ?

**Comment by mc-hamster** [comment]
Probably not. The screen is a totally different resolution. 

The rest of the device should work with a few tweaks.

**Comment by abhatikar** [comment]
Any plans to support that device?

**Comment by mc-hamster** [comment]
It can probably be made to work without the screen with fairly low effort, but resizing all of the UI just for that one resolution will be a bit of effort.

**Comment by abhatikar** [comment]
Would it be possible for a short call to explain how the code is organized and if it's possible, I could volunteer to add the support for the board.

thanks,

**Comment by mc-hamster** [comment]
Join the developer slack and I'll walk you through what I can.

https://join.slack.com/t/meshtasticdev/shared_invite/zt-i7g00myc-ZNBbmQt6FFWPAPXFkvSUaQ
