### ISSUE TITLE
bug in how we are setting the delays to avoid collisions

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#513]
yep and btw - there is a bug in how we are setting the delays to avoid collisions. The current delay calculation is not considering the expected airtime of the packet. Which is fine for the default long range/slow settings - because that’s what I used when I was developing. But now that more people are wanting to use the fast/shorter range settings, we should fix that. Fixing this will dramatically speed up the the ‘faster’ settings.

The fix is easy, would someone mind putting a bug in for meshtastic-device and I’ll do it soon.

From: https://meshtastic.discourse.group/t/bitrates-of-the-different-channel-settings/1705/4

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/bitrates-of-the-different-channel-settings/1705/5
