### ISSUE TITLE
Heltec 1.1.7 reboot when ask wifi host connection

### ISSUE THREAD

**Issue by folletto95** [meshtastic/Meshtastic-device#514]
As told on the forum, i found this bug: 
- https://meshtastic.discourse.group/t/heltec-1-1-7-reboot-when-ask-wifi-host-connection/1709

When you ask a connection from the python api via wifi, meshtastic --host “myipaddress” --info, the Heltec board whit firmware 1.1.7 disconnect itself  from the wifi accesspoint.

**To Reproduce**
1. Connect the node via a home access point
2. Ask a connection via a win 10 pc to a python api
3. The node disconnect itself from the access point

**Device info:**
 - Device model: Heltec 
 - Software Version: 1.1.7

**Smartphone information:**
 - Device: PC
 - OS: Win10
 - Python API: 1.1.7

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/heltec-1-1-7-reboot-when-ask-wifi-host-connection/1709/3
