### ISSUE TITLE
[Feature Request]: Meshtasticd as central daemon for dumb nodes

### ISSUE THREAD

**Issue by nmaas87** [meshtastic/Meshtastic-device#5146]
### Platform

Cross-Platform

### Description

Dear all,
coming from more of an LoRaWAN background and running some LoRa concentrators I am proposing following idea: Running a concentrator can be basically achieved by pluging in a USB concentrator into any ARM based SBC and running the packet-forwarder. The same kind of ease is currently missing for Meshtastic. Yes, we can run Meshtasticd if we got an SPI connected HAT/LoRa Radio - or we can run the Python API to talk to some complete Meshtastic node. However, the "middleway" is missing: An integration into Meshtasticd which would allow to integrate one or more USB/Serial connected Meshtastic nodes (be it with directed or omnidirectional antennas) into it and allow those to be used via Python API or Webclient. That would allow to use a node, e.g. a RAK11300 (which is only allowing USB/UART as an interface and does not poses a display, BT/WIFI or anything) as a stationary "accesspoint" to be run as a LoRaWAN concentrator while still having the mangement features if a normal node - and the ability to log data and manage that node directly via the SBC it is attached to.

**Comment by garthvh** [comment]
Concentrators are explicitly not supported by Lora p2p
