### ISSUE TITLE
TBeam continually reboots when connected to USB

### ISSUE THREAD

**Issue by crossan007** [meshtastic/Meshtastic-device#516]
**NOTE** 
I'm opening this ticket with the intent of closing it right away (probably) since I've found the solution and may help someone else in the future who finds this.

While connected to my computer for USB charging, the device continually reboots.

I tried with the battery in, battery out,  I tried doing a factory reset, and re-joining my mesh.

It turns out that having "Cura"  (3D Printing slicing software) open on the same machine to which a TBeam is plugged into will cause meshtastic to enter a bootloop.

**Comment by geeksville** [comment]
Btw cause of this is that cura is probably opening the serial port if any device that connects (to check if a 3d printer).  But tbeams (and most esp32 boards) use the serial port rts line to control RESET (to force bootloader entry).

I bet cura is also asserting RTS which causes reset.
