### ISSUE TITLE
[Bug]: Device crashes on nodedb update

### ISSUE THREAD

**Issue by liquidraver** [meshtastic/Meshtastic-device#5356]
### Category

Other

### Hardware

Station G2

### Firmware Version

2.5.13

### Description

(#5354 reopened)

I dug a little deeper, reinstalled everything from scratch with a full wipe.
Configured Name/Lora/Wifi/Fixed position and rebooted.
Everything is working.

Switched on my other node and immediately when the device gets a packet, tries to save the nodedb it crashes, reboots and forgets position and name.

Last log line on serial before reboot is:
Save /prefs/db.proto

**Comment by fifieldt** [comment]
Thanks for reporting, we appreciate it :)
