### ISSUE TITLE
Request: Hard code a location for non-gps units

### ISSUE THREAD

**Issue by plughie** [meshtastic/Meshtastic-device#536]
**Describe the feature request**
I have a couple of Heltec units without GPS that I would like to report from a static, hardcoded position. These will be fixed relay nodes with no use for a GPS, which would just draw extra unnecessary power.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device info:**
 - Heltec units running 1.1.8 firmware

**Smartphone information (if relevant):**
 - App Version [e.g. 0.7.2]

**Additional context**

**Comment by folletto95** [comment]
What app did you use for ios?

**Comment by plughie** [comment]
I used Android, but app and OS versions are irrelevant because relay nodes will not be app connected.

**Comment by IZ1IVA** [comment]
> **Describe the feature request**
> I have a couple of Heltec units without GPS that I would like to report from a static, hardcoded position. These will be fixed relay nodes with no use for a GPS, which would just draw extra unnecessary power.

I second that request, excellent idea!

**Comment by geeksville** [comment]
thanks good idea.  working on this now.

**Comment by geeksville** [comment]
In.  Run "meshtastic --setlat 32.7767 --setlon -96.7970 --setalt 1337".  If someone in this thread and has time and interest, it would be super great if you could send in a pull request to create the beginnings of "docs/python-cmd-guide.md" documenting these new flags (and eventually other things)

**Comment by IZ1IVA** [comment]
> In. Run "meshtastic --setlat 32.7767 --setlon -96.7970 --setalt 1337". If someone in this thread and has time and interest, it would be super great if you could send in a pull request to create the beginnings of "docs/python-cmd-guide.md" documenting these new flags (and eventually other things)

Done. I presume --setalt expects an altitude in feet, doesn't it?

**Comment by IZ1IVA** [comment]
Turns out it's metres. Or meters. Good!

**Comment by IZ1IVA** [comment]
I'm having an issue here... if I manually set the position of a LoRa32 board, meshtastic --info doesn't return any position at all. Indeed, this node is listed in the mesh but doesn't show up in the map.
