### ISSUE TITLE
Occasionally reset the time based on GPS

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#540]
Many boards (in particular TBEAMs) don't have a 32khz xtal.  Therefore they are just using an RC clock for timekeeping and that drifts pretty fast.

So the time of day clock (not millis() though) should be reset occasionally if !defined(HAS_HIGH_ACCURACY_CLOCK) when we receive GPS time.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/settime-command-periodically-via-bluetooth/1807/6

**Comment by mc-hamster** [comment]
The esp32 has internal methods to improve clock accuracy:

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html

**Comment by geeksville** [comment]
Most of this is fixed by #584 (though we should still reset the clock based on GPS occasionally (once a day?)
