### ISSUE TITLE
[Feature Request]: Add hardware support for wisblock sd-card slot + features

### ISSUE THREAD

**Issue by Woutvstk** [meshtastic/Meshtastic-device#5419]
### Platform

NRF52

### Description

Adding hardware support for the wisblock RAK15002 SD-card slot (rak19007, ...) 

Even with a small 2Gb sd-card. There is a ton of storage space available for a node.
Using this storage to save device/environment/power/... metrics for a long period.
Using this storage to save all packets received by the node.
Using this storage with the store and forward module
and any other logging

All this data can be dumped to client over Bluetooth on connecting or over lora (limited data of course)

I am very new to github and somewhat familiar with C++. I'll try adding these features myself but it will take a while. Any help/recommendations welcome.

**Comment by RichieFrame** [comment]
Extremely relevant #5083
