### ISSUE TITLE
REST API for SPIFFSS File Management

### ISSUE THREAD

**Issue by crossan007** [meshtastic/Meshtastic-device#550]
Partial user story

As Web UI for Meshtastic
I should be able to GET request a `/files` endpoint 
I should see a JSON object containing all of the files on the SPIFFS storage.

I should be able to POST new files to an HTTP endpoint

I should be able to DELETE files from an HTTP endpoint.

**Comment by mc-hamster** [comment]
Easy, ok. Will do.

**Comment by mc-hamster** [comment]
You forgot the 'why' or 'because' of your user story.

... teasing

**Comment by crossan007** [comment]
this is done, and available in the app starting with https://github.com/meshtastic/meshtastic-web/releases/tag/0.1.3
