### ISSUE TITLE
Feature: Add instructions for if the SPIFFS is not uploaded

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#552]
More than a few people are not uploading the SPIFFS when flashing the device. Provide a link to the instructions on the /index.html handler.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/want-to-help-alpha-test-this-build-1-1-20/1862/32
