### ISSUE TITLE
Cannot Set NodeInfo:Position

### ISSUE THREAD

**Issue by crossan007** [meshtastic/Meshtastic-device#555]
When `fixed_position` is `true`, it's conceivable that a user may want to administratively set a position.

It looks like the `Position` property is only stored in the `NodeInfo` message.

I don't see any way to "set" `NodeInfo` via a `ToRadio` packet (which makes setting a static position over protobuf not possible)

**Comment by geeksville** [comment]
sorry I didn't notice this one till now: you can send a position from the python or android app and that implicitly will update the position for that node.
