### ISSUE TITLE
[Bug]: No firmware Heltec V2_1

### ISSUE THREAD

**Issue by lykamspam** [meshtastic/Meshtastic-device#5556]
### Category

Other

### Hardware

Heltec v2.1

### Firmware Version

2.5.16

### Description

Where is firmware for heltec v2.1 ?
Is possible download firmware directly when web flasher dont work?

### Relevant log output

```Shell
I need it
```

**Comment by garthvh** [comment]
The heltec v2 is no longer supported via the web flasher.

**Comment by lykamspam** [comment]
Meybe make a table
esp32s3 == heltec v3
esp* = heltec v2.1
tlora-s3 == ?

etc.

**Comment by lykamspam** [comment]
> The heltec v2 is no longer supported via the web flasher.

How upgrading device without web falsher? where download firmware? I cant find

**Comment by garthvh** [comment]
You would need to build it
