### ISSUE TITLE
Reboot device over WiFi

### ISSUE THREAD

**Issue by crossan007** [meshtastic/Meshtastic-device#557]
I can't seem to find any mechanism to trigger a reboot of a device over WiFi.

There's a protobuf field for `FromRadio/rebooted` but I can't find anything to actually force a reboot.

This would be useful to be able to trigger a reboot from the webui.

either something in a Protobuf, or straight HTTP POST reboot trigger would suffice

Bonus points for Cisco-router-style `reboot at` command for rebooting at a timestamp

**Comment by mc-hamster** [comment]
A get request to /restart will restart the device
