### ISSUE TITLE
Feature: Force SoftAP if the user button is held down during startup.

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#560]
If the user button is held down during startup, force device into the SoftAP.

The sequence is ... hold down the middle button. push and let go of reset, count to 2 and let go of the middle button.

ssid: meshtasticAdmin
password: 12345678

**Comment by mc-hamster** [comment]
@crossan007 Said that the forced softap preference may get accidentally persisted in some workflows. I need to change how this is done to not save into radioConfig.preferences.*

**Comment by Black6spdZ** [comment]
is there a "user button" pin defined on boards without physical?

**Comment by mc-hamster** [comment]
On the boards with two buttons, there's a reset and the other button. It's the other button.

What do you mean, "without physical"?

**Comment by Black6spdZ** [comment]
that's what I initially thought accept wasn't sure if the "prog" button on this lora32 v1 wasn't defined correctly.. I just get a black screen and no boot after trying the enable softap feature

**Comment by mc-hamster** [comment]
I tied into the same button that's used to page through the screens of the oled. It's that button.

When you load it for the first time, it usually adds about 20-30 seconds to the boot up, but I've seen it take up to 45. It does this to generate 2048 bit cryptographic keys for the HTTPS server. You may be running into that.

Let's take this conversation to the community forum if you have more questions. This way other people can learn too :) 

I'm out for the day. Cheers!
