### ISSUE TITLE
Battery charge discrepancy between device and app

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/Meshtastic-device#566]
I'm charging a TTGO T-Beam via USB and its OLED display shows a 99% charge level, while the Android app reports 92%.

1.1.20 alpha firmware, 1.1.21 app version

Cheers

**Comment by geeksville** [comment]
ooh - I bet we should occasionally send a position update even if we don't have a gps lock.  because position (due to a mistake on my part) includes battery level.  or we should move battery level out of position
