### ISSUE TITLE
Features: Diy Esp32 board

### ISSUE THREAD

**Issue by folletto95** [meshtastic/Meshtastic-device#569]
Hi, can we make a setup for an “open” board where we can use a random esp32 and LoRa module connected together?

**Comment by geeksville** [comment]
hm.  you can do that already pretty much by using the tbeam (or heltec) or whatever configs.  Just change the gpio bindings as needed in configuration.h.  Does that help?

**Comment by geeksville** [comment]
also: good thread here: https://meshtastic.discourse.group/t/discussion-on-support-for-custom-build-targets-i-e-different-radio-chips-cpus-one-off-boards/104/25
