### ISSUE TITLE
Try lowering CPU voltage to 3V to save power

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#57]
From this idea: https://meshtastic.discourse.group/t/power-consumption-measurements/58

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/power-consumption-measurements/58/2

**Comment by mc-hamster** [comment]
really advice against doing this. 3V is right around the low voltage detection for the esp32 as we us it.
