### ISSUE TITLE
Improve esp32 RTC accuracy by setting ESP32_RTC_CLK_SRC_INT_8MD256

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#584]
The Espressif configuration ESP32_RTC_CLK_SRC_INT_8MD256 (aka CONFIG_ESP32_RTC_CLOCK_SOURCE_INTERNAL_8MD256) should be set to improve the accuracy of the RTC while device is sleeping.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-esp32-time-syscall

This can be found in sdkconfig and sdkconfig.h in arduino-esp32/tools/sdk/include/config

Those files say not to edit them directly.

**Comment by geeksville** [comment]
@mc-hamster  ooh thanks - I'll build a new version of the espressiv binaries in the next dayish with your idea!
