### ISSUE TITLE
Total Beginner Help :)

### ISSUE THREAD

**Issue by Mschp** [meshtastic/Meshtastic-device#585]
Hey I Just Randomly Bought This with no actual idea about its uses, i figured you can interact off the grid with this device and want to start learning what i can.
the Product I bought in 915MHZ.
https://www.banggood.com/2Pcs-LILYGO-TTGO-915MHz-SX1276-ESP32-LoRa-0_96-Inch-Blue-OLED-Display-bluetooth-WIFI-Module-IOT-Development-Board-p-1545115.html?rmmds=myorder&cur_warehouse=CN
I want to burn the appropriate firmware, and managed to figure out it was a board by heltec automation.
that looks exactly like this: 
![image](https://user-images.githubusercontent.com/76531873/103024852-50817780-4559-11eb-9e2d-2a62a1fd9005.png)
i was wondering if the \firmware-heltec-US-1.1.5.bin file is compatible.

**Comment by mc-hamster** [comment]
Hi @Mschp 

The best place for these questions is our community forum:
  https://meshtastic.discourse.group

This issue tracker is for feature requests and bug reports.

Cheers!
