### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by cronyx** [meshtastic/Meshtastic-device#587]
Hi, I was trying to build firmware from source according to the build instructions and received an error.
![Выделение_430](https://user-images.githubusercontent.com/2557102/103078317-a3534180-45e2-11eb-99cc-cec6349bbc6e.png)

**Comment by geeksville** [comment]
oh interesting!  It seems like the python in your platformio is old.  Can you check if you are running the latest version of platformio?  I think that "pio upgrade" will do this?

**Comment by geeksville** [comment]
this might help: https://docs.platformio.org/en/latest/faq.html#install-python-interpreter

**Comment by geeksville** [comment]
but just in case, I pushed a version of  our build script that I think will also work on python 2.x.  can you give it a try? (it will go into master in about an hr)

**Comment by cronyx** [comment]
> this might help: https://docs.platformio.org/en/latest/faq.html#install-python-interpreter

Hi, platformio version is 5.0.3
```
You're up-to-date!
PlatformIO 5.0.3 is currently the newest version available.
```

Python versions:
```
python -V
Python 2.7.12
python3 -V
Python 3.5.2
```

> but just in case, I pushed a version of our build script that I think will also work on python 2.x. can you give it a try? (it will go into master in about an hr)

Thanks, it work, but need some corrections:
```
# General options that are passed to the C and C++ compilers
projenv.Append(CCFLAGS=[
    "-DAPP_VERSION=" + verStr
    ])
```
