### ISSUE TITLE
timing going up and down (and not correct)

### ISSUE THREAD

**Issue by wakareva** [meshtastic/Meshtastic-device#604]
Hi,
on my 2 tbeam I've notice this uncorrect time counting.
As per the video the timing goes up and down and step from minutes to hours and back. In general after 4 minutes it step up to 74 or 93 hours also moving back in time. Plus sometime the time is too much bigger.
I hope the picture/video are usefull.

https://youtu.be/WqUp11axkXk
https://youtu.be/jKp-wvuiO1g
https://youtu.be/aG10zvHD9tM

![2020-12-29 10 32 37](https://user-images.githubusercontent.com/42495103/103281006-0b829880-49d2-11eb-9789-46dd8fd6d2a7.jpg)

**Comment by mc-hamster** [comment]
The number of hours on the screen calculates out roughly to some time Jan 1, 1970.

**Comment by mc-hamster** [comment]
The node's last_seen is probably being saved before gps lock is made and then after the device gets the gps lock, when we do getTime() it does the math based on the wrong time scale.

**Comment by wfang2002** [comment]
I have the same issue and created PR for the fix https://github.com/meshtastic/Meshtastic-device/pull/613

**Comment by geeksville** [comment]
thanks!  @wfang2002's fix is exactly correct!  somehow I must have nuked that line accidentally.
