### ISSUE TITLE
On boards with BATTERY_PIN defined, check for missing voltage divider net

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#626]
at power up:
enable internal pullup and see if the raw ADC value is saturated at Vcc
then enable internal pulldown and see if raw ADC value is stuck at ground

If both of these are true the voltage divider resistors must not be installed.  Disable battery sensing.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/ttgo-lora32-v2-0-battery-level/1989/18

**Comment by thebentern** [comment]
Closing
