### ISSUE TITLE
we should suspend lora send/recv during firmware update because it seems to break things

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#634]
the updater *really* doesn't like poorly timed isrs.

**Comment by Noki** [comment]
Maybe a dedicated update mode would work best:

- Trigger update
- Restart into dedicated update mode
- Upload and perform update
- Restart into updated version

And probably plan ahead for the following update paths:

- Bluetooth (Mobile App)
- Wifi (Web Upload via Webserver)
- Wifi (Automated download from URL)

**Comment by geeksville** [comment]
@noki great point.  i'll do that.

**Comment by geeksville** [comment]
done some time ago
