### ISSUE TITLE
Include more detail in the /json/report

### ISSUE THREAD

**Issue by ScriptBlock** [meshtastic/Meshtastic-device#635]
Please include some additional data in the /json/report endpoint. 

Some ideas that may be beneficial for data collection and reporting are:
- battery charge/status
- time on battery/charge
- environmental details (where possible) - attitude/orientation/acceleration changes of device, ambient temperature
- API or remote IP statistics

**Comment by ScriptBlock** [comment]
Ideally this telemetry would be configurable and opt-in (I think @geeksville said it was a future plan to do some of this).

**Comment by crossan007** [comment]
I would like this info as well for meshtastic-web

**Comment by crossan007** [comment]
Just opened a separate issue for some related items I'd like: https://github.com/meshtastic/Meshtastic-device/issues/636

**Comment by mc-hamster** [comment]
@ScriptBlock 

@crossan007 Added power stats.
I added memory and filesystem stats.

Those are the easy stats for us to get. This will go into the next alpha build.

I'm closing this request and marking it done. Please open a new request if there is a specific stat you'd like.

Thanks!

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/new-device-alpha-1-1-33/2270/1
