### ISSUE TITLE
Update airtime calculation to track in milliseconds instead of seconds

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#639]
Update airtime calculation to track in milliseconds instead of seconds.

a 24 byte packet at SF7->SF9 with a bandwidth of 125kHz will take at most 267ms. This will be rounded down to 0s in the current implementation.

We need better resolution.

Fix is to switch to 32bit counters and track milliseconds instead. This will double the memory requirement, but it would be needed to track usage of faster spreading factors.

Memory usage can be reduced by changing the number of periods we log.

**Comment by mc-hamster** [comment]
done

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/new-device-alpha-1-1-33/2270/1
