### ISSUE TITLE
build-all.sh will fail if it has never been run

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#650]
On the first run of build-all.sh, it will (line 27):

rm -r $OUTDIR/bins/*

That will fail if content within bins doesn't exist. On the first run, nothing inside that folder exists.

I got this error on MacOS and Linux.

**Comment by geeksville** [comment]
good find!  If you add "|| true" at the end of that line bash will ignore that failure.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/new-device-alpha-1-1-33/2270/1
