### ISSUE TITLE
Feature Request: Notification LED/Speaker

### ISSUE THREAD

**Issue by lureexcitingsalads** [meshtastic/Meshtastic-device#654]
Request to add an output that is briefly powered when a message is received. This could be used for an LED, buzzer, or horn.

Another scenario in which this might be useful is when trying to establish a connection over a long distance, and the signal strength goes from 0 to any number above.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/adding-a-simple-speaker/2209/5
