### ISSUE TITLE
Improve pointer / bearing accuracy

### ISSUE THREAD

**Issue by android606** [meshtastic/Meshtastic-device#662]
At walking speeds and relatively close distances, a GPS error of 3-5m+ can make your position pretty uncertain, which makes bearing calculations wonky and therefore make the pointer arrow on the screen noticeably inaccurate.

We should look into ways to make bearing calculations that are more accurate. Is it possible to use more points to generate an "average" bearing, perhaps?

See discussion at: [Discourse](https://meshtastic.discourse.group/t/direction-of-compass-orientation-device/1282/6)

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/direction-of-compass-orientation-device/1282/17

**Comment by mc-hamster** [comment]
closing this issue.

averaging really may not work since the drift will be the same for the averaged points.
