### ISSUE TITLE
Blink the LED when the button is double clicked and we enter disablePin()

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#664]
Blink the LED when the button is double clicked and we enter disablePin().

This will give feedback that we are successful with a double click.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/ble-just-works-pairing-for-screenless-devices/2273/12
