### ISSUE TITLE
Store & Forward Plugin

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#668]
New plugin that would **store** received packets on a router node.

A node can then send a **request** to the mesh to be the messages that it may have missed. The request can be automatic based on a set metric or manually triggered.

A router and client device would send a periodic heartbeat to let connected devices know that it is on the mesh.

Need to support n-number of routers, but will start with just one. Will use the port "PortNum_STORE_FORWARD_APP".

If a client device has not received a message or heartbeat from a router in x-minutes, it will consider itself disconnected from the primary mesh network.

Once it receives a forwarded message from a router directly or a heartbeat from a router, it will respond with an "I'm Back" message. This will indicate to the router that it should forward the most recently received packets.

**Comment by sachaw** [comment]
This should be able to be disabled when the configuring the node, maybe a nested configuration i.e routerSettings

**Comment by mc-hamster** [comment]
For now, it can go to the same place as the other plugin configurations in RadioConfig.UserPreferences but @geeksville discussed making a separate name space just for plugins.
