### ISSUE TITLE
Add restart counter

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#669]
Add a counter that increments every time the device is restarted.

Would be useful to track unmonitored device restarts.

Stat is in three places:

- Debug output on startup
- /json/report
- MyNodeInfo

**Comment by sachaw** [comment]
The ability to reset the centre would also be handy

**Comment by mc-hamster** [comment]
Good point. Easy to do.

**Comment by sachaw** [comment]
Yeah, either another flag when it is configured, i.e. `doReset` or an http APO endpoint
