### ISSUE TITLE
Range Test Plug-in

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#671]
Plug-in with two parts

1) Sender - sends a packet every n-seconds

2) Receiver - logs the received packet along with gps stats. Log will be available on the web server’s file system. The log file can then be used to generate a heat map for real-world coverage testing.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/antenna-improved-range/227/99

**Comment by mc-hamster** [comment]
Marking as done. It's in .48.
