### ISSUE TITLE
Typo on Website

### ISSUE THREAD

**Issue by karlhorky** [meshtastic/Meshtastic-device#673]
Hi, thanks for this project, really cool!

**Describe the bug**

The Meshtastic website at https://meshtastic.letstalkthis.com/ has a typo on it (`Andoid` without an `r`)

I looked for the website source code under [the `meshtastic` organization](https://github.com/meshtastic) to do a pull request but I guess it's not open source?

**To Reproduce**
1. Go to https://meshtastic.letstalkthis.com/
2. Scroll down
3. See typo

**Expected behavior**

No Typo

**Screenshots**

![Screen Shot 2021-02-01 at 15 32 51](https://user-images.githubusercontent.com/1935696/106472366-e4245d00-64a2-11eb-8dcd-b18050a4b5b0.png)

**Device info:**
 - Device model: -
 - Software Version -

**Smartphone information (if relevant):**
 - Device: -
 - OS: -
 - App Version -

**Comment by geeksville** [comment]
thanks for the note.  alas, we didn't make that (helpful) webpage.  I'll post where the author might see this.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/beginners-guide/717/10

**Comment by rezl** [comment]
This has been fixed. :)
