### ISSUE TITLE
Expose radio details of the current channel for more prominent display in the python API, app, and web server

### ISSUE THREAD

**Issue by thebentern** [meshtastic/Meshtastic-device#682]
It would be very nice to have the channel details that we only see currently in the logs (such as the operational frequency) exposed by the device in a way that is easily consumed by the python API, app, and web server.
![image](https://user-images.githubusercontent.com/9000580/107368194-dc1d7c00-6aa5-11eb-8261-fc88bdf5ea7e.png)

I have entered a complementary ticket in the python project to display these attributes in the --info output:
https://github.com/meshtastic/Meshtastic-python/issues/53

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/antenna-improved-range/227/107

**Comment by mc-hamster** [comment]
![Notification_Center](https://user-images.githubusercontent.com/12804989/107471477-09a80b00-6b22-11eb-9065-1fd97af2aa1f.png)
