### ISSUE TITLE
SPIFFS Enumerating Weirdly

### ISSUE THREAD

**Issue by crossan007** [meshtastic/Meshtastic-device#691]
Running @mc-hamster's branch at `8320754b985e8c8cebb42d72c3287fb1dab45d74`.

I'm seeing some weird duplication of files on SIPFFS:
![image](https://user-images.githubusercontent.com/11679900/107969443-c9131c00-6f7d-11eb-90f8-93c3ec51daa4.png)

After a full `factory_reset`, I'm seeing "shadows" of files that were previously on the device, but with 0 bytes:
![image](https://user-images.githubusercontent.com/11679900/107969515-dfb97300-6f7d-11eb-8027-2431bafb2b1c.png)

**Comment by crossan007** [comment]
Trying to delete one of these 0-byte static files shows this in `meshtastic --debug` logs:

```
[HTTPS:I] Request: GET /static?delete=static/index.html.gz (FID=59)
[E][vfs_api.cpp:238] VFSFileImpl(): fopen(/spiffs/static/index.html.gz) failed
[E][vfs_api.cpp:135] remove(): /static/index.html.gz does not exists or is directory
/static/index.html.gz
Trigger powerFSM 9
[HTTPS:I] Connection closed. Socket FID=59
[HTTPS:I] New connection. Socket FID=60
[HTTPS:I] Request: GET /static (FID=60)
```

**Comment by crossan007** [comment]
After a hard-reset, the files on SPIFFS now appear with non-zero sizes 🤔🤔🤔

**Comment by geeksville** [comment]
hehehe!

**Comment by mc-hamster** [comment]
Espressif is moving away from SPIFFS. It wouldn't surprise me that in a not so distant future SDK, SPIFFS would be deprecated entirely. Corruption is a frequent complaint.

**Comment by mc-hamster** [comment]
Closing. Please reopen if you see it again.
