### ISSUE TITLE
Add user pref to disable BLE / Wifi completely (or manually enable it via button on GPIO pin)

### ISSUE THREAD

**Issue by thebentern** [meshtastic/Meshtastic-device#696]
After doing some experimentation for my use case of long term low power repeater deployments, I believe that bluetooth / wifi is unnecessary for this application. It would be a really nice compliment to the router mode / low power prefs to have one that just disables BLE / Wifi. I will most likely be configuring and performing maintenance via usb serial. 

Another alternative option that might be preferable is to define a setting for GPIO pin mapping for a button on the board to initiate bluetooth manually. I think meshtastic-web already does something similar on a predefined pin for starting up the web service. This could prove very useful for OTA flashes of remote nodes that otherwise have no use for bluetooth.

**Comment by geeksville** [comment]
There is already an option for this.  I'll write more when I get home.

(Sent from a phone - please ignore typos)

**Comment by crossan007** [comment]
there is a mechanism in meshtastic-device which allows you to hold the user-button during device start-up to force the device into a SoftAP mode.  

not a function of meshtastic-web, but certainly useful for accessing meshtastic-web on a previously unconfigured device (https://github.com/meshtastic/Meshtastic-device/releases/tag/1.1.23)

**Comment by thebentern** [comment]
> not a function of meshtastic-web, but certainly useful for accessing meshtastic-web on a previously unconfigured device 
Right! That's what I was trying to think of. Sorry for conflating the device and meshtastic-web. I didn't separate the two in my head since I have meshtastic-web going on my home base station device.

**Comment by mc-hamster** [comment]
@thebentern This is nearly a year old. Still needed?

**Comment by thebentern** [comment]
@mc-hamster, I'm going to close this because I think it's rendered pretty irrelevant with my experience of NRF based devices and their low power consumption. Better to solve the problem with suitable hardware solution rather than bending the software around to make small gains. :-)
