### ISSUE TITLE
TLORA32 v1 doesnt sleep

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#702]
The v1 doesn't sleep when powered from battery.

I think this is because there's no battery sense

**Comment by IZ1IVA** [comment]
TLORA32s have an average power consumption of 65 mA. If sleep mode could be implemented, power consumption would drop to 10-11 mA, a fairly big improvement!

**Comment by mc-hamster** [comment]
Closed as a duplicate of #442
