### ISSUE TITLE
If no gps is found, we keep looking for a GPS by sending out of the gps tx pin and we never call _serial_gps->end()

### ISSUE THREAD

**Issue by zyrorl** [meshtastic/Meshtastic-device#704]
latest code in master activates buzzer on gpio 13 for TTGO Lora T3 V2.1.6 even if there's no gps attached

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device info:**
 - Device model: [e.g. TBEAM]
 - Software Version [e.g. 0.7.8]

**Smartphone information (if relevant):**
 - App Version [e.g. 0.7.2]

**Additional context**

**Comment by mc-hamster** [comment]
There are three causes of this.

1) A recent change sets the GPS TX pin for that board to GPIO 13.
2) The code to detect that the GPS is initialized doesn't look in the right place.
3) _serial_gps->end(); is never run to stop sending out of the GPS TX if no gps is found.

**Comment by garthvh** [comment]
https://github.com/meshtastic/Meshtastic-device/pull/1583
