### ISSUE TITLE
"00:01:08 68 [EnvironmentalMeasurementPlugin] Environmental Measurement Plugin: DISABLED; The SENSOR_READ_ERROR_COUNT_THRESHOLD has been exceed: 5"

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#707]
I see this repeatedly in the logs on my 1.2 dev branch.  Is this intended?  Did I mess things up wrt master?

Not urgent but fyi

**Comment by crossan007** [comment]
Yeah...   I have a mr coming soon to fix this.


It's because the plug-in is enabled by default, and you likely don't have a dht11 connected.

**Comment by crossan007** [comment]
It tries to read 5 times, and then gives up

**Comment by crossan007** [comment]
This should be resolved with #705.

The behavior is now documented in the protobufs: https://github.com/meshtastic/Meshtastic-protobufs/blob/master/mesh.proto#L929

**Comment by sachaw** [comment]
@geeksville is this solved?
@crossan007 any chance you can abbreviate your plugin naming, `environmentalMeasurementPluginMeasurementEnabled` is unsightly, maybe `envSensorPluginEnabled` or something along those lines.

**Comment by garthvh** [comment]
Is this still and open issue?

**Comment by crossan007** [comment]
We can probably close this?   

To be honest, I haven't really played with Meshtastic since fixing this issue.

**Comment by thebentern** [comment]
Closing. Feel free to open a new one if you get back into it.
