### ISSUE TITLE
recent breakage in master: "00:00:32 32 [Router] updating changed=0 user !abf84098/Unknown 4098/?98"

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#708]
the format string for time is wrong, it is showing seconds twice

**Comment by mc-hamster** [comment]
@geeksville I put that in there.

00:00:32 eventually turns into the system clock.
32 is the number of seconds since the system was started up.

It was getting difficult to see how long the system was up just based on the system time.

Happy to handle this some other way if you have ideas.
