### ISSUE TITLE
Devices sending location messages without a GPS fix are erasing markers off of map

### ISSUE THREAD

**Issue by DylanHoen** [meshtastic/Meshtastic-device#710]
Bug:
Devices sending location messages without a GPS fix are erasing markers off of map (At least that is my guess as to why markers are dissappearing from the map in 1.1.48).

Possible solution:
GPS coordinates should come with a time stamp of the time the coordinate actually came out of the GPS.  That way, if coordinates come through multiple paths, like store and forward repeaters, the actual newest coordinate can be determined and kept, and the actual older coordinate can be discarded, and the user could decide how old of a coordinates to keep displaying on the map.  If the device doesn't know where it is, that could be determined by the age of the timestamp being 10 minutes, or something, behind the current time, and graying out the marker on the map (cell phones usually have accurate time, syncing to an online time server each day, and a GPS coordinate usually comes with a timestamp accurate to miliseconds, and some times, microseconds).

**Comment by geeksville** [comment]
thanks for this.  I'll put out a 1.1.49 hotfix in the next couple of days.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/device-alpha-1-1-50-is-up-on-github/2699/1
