### ISSUE TITLE
the node should show bearing, distance, signal only if the last NODEINFO_APP msg received is not older than 2*interval

### ISSUE THREAD

**Issue by vinloren** [meshtastic/Meshtastic-device#717]
FEATURE PROPOSAL
It happens that the node shows other nodes reference in the mesh such as distance, bearing, signal regardless the fact that the other nodes are actually active just relaying on the last NODEINFO_APP / POSITION_APP received.
This approach might be inconsistent since in the test I made with a home node and a mobile node of mines with the home node not powered yet the mobile node shows bearing distance and signal referred to the home node.

That could be fixed if the node showed those data only if the last relevant NODEINFO_APP and POSITION_APP messages were received not earlier than 2xtime interval (default would be 2x900 secs.)

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/range-test-made-with-2xttgo-lora32-v1-weird-result/2675/4
