### ISSUE TITLE
SerialPlugin - Feature Request - Packet acknowledgement

### ISSUE THREAD

**Issue by msm395** [meshtastic/Meshtastic-device#718]
As suggested by mc-hamster, I have placed the link from the discourse forums in this feature request.

https://meshtastic.discourse.group/t/serialplugin-feature-request/2659

TLDR - Return acknowledgement of the packet if the packet has been received by another node.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/serialplugin-feature-request/2659/3

**Comment by garthvh** [comment]
Each mode will be responsible for this.
