### ISSUE TITLE
auto power on if USB power is connected

### ISSUE THREAD

**Issue by copykatze** [meshtastic/Meshtastic-device#720]
It would be great to change the behavior of the power button so the device would automatically power on if USB power is connected. I would love to put a device on my roof with a solar charger (and a battery), but as of now I guess I would need to climb up there every time the battery is drained.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/change-of-behavior-tbeams-will-now-stay-awake-if-they-have-usb-power/1364/4

**Comment by geeksville** [comment]
alas, see good comment from @mc-hamster in the thread.  If you are describing a TBEAM, the PMU chip on that board is wired in a way that doesn't allow this.
