### ISSUE TITLE
Build fails on nRF52832 target

### ISSUE THREAD

**Issue by xorbit** [meshtastic/Meshtastic-device#723]
**Describe the bug**
Building an nRF52832 target fails because it tries to build a nRF52840 file that is missing a structure member that apparently doesn't exist in the nRF52832.

**To Reproduce**
```
pio run --environment rak815 -t upload
```

**Expected behavior**
The project should build without errors.

**Screenshots**
```
Compiling .pio/build/rak815/FrameworkArduino/nordic/nrfx/mdk/system_nrf52840.c.o
/home/xxx/.platformio/packages/framework-arduinoadafruitnrf52/cores/nRF5/nordic/nrfx/mdk/system_nrf52840.c: In function 'SystemInit':
/home/xxx/.platformio/packages/framework-arduinoadafruitnrf52/cores/nRF5/nordic/nrfx/mdk/system_nrf52840.c:111:16: error: 'NRF_CCM_Type {aka struct <anonymous>}' has no member named 'MAXPACKETSIZE'
         NRF_CCM->MAXPACKETSIZE = 0xFBul;
                ^~
*** [.pio/build/rak815/FrameworkArduino/nordic/nrfx/mdk/system_nrf52840.c.o] Error 1
```

**Device info:**
 - Device model: RAK815
 - Software Version: Github master

**Additional context**
I'm actually trying to port to a new nRF52832 board and got this error.  So I verified it also exists in the only existing nRF52832 I could find, the RAK815.

**Comment by mc-hamster** [comment]
We support the RAK815 now.

Closing this issue. Feel free to open a new issue if you're still having the problem.
