### ISSUE TITLE
Packet source tracking

### ISSUE THREAD

**Issue by iz1kga** [meshtastic/Meshtastic-device#731]
Hello everyone,

This is for asking a new feature that allows to track packet source when it is repeated.

Some details on discourse:
https://meshtastic.discourse.group/t/packet-source-tracking/2764/2

Use case:
Allow the routing tracking capability adding data to an array containing routing history for eg. to draw the mesh configuration on a map or to understand the best position of a repeater node.

User Needs:
- User needs a variable containing routing history
- User needs the possibility to enable or disable the feature according to application needs

**Comment by MrSniffer** [comment]
It would be helpful if the routing information also included the rssi for each hop.

**Comment by garthvh** [comment]
There is quite a bit of logging of mesh traffic on both mobile apps and via serial and the CLI.
