### ISSUE TITLE
TX interrupt fault diagnostic has a bug?

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#734]
per https://meshtastic.discourse.group/t/newbie-questions-t-beam-critical-error-8/2787/2

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/newbie-questions-t-beam-critical-error-8/2787/3

**Comment by sachaw** [comment]
Very old issue with not enough info, closing.
