### ISSUE TITLE
CROSS-POST: TTGO TBeam Needs Newer Python Client After Firmware Install

### ISSUE THREAD

**Issue by tcote19** [meshtastic/Meshtastic-device#754]
Wasn't sure if this was necessarily related to the Python Repo or this one, so I'm cross-posting it from here
https://github.com/meshtastic/Meshtastic-python/issues/75

**Describe the bug**

**To Reproduce**
1. Downloaded Firmware 1.2.11 (https://github.com/meshtastic/Meshtastic-device/releases/tag/1.2.11)
2. Flashed device with "firmware-tbeam-1.2.11.bin".
3. Added Example Python script from this page (https://meshtastic.github.io/Meshtastic-python/meshtastic/index.html)
4. See error:

```
ERROR:root:Error while handling message from radio This device needs a newer python client, please "pip install --upgrade meshtastic"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meshtastic/__init__.py", line 678, in __reader
    self._handleFromRadio(self._rxBuf[HEADER_LEN:])
  File "/usr/local/lib/python3.9/site-packages/meshtastic/__init__.py", line 364, in _handleFromRadio
    raise Exception(
Exception: This device needs a newer python client, please "pip install --upgrade meshtastic"
```

**Expected behavior**
Things worky?

**Screenshots**
NA

**Device info:**
 - Device model: https://www.aliexpress.com/snapshot/0.html?orderId=8125368229366069&productId=4001178678568&edm_click_module=order_detail&tracelog=rowan&rowan_id1=destinationArriveV2_1_en_US_2021-02-04&rowan_msg_id=6069812536822935$dab8a1bfbcc644eab3cbf78775f10009&ck=in_edm_other
 - Software Version firmware-tbeam-1.2.11.bin

**Smartphone information (if relevant):**
NA

**Additional context**
I might be totally missing something obvious in the process of setting up the hardware and attempting to transmit data to/from the TTGO device. I'm new here 💯

**Comment by geeksville** [comment]
I think you might have accidentially installed the alpha release (all of the 1.2 builds are marked as alpha and pre-release).  You can either:

* install 1.1.50 (the current beta)
* type "pip install --upgrade meshtastic" to install the sister (also alpha) 1.2 command line tool.

More info here: https://meshtastic.discourse.group/t/using-the-python-api-during-the-1-2-transition/2730

(and if that doesn't work please post in the forum and our friendly gang of geeks will help)
