### ISSUE TITLE
Report Elevation while in range test, 

### ISSUE THREAD

**Issue by dave032285** [meshtastic/Meshtastic-device#758]
Reporting elevation during the range test would be sweet. I guess it would be practical use for someone setting up on a mountain or something, personally im mounting meshtastic devices to my drones for impractical range testing. Maybe not impractical. But not real world testing. Unless it was for an emergency of some sort. Youd have an idea of how high you need to be to reach specific areas,

Please - if you just have a question (i.e. not a bug report or a feature proposal), post in our [forum](https://meshtastic.discourse.group/) instead.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device info:**
 - Device model: [e.g. TBEAM]
 - Software Version [e.g. 0.7.8]

**Smartphone information (if relevant):**
 - App Version [e.g. 0.7.2]

**Additional context**

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/new-plugin-rangetestplugin/2591/66

**Comment by dave032285** [comment]
Its actually a feature request. Did i post in the worng place?

**Comment by geeksville** [comment]
@dave032285 no worries - that message wasn't really from me - it was just a side effect of your forum post linking here ;-)

**Comment by mc-hamster** [comment]
This is done.

**Comment by skycpdx** [comment]
Elevation and SNR fields (or headers) are backwards in the CSV

**Comment by mc-hamster** [comment]
> Elevation and SNR fields (or headers) are backwards in the CSV

Thank you. I opened a bug for this.
