### ISSUE TITLE
Allow device to route between internet and LoRa

### ISSUE THREAD

**Issue by texrg** [meshtastic/Meshtastic-device#8]
I think, many people need a router version. With ethernet cable.
Increase network and comunicating from/to internet
For example tox, matrix, wire <-> to lora

**Comment by geeksville** [comment]
oh yes, this is definitely a good idea, though given the limited bandwidth of LoRa I think the existing bluetooth (or serial via USB) link is probably sufficient.

**Comment by geeksville** [comment]
also - this feature will be built on top of https://github.com/meshtastic/Meshtastic-device/issues/169 (mqtt gateway support)

**Comment by mc-hamster** [comment]
Closing as duplicate of #169
