### ISSUE TITLE
Setting "is_router true" causes node to drop messages

### ISSUE THREAD

**Issue by Chiumanfu** [meshtastic/Meshtastic-device#801]
Turning on router mode causes messages to get lost across multi hop meshes.

A lot more details here
https://meshtastic.discourse.group/t/router-mode-missing-messages/3329

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/router-mode-missing-messages/3329/8

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/atak-for-hikers-signed-meshtastic-plugin/2229/57
