### ISSUE TITLE
Incorrect/Intermittent power sensing on RAK4630 boards

### ISSUE THREAD

**Issue by KevinKW87** [meshtastic/Meshtastic-device#815]
**Describe the bug**
Display of battery percentage remaining for RAK4630 boards is incorrect or intermittent in the Android app. I didn't have OLED displays connected, but it may be reporting incorrectly for those as well.

It will sometimes show battery percentage on first connection and then over time return to the "plug" symbol even when on battery power. Battery percentage may be incorrect as it has not changed for me over several days.

**To Reproduce**
1. Connect to a RAK4630 board via Bluetooth and the Android app.
2. Go to the Network List menu and view connected nodes.

**Expected behavior**
Correct battery percentage.

**Device info:**
 - Device model: RAK4630 w/RAK5005-O (Base)
 - Software Version 1.2.39

**Smartphone information (if relevant):**
 - Device: Pixel 3
 - OS: Android 11
 - App Version 1.2.31

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/25-low-power-dev-board-with-solar-rak4630-now-included-in-regular-builds/410/103

**Comment by geeksville** [comment]
Fixed by @claesg.  woot!
