### ISSUE TITLE
t-echo CLI

### ISSUE THREAD

**Issue by Justin4462** [meshtastic/Meshtastic-device#821]
**Describe the bug**
Unable to access t-echo via CLI

**To Reproduce**
Was unable to install Meshtatic via CLI.
Double pressed reset button to enter developermode.
Installed Meshtastic version 1.2.42 alpha via copy and paste to bootloader method. Install was succesful.
Still unable access device via CLI.

**Expected behavior**
CLI working to configure device 

**Additional Context**
I think I need the nRF52 equivalent of esptool and this may just be a documentation problem. I'll look into it after I sleep.

**Device info:**
 - Device model: T-ECHO
 - Software Version 1.2.42 alpha

**Comment by 24601** [comment]
Meshtastic CLI is connecting to my T-ECHO, same firmware and update process as your attempt, what version of the CLI are you using, though?

**Comment by geeksville** [comment]
hmm - I think this is working and haven't heard back.  Closing for now to keep queue tidy, please reopen if still an issue.
