### ISSUE TITLE
"Screen.h:290 error: 'SH1106Wire' does not name a type" error when enabling USE_SH1106 in config

### ISSUE THREAD

**Issue by dmitryelj** [meshtastic/Meshtastic-device#826]
**Describe the bug**
When enabling the USE_SH1106 define in configuration.h we get the compiler error:

_src/esp32/../graphics/Screen.h:290:5: error: 'SH1106Wire' does not name a type SH1106Wire dispdev;_

**Solution**
There is no link from Screen.h to configuration.h. Proper #include should be added at line 23 to Screeen.h:

`#include "../configuration.h"
`

**Comment by geeksville** [comment]
Hi @dmitryelj , thank you for this great report.  Alas, I don't have a board with a SH1106 to test with (and my coding time is super limited right now due to some health issues).  Would you be willing to send in a small pull-request with this change?

**Comment by dmitryelj** [comment]
Pull request created

**Comment by dmitryelj** [comment]
By the way, this issue is duplicated also here: https://github.com/meshtastic/Meshtastic-device/issues/797

**Comment by kylegordon** [comment]
Works great, thank you both :+1:
