### ISSUE TITLE
RAK4631 loses "owner name" upon powering down

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/Meshtastic-device#828]
**Describe the bug**
After the unit has been powered down, either by the user or on itself by battery depletion and subsequently powered back up, its "owner name" resets to the default "Unknown" + last four digits of its "id".

**Device info:**
 - Device model: RAK4631
 - Software Version: 1.2.43a

**Comment by geeksville** [comment]
ooh it sounds like we are not calling flash write after setting prefs from the API.  Will put as #3 in my queue

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/geeksvilles-current-task-list/514/57

**Comment by IZ1IVA** [comment]
Actually it has just happened also on a T-Beam running 1.2.42!

**Comment by IRainman** [comment]
Same problem on version 1.2.43. Problem is in both of NRF firmware and that's great realy :) 

> 
> 
> Actually it has just happened also on a T-Beam running 1.2.42!

**Comment by thebentern** [comment]
Is this issue still occurring for anyone on the latest release? I haven't experienced it on my RAK or T-Beam devices

**Comment by garthvh** [comment]
Nope

**Comment by thebentern** [comment]
Closing. If anyone is still experiencing this on the latest software, please open a new issue with the details.
