### ISSUE TITLE
I can't set a "Device sleep period" paramether to 0 on T-Echo device (this is additional bug in NRF52 devices)

### ISSUE THREAD

**Issue by IRainman** [meshtastic/Meshtastic-device#832]

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/geeksvilles-current-task-list-now-working-on-nrf52-fixes/514/63

**Comment by garthvh** [comment]
The nrf52 does not sleep.
