### ISSUE TITLE
Missing ROUTING_APP message

### ISSUE THREAD

**Issue by mraugit** [meshtastic/Meshtastic-device#833]
I have 3 T-Beams (V1.1). One ist acting as a gateway to a REST service at the internet (Python-API). The gateway has a fix power supply. The other 2 T-Beams are powered by battery. The gateway receives the NODEINFO_APP and POSITION_APP messages from the other 2 devices and sends TEXT_MESSAGE_APP messages to the other 2 devices ( with wantAck=True and destinationId=...).
If one of the 2 devices is in standby, the gateway receives a ROUTING_APP message with the information MAX_RETRANSMIT. The gateway uses this information to retry the transmition of the message. 

Sporatically the ROUTING_APP message is not available, wich brings my gateway application into an inconsistent state and could only be handled by an additional timeout.

I made some tests with changing the value of #define NUM_RETRANSMISSIONS 3. It seems that the behaviour get worsened by higher numbers.

**Comment by garthvh** [comment]
Seems like we can close this unless there are some additional details provided @thebentern
