### ISSUE TITLE
Critical fault #11

### ISSUE THREAD

**Issue by mraugit** [meshtastic/Meshtastic-device#841]
T-Beam 1.1 displays "Critical fault #11"

**To Reproduce**
I have 3 T-Beam and one ESP32-Paxcounter devices. The Paxcounter is connected to a PC Python application which sends text messages through the Python API to the 3 T-Beam devices. The T-Beam devices report position and status to the Paxcounter device which gives the data through the Python api to the PC application.

The 3 T-Beam's are powered by battery

**Expected behavior**
The device firmware should run stable for long time

**Device info:**
 - Device model: TBEAM 1.1
 - Software Version 1.2.44

Log sequence:

...
19:23:43 2269 [Router] Update DB node 0xf244e3a0, rx_time=1629919423
19:23:43 2269 [Router] NOTE: tophone queue is full, discarding oldest
19:23:43 2269 [Router] Plugin routing considered
19:23:43 2269 [RadioIf] Can not send yet, busyRx
19:23:44 2269 [RadioIf] (bw=125, sf=7, cr=4/5) packet symLen=1 ms, payloadSize=48, time 119 ms
19:23:44 2269 [RadioIf] Lora RX (id=0x37aadf84 Fr0xa0 To0xff, WantAck0, HopLim2 Ch0x5d encrypted rxSNR=12.5)
19:23:44 2269 [RadioIf] AirTime - Packet received : 119ms
19:23:44 2269 [Router] Found existing packet record for fr=0xf244e3a0,to=0xffffffff,id=0x37aadf84
19:23:44 2269 [Router] Add packet record (id=0x37aadf84 Fr0xa0 To0xff, WantAck0, HopLim2 Ch0x5d encrypted rxSNR=12.5)
19:23:44 2269 [Router] Ignoring incoming msg, because we've already seen it (id=0x37aadf84 Fr0xa0 To0xff, WantAck0, HopLim2 Ch0x5d encrypted rxSNR=12.5)
19:23:44 2269 [Router] Incoming message was filtered 0xf244e3a0
19:23:44 2269 [RadioIf] Starting low level send (id=0x37aadf84 Fr0xa0 To0xff, WantAck0, HopLim2 Ch0x5d encrypted rxtime=1629919423 rxSNR=12.25 priority=64)
**19:23:44 2270 [RadioIf] NOTE! Recording critical error 11 at src/mesh/RadioLibInterface.cpp:13c**
19:23:44 2270 [RadioIf] Completed sending (id=0x37aadf84 Fr0xa0 To0xff, WantAck0, HopLim2 Ch0x5d encrypted rxtime=1629919423 rxSNR=12.25 priority=64)
**19:23:44 2270 [Screen] Screen: Critical error 11!**
19:23:48 2274 [Power] Battery: usbPower=0, isCharging=0, batMv=4108, batPct=100
19:24:08 2294 [Power] Battery: usbPower=0, isCharging=0, batMv=4107, batPct=100
19:24:08 2294 [PowerFSM] lsEnter begin, ls_secs=300
19:24:08 2294 [PowerFSM] Setting bluetooth enable=0
19:24:08 2294 [PowerFSM] advertise complete; reason=29error enabling advertisement; rc=30
19:24:08 2294 [PowerFSM] Done shutting down bluetooth
Shutdown BT: 212120 heap size
...

**Comment by thebentern** [comment]
That error code represents an SPI communication failure to the radio and is most likely a hardware issue, since this report is isolated. I'm closing the issue for now. If this occurs again on the latest device firmware (1.2.50 at this time), please open a new github issue and tag me in it. Thanks
