### ISSUE TITLE
RFE: do not power-cycle GPS module if gps_update_interval is small

### ISSUE THREAD

**Issue by a-f-G-U-C** [meshtastic/Meshtastic-device#844]
This is based on my observations running Meshtastic in stand-alone mode on the tbeam 1.1-M8N-SX1262, but may also apply to other boards using UBlox GPS modules.

For power saving reasons, Meshtastic attempts to only power on the GPS module when required to update the location data, then immediately power it back off. The cycle is repeated every `gps_update_interval` seconds. 
In theory, the power saving is achieved by eliminating the idle current consumption of the GPS **when it's not needed**.

However, on the M8N module at least, the power-up boot sequence takes approximately 30 seconds, and is arguably the most power-intensive of all operating modes. It also has a degradation effect on GPS accuracy due the first valid data point being chosen every time. 

Therefore, while I can see this working in a scenario where the GPS is only read infrequently (every hour or so), I suspect that for small values of gps_update_interval (about 60 seconds or less), the inconveniences associated with the power-cycle loop outweigh any power-saving benefits.

**Suggestion:**
The GPS power cycling feature should be disabled if the user-specified `gps_update_interval` value is under a certain threshold.
This would improve (or **un-degrade** :) ) the GPS speed and accuracy as well as the user experience, and should not have a significant impact on power consumption.

**Additionally**
May be relevant to old issue #376

**Comment by geeksville** [comment]
fixed by #847
