### ISSUE TITLE
Sync Meshtastic RadioLib to upstream

### ISSUE THREAD

**Issue by osmanovv** [meshtastic/Meshtastic-device#849]
Hi, in case to add support for the new radio modules, I have merged the actual RadioLib changes from upstream `jgromes/RadioLib` to the `Meshtastic/RadioLib`. It fixes many bugs and adds support for the new modules.

Need someone to check and merge those changes for further development.

Pull request to check: https://github.com/meshtastic/RadioLib/pull/2

**Comment by geeksville** [comment]
OMG thank you for doing this!
