### ISSUE TITLE
UBLOX GPS - location data can get overwritten with invalid values

### ISSUE THREAD

**Issue by a-f-G-U-C** [meshtastic/Meshtastic-device#857]
In `UBloxGPS.cpp`, the latitude/longitude variables are populated with data from GPS **BEFORE** the data is validated, allowing in some cases invalid data to overwrite previous good data. 

This is where the variables get overwritten:
https://github.com/meshtastic/Meshtastic-device/blob/21f3cc6f7a5225bacb08d835cab829b6c844a8d1/src/gps/UBloxGPS.cpp#L180-L183
The data validation occurs too late:
https://github.com/meshtastic/Meshtastic-device/blob/21f3cc6f7a5225bacb08d835cab829b6c844a8d1/src/gps/UBloxGPS.cpp#L192

This, in combination with the sticky behaviour of `hasValidLocation` (per issue #843) may result in invalid location data being presented as valid and current.

**I have a working fix for this issue, in the process of cleaning it up for a PR submission**

**Comment by geeksville** [comment]
great fix!

**Comment by a-f-G-U-C** [comment]
Thank you.
