### ISSUE TITLE
Can not send yet, busyTx

### ISSUE THREAD

**Issue by tomasbrincil** [meshtastic/Meshtastic-device#860]
Hi there, I am using T-Beam v 1.1 sx1262, I am trying to desolder original chip a and wire G-NiceRF sx1262 module with integrated power amplifier (I am licenced ham I should know what I am doing :))

![image](https://user-images.githubusercontent.com/16230374/132523165-e1c7415f-1af0-4323-86ee-18993b8b39e3.png)

Considering same wiring for G-NiceRF module as original module there is some issue when trying to transmit.

> [15:40:40]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> [15:40:40]configsip: 0, SPIWP:0xee
> [15:40:40]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> [15:40:40]mode:DIO, clock div:2
> [15:40:40]load:0x3fff0018,len:4
> [15:40:40]load:0x3fff001c,len:1044
> [15:40:40]load:0x40078000,len:8896
> [15:40:40]load:0x40080400,len:5828
> [15:40:40]entry 0x400806ac
> [15:40:41][D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
> [15:40:41][15:40:41]??:??:?? 0 Filesystem files:
> [15:40:41]??:??:?? 0   /prefs/db.proto
> [15:40:41]??:??:?? 0   /prefs/radio.proto
> [15:40:41]??:??:?? 0   /prefs/channels.proto
> [15:40:41]??:??:?? 0 I2C device found at address 0x34
> [15:40:41]??:??:?? 0 axp192 PMU found
> [15:40:41]??:??:?? 0 I2C device found at address 0x3c
> [15:40:41]??:??:?? 0 ssd1306 display found
> [15:40:41]??:??:?? 0 done
> [15:40:41]??:??:?? 0 Meshtastic hwvendor=4, swver=1.2.45.a27ebda-d, hwver=unset
> [15:40:41]??:??:?? 0 Setting random seed 293909529
> [15:40:41]??:??:?? 0 Total heap: 254984
> [15:40:41]??:??:?? 0 Free heap: 221212
> [15:40:41]??:??:?? 0 Total PSRAM: 4194252
> [15:40:41]??:??:?? 0 Free PSRAM: 4194252
> [15:40:41]??:??:?? 0 NVS: UsedEntries 70, FreeEntries 560, AllEntries 630
> [15:40:41]??:??:?? 0 Setup Preferences in Flash Storage
> [15:40:41]??:??:?? 0 Number of Device Reboots: 29
> [15:40:41]??:??:?? 0 Initial packet id 1718671776, numPacketId 4294967295
> [15:40:41]??:??:?? 0 Setting default channel and radio preferences!
> [15:40:41]??:??:?? 0 Expanding short PSK #1
> [15:40:41]??:??:?? 0 Wanted region 0, using Unset
> [15:40:41]??:??:?? 0 Loading /prefs/db.proto
> [15:40:41]??:??:?? 0 Loaded saved preferences version 11
> [15:40:41]??:??:?? 0 Loading /prefs/radio.proto
> [15:40:41]??:??:?? 0 Loading /prefs/channels.proto
> [15:40:41]??:??:?? 0 Number of Device Reboots: 29
> [15:40:41]??:??:?? 0 Expanding short PSK #1
> [15:40:41]??:??:?? 0 Wanted region 0, using Unset
> [15:40:41]??:??:?? 0 region=0, NODENUM=0xf267a2b8, dbsize=1
> [15:40:41]chip id detect 0x3
> [15:40:41]Detect CHIP :AXP192
> [15:40:41]OUTPUT Register 0x5f
> [15:40:41]??:??:?? 0 AXP192 Begin PASS
> [15:40:41]??:??:?? 0 DCDC1: ENABLE
> [15:40:41]??:??:?? 0 DCDC2: ENABLE
> [15:40:41]??:??:?? 0 LDO2: ENABLE
> [15:40:41]??:??:?? 0 LDO3: ENABLE
> [15:40:41]??:??:?? 0 DCDC3: ENABLE
> [15:40:41]??:??:?? 0 Exten: ENABLE
> [15:40:41]??:??:?? 0 ----------------------------------------
> [15:40:41]??:??:?? 0 DCDC1: ENABLE
> [15:40:41]??:??:?? 0 DCDC2: ENABLE
> [15:40:41]??:??:?? 0 LDO2: ENABLE
> [15:40:41]??:??:?? 0 LDO3: ENABLE
> [15:40:41]??:??:?? 0 DCDC3: ENABLE
> [15:40:41]??:??:?? 0 Exten: ENABLE
> [15:40:41]SRC REG:0xc4
> [15:40:41]Charging enable is enable
> [15:40:41]Charging target-voltage : 0x2
> [15:40:41] end when the charge current is lower than 10% of the set value
> [15:40:41]Charge current : 700.00 mA
> [15:40:41]??:??:?? 0 Battery: usbPower=1, isCharging=1, batMv=4187, batPct=100
> [15:40:41]??:??:?? 0 Read RTC time as 408 (cur millis 209) quality=0
> [15:40:41]??:??:?? 0 WANT GPS=1
> [15:40:41]??:??:?? 0 Setting GPS power=1
> [15:40:41]??:??:?? 0 Connected to UBLOX GPS successfully
> [15:40:42]??:??:?? 0 External Notification Plugin Disabled
> [15:40:42]??:??:?? 0 Turning on screen
> [15:40:42]??:??:?? 0 Starting meshradio init...
> [15:40:42]??:??:?? 0 (bw=31, sf=9, cr=4/8) packet symLen=16 ms, payloadSize=16, time 1363 ms
> [15:40:42]??:??:?? 0 Set radio: name=LongSlow, config=3, ch=0, power=0
> [15:40:42]??:??:?? 0 Short packet time: 1363 msec
> [15:40:42]??:??:?? 0 Lowering transmit power because of regulatory limits
> [15:40:42]??:??:?? 0 Set radio: final power level=8
> [15:40:42]??:??:?? 1 RF95 init result -2
> [15:40:42]??:??:?? 1 Warning: Failed to find RF95 radio
> [15:40:42]??:??:?? 1 Starting meshradio init...
> [15:40:42]??:??:?? 1 (bw=31, sf=9, cr=4/8) packet symLen=16 ms, payloadSize=16, time 1363 ms
> [15:40:42]??:??:?? 1 Set radio: name=LongSlow, config=3, ch=0, power=0
> [15:40:42]??:??:?? 1 Short packet time: 1363 msec
> [15:40:42]??:??:?? 1 Lowering transmit power because of regulatory limits
> [15:40:42]??:??:?? 1 Set radio: final power level=8
> [15:40:42]??:??:?? 1 SX1262 init result 0
> [15:40:42]??:??:?? 1 SX1262 Radio init succeeded, using SX1262 radio
> [15:40:42]??:??:?? 1 Not using WIFI
> [15:40:42]??:??:?? 1 PowerFSM init, USB power=1
> [15:40:42]??:??:?? 1 Enter state: BOOT
> [15:40:42][D][esp32-hal-cpu.c:189] setCpuFrequencyMhz(): PLL: 320 / 4 = 80 Mhz, APB: 80000000 Hz
> [15:40:42]??:??:?? 1 [Power] Battery: usbPower=1, isCharging=1, batMv=4187, batPct=100
> [15:40:42]??:??:?? 1 [Screen] Screen: Started...
> [15:40:42]??:??:?? 1 [GPS] publishing GPS lock=0
> [15:40:42]??:??:?? 1 [GPS] No GPS lock
> [15:40:42]??:??:?? 1 [GPS] got gps notify time=0, lat=0, bat=100
> [15:40:42]??:??:?? 1 [GPS] DB update position node=0xf267a2b8 time=0, latI=0, lonI=0
> [15:40:42]??:??:?? 1 [GPS] Node status update: 0 online, 1 total
> [15:40:42]??:??:?? 1 [SerialPlugin] Serial Plugin Disabled
> [15:40:42]??:??:?? 1 [StoreForwardPlugin] Store & Forward Plugin - Disabled
> [15:40:42]??:??:?? 1 [RangeTestPlugin] Range Test Plugin - Disabled
> [15:40:45]??:??:?? 4 [PowerFSM] Enter state: POWER
> [15:40:45]??:??:?? 4 [PowerFSM] Setting bluetooth enable=1
> [15:40:45]??:??:?? 4 [PowerFSM] Not using WIFI
> [15:40:45]Pre BT: 209528 heap size
> [15:40:45]??:??:?? 4 [PowerFSM] Starting bluetooth
> [15:40:46]??:??:?? 4 [Screen] Screen: Powered...
> [15:40:46]??:??:?? 4 BLE task running
> [15:40:46]??:??:?? 4 registered service 0x1800 with handle=1
> [15:40:46]??:??:?? 4 registered service 0x1801 with handle=6
> [15:40:46]??:??:?? 4 registered service 6ba1b218-15a8-461f-9fa8-5dcae273eafd with handle=10
> [15:40:46]??:??:?? 4 registered service cb0b9a0b-a84c-4c0d-bdbb-442e3144ee30 with handle=18
> [15:40:46]??:??:?? 4 BLE advertisting type=0, Private=0, Device Address: 95:08:3a:f2:67:a2
> [15:40:46]
> [15:40:47]??:??:?? 5 [Screen] Done with boot screen...
> [15:40:47]??:??:?? 5 [Screen] showing standard frames
> [15:40:47]??:??:?? 5 [Screen] Showing 0 plugin frames
> [15:40:47]??:??:?? 5 [Screen] Total frame count: 35
> [15:40:47]??:??:?? 5 [Screen] Added plugins.  numframes: 0
> [15:40:47]??:??:?? 5 [Screen] Finished building frames. numframes: 2
> [15:40:47]??:??:?? 5 [Screen] Setting fast framerate
> [15:40:47]??:??:?? 5 [Screen] Setting idle framerate
> [15:41:02]??:??:?? 21 [Power] Battery: usbPower=1, isCharging=1, batMv=4187, batPct=100
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Sending our nodeinfo to mesh (wantReplies=1)
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] sending owner !f267a2b8/Unknown a2b8/?B8
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Update DB node 0xf267a2b8, rx_time=0
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] handleReceived (id=0x6670d9a3 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=4 WANTRESP priority=10)
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Plugin nodeinfo wantsPacket=1
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Received nodeinfo from=0xf267a2b8, id=0x6670d9a3, portnum=4, payloadlen=40
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] old user !f267a2b8/Unknown a2b8/?B8
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] updating changed=0 user !f267a2b8/Unknown a2b8/?B8
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Plugin nodeinfo considered
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Plugin routing wantsPacket=1
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Received routing from=0xf267a2b8, id=0x6670d9a3, portnum=4, payloadlen=40
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Routing sniffing (id=0x6670d9a3 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=4 WANTRESP priority=10)
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] FIXME-update-db Sniffing packet
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Delivering rx packet (id=0x6670d9a3 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=4 WANTRESP priority=10)
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Forwarding to phone (id=0x6670d9a3 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=4 WANTRESP priority=10)
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Update DB node 0xf267a2b8, rx_time=0
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Plugin routing considered
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Add packet record (id=0x6670d9a3 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=4 WANTRESP priority=10)
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Expanding short PSK #1
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] Installing AES128 key!
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] enqueuing for send (id=0x6670d9a3 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0xb1 encrypted priority=10)
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] (bw=31, sf=9, cr=4/8) packet symLen=16 ms, payloadSize=62, time 3084 ms
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] txGood=0,rxGood=0,rxBad=0
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] AirTime - Packet transmitted : 3084ms
> [15:41:12]??:??:?? 30 [NodeInfoPlugin] xmit timer 2540
> [15:41:12]??:??:?? 30 [Screen] Screen: Joined: Unknown a2b8
> [15:41:14]??:??:?? 33 [RadioIf] delay done
> [15:41:14]??:??:?? 33 [RadioIf] Starting low level send (id=0x6670d9a3 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0xb1 encrypted priority=10)
> [15:41:22]??:??:?? 41 [Power] Battery: usbPower=1, isCharging=1, batMv=4187, batPct=100
> [15:41:42]??:??:?? 60 [PositionPlugin] Sending position to mesh (wantReplies=1)
> [15:41:42]??:??:?? 60 [PositionPlugin] Stripping time 0 from position send
> [15:41:42]??:??:?? 60 [PositionPlugin] Update DB node 0xf267a2b8, rx_time=0
> [15:41:42]??:??:?? 60 [PositionPlugin] handleReceived (id=0x6670d9a4 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=3 WANTRESP priority=10)
> [15:41:42]??:??:?? 60 [PositionPlugin] Plugin position wantsPacket=1
> [15:41:42]??:??:?? 60 [PositionPlugin] Received position from=0xf267a2b8, id=0x6670d9a4, portnum=3, payloadlen=2
> [15:41:42]??:??:?? 60 [PositionPlugin] DB update position node=0xf267a2b8 time=0, latI=0, lonI=0
> [15:41:42]??:??:?? 60 [PositionPlugin] Node status update: 0 online, 1 total
> [15:41:42]??:??:?? 60 [PositionPlugin] Plugin position considered
> [15:41:42]??:??:?? 60 [PositionPlugin] Plugin routing wantsPacket=1
> [15:41:42]??:??:?? 60 [PositionPlugin] Received routing from=0xf267a2b8, id=0x6670d9a4, portnum=3, payloadlen=2
> [15:41:42]??:??:?? 60 [PositionPlugin] Routing sniffing (id=0x6670d9a4 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=3 WANTRESP priority=10)
> [15:41:42]??:??:?? 60 [PositionPlugin] FIXME-update-db Sniffing packet
> [15:41:42]??:??:?? 60 [PositionPlugin] Delivering rx packet (id=0x6670d9a4 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=3 WANTRESP priority=10)
> [15:41:42]??:??:?? 60 [PositionPlugin] Forwarding to phone (id=0x6670d9a4 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=3 WANTRESP priority=10)
> [15:41:42]??:??:?? 60 [PositionPlugin] Update DB node 0xf267a2b8, rx_time=0
> [15:41:42]??:??:?? 60 [PositionPlugin] Plugin routing considered
> [15:41:42]??:??:?? 60 [PositionPlugin] Add packet record (id=0x6670d9a4 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0x0 Portnum=3 WANTRESP priority=10)
> [15:41:42]??:??:?? 60 [PositionPlugin] Expanding short PSK #1
> [15:41:42]??:??:?? 60 [PositionPlugin] Installing AES128 key!
> [15:41:42]??:??:?? 60 [PositionPlugin] enqueuing for send (id=0x6670d9a4 Fr0xb8 To0xff, WantAck0, HopLim1 Ch0xb1 encrypted priority=10)
> [15:41:42]??:??:?? 60 [PositionPlugin] (bw=31, sf=9, cr=4/8) packet symLen=16 ms, payloadSize=24, time 1675 ms
> [15:41:42]??:??:?? 60 [PositionPlugin] txGood=0,rxGood=0,rxBad=0
> [15:41:42]??:??:?? 60 [PositionPlugin] AirTime - Packet transmitted : 1675ms
> [15:41:42]??:??:?? 60 [PositionPlugin] xmit timer 1727
> [15:41:42]??:??:?? 61 [Power] Battery: usbPower=1, isCharging=1, batMv=4187, batPct=100
> [15:41:44]??:??:?? 62 [RadioIf] delay done
> [15:41:44]??:??:?? 62 [RadioIf] Can not send yet, busyTx
> [15:41:44]??:??:?? 62 [RadioIf] xmit timer 3414
> [15:41:47]??:??:?? 65 [RadioIf] delay done
> [15:41:47]??:??:?? 65 [RadioIf] Can not send yet, busyTx
> [15:41:47]??:??:?? 65 [RadioIf] xmit timer 1703
> [15:41:49]??:??:?? 67 [RadioIf] delay done
> [15:41:49]??:??:?? 67 [RadioIf] Can not send yet, busyTx
> [15:41:49]??:??:?? 67 [RadioIf] xmit timer 1997
> [15:41:51]??:??:?? 69 [RadioIf] delay done
> [15:41:51]??:??:?? 69 [RadioIf] Can not send yet, busyTx
> [15:41:51]??:??:?? 69 [RadioIf] xmit timer 4853
> [15:41:56]??:??:?? 74 [RadioIf] delay done
> [15:41:56]??:??:?? 74 [RadioIf] Can not send yet, busyTx
> [15:41:56]??:??:?? 74 [RadioIf] xmit timer 3226
> [15:41:59]??:??:?? 77 [RadioIf] delay done
> [15:41:59]??:??:?? 77 [RadioIf] Can not send yet, busyTx
> [15:41:59]??:??:?? 77 [RadioIf] xmit timer 862
> [15:42:00]??:??:?? 78 [RadioIf] delay done
> [15:42:00]??:??:?? 78 [RadioIf] Can not send yet, busyTx
> [15:42:00]??:??:?? 78 [RadioIf] xmit timer 1176
> [15:42:01]??:??:?? 79 [RadioIf] delay done
> [15:42:01]??:??:?? 79 [RadioIf] Can not send yet, busyTx
> [15:42:01]??:??:?? 79 [RadioIf] xmit timer 352
> [15:42:01]??:??:?? 80 [RadioIf] delay done
> [15:42:01]??:??:?? 80 [RadioIf] Can not send yet, busyTx
> [15:42:01]??:??:?? 80 [RadioIf] xmit timer 814
> [15:42:02]??:??:?? 80 [RadioIf] delay done
> [15:42:02]??:??:?? 80 [RadioIf] Can not send yet, busyTx
> [15:42:02]??:??:?? 80 [RadioIf] xmit timer 3620
> [15:42:02]??:??:?? 81 [Power] Battery: usbPower=1, isCharging=1, batMv=4187, batPct=100
> [15:42:06]??:??:?? 84 [RadioIf] delay done
> [15:42:06]??:??:?? 84 [RadioIf] Can not send yet, busyTx
> [15:42:06]??:??:?? 84 [RadioIf] xmit timer 2518
> [15:42:08]??:??:?? 87 [RadioIf] delay done
> [15:42:08]??:??:?? 87 [RadioIf] Can not send yet, busyTx
> [15:42:08]??:??:?? 87 [RadioIf] xmit timer 4415
> [15:42:13]??:??:?? 91 [RadioIf] delay done
> [15:42:13]??:??:?? 91 [RadioIf] Can not send yet, busyTx
> [15:42:13]??:??:?? 91 [RadioIf] xmit timer 2734
> [15:42:15]??:??:?? 94 [RadioIf] delay done
> [15:42:15]??:??:?? 94 [RadioIf] Can not send yet, busyTx
> [15:42:15]??:??:?? 94 [RadioIf] Hardware Failure! busyTx for more than 60s
> [15:42:15]??:??:?? 94 [RadioIf] NOTE! Recording critical error 8 at src/mesh/RadioLibInterface.cpp:50
> [15:42:15]??:??:?? 94 [RadioIf] xmit timer 77
> [15:42:15]??:??:?? 94 [Screen] Screen: Critical error 8!
> [15:42:15]??:??:?? 94 [RadioIf] delay done
> [15:42:15]??:??:?? 94 [RadioIf] Can not send yet, busyTx
> [15:42:15]??:??:?? 94 [RadioIf] Hardware Failure! busyTx for more than 60s
> [15:42:15]??:??:?? 94 [RadioIf] NOTE! Recording critical error 8 at src/mesh/RadioLibInterface.cpp:50
> [15:42:15]??:??:?? 94 [RadioIf] xmit timer 1605
> [15:42:15]??:??:?? 94 [Screen] Screen: Critical error 8!
> [15:42:17]??:??:?? 95 [RadioIf] delay done
> [15:42:17]??:??:?? 95 [RadioIf] Can not send yet, busyTx
> [15:42:17]??:??:?? 95 [RadioIf] Hardware Failure! busyTx for more than 60s
> [15:42:17]??:??:?? 95 [RadioIf] NOTE! Recording critical error 8 at src/mesh/RadioLibInterface.cpp:50
> [15:42:17]??:??:?? 95 [RadioIf] xmit timer 3125
> [15:42:17]??:??:?? 95 [Screen] Screen: Critical error 8!
> [15:42:20]??:??:?? 99 [RadioIf] delay done
> [15:42:20]??:??:?? 99 [RadioIf] Can not send yet, busyTx
> [15:42:20]??:??:?? 99 [RadioIf] Hardware Failure! busyTx for more than 60s
> [15:42:20]??:??:?? 99 [RadioIf] NOTE! Recording critical error 8 at src/mesh/RadioLibInterface.cpp:50
> [15:42:20]ets Jul 29 2019 12:21:46
> [15:42:20]
> 

BUSY pin on module is 0V. I tried watch scope and no difference between modules.
Yellow is clock, green is data from master, blue is BUSY.
![image](https://user-images.githubusercontent.com/16230374/132523119-4d980797-5329-4958-a07d-ceec07404224.png)

Any idea? In your private TODO.md (sorry!) I found "swbug! stuck busy tx occurred!" on eink. Can´t be same problem?

**Comment by markbirss** [comment]
@tomasbrincil  Hi, have you connected the busy pin also ? possibly nned same connection as Type 2 here - https://github.com/NanoVHF/Meshtastic-DIY/blob/main/Schematics/Mesh_NiceRF.pdf.

**Comment by tomasbrincil** [comment]
Hi, thank for your time. Yes busy pin is connected to original pin 32. I rewired 1:1 all pads to G-Nice RF module.

**Comment by markbirss** [comment]
Oh Ok, my RA-02 would not initialise correctly but i had wired to wrong GPIO on my breakout board
It works now 
Im using the Tlora32 v1 firmware but custom DIY board ESP32 and RA02

![diy](https://user-images.githubusercontent.com/22388007/134178112-1bc4952d-e72a-4191-8970-f95137787a13.png)

**Comment by tomasbrincil** [comment]
No change. I am trying differents GPIO pins and nothing helps. @geeksville can you hint me pls? Is it software thing?

**Comment by osmanovv** [comment]
There is no Tx pin issue, "busyTx" in this message means you are still sending a message or forget to handle it:

https://github.com/meshtastic/Meshtastic-device/blob/b182819aff7aece1eaae8efefca749c3384df2aa/src/mesh/RadioLibInterface.cpp#L65-L78

Use https://github.com/meshtastic/Meshtastic-device/blob/b182819aff7aece1eaae8efefca749c3384df2aa/src/mesh/RadioLibInterface.cpp#L211-L218

or https://github.com/meshtastic/Meshtastic-device/blob/b182819aff7aece1eaae8efefca749c3384df2aa/src/mesh/RadioLibInterface.cpp#L220-L225

to clear the message after sending it.
