### ISSUE TITLE
LoRa think's it is plugged in

### ISSUE THREAD

**Issue by KrazyKerbalnaut** [meshtastic/Meshtastic-device#888]
Hey, I'm having another issue where my radio thinks it's plugged in to USB and receiving power. I have my hardware connected to a LiPo cell via the jst. It was initially giving me a battery charge but I haven't been able to get it to come out of that recently. I'm not able to get them to sleep anymore either. Idk what is causing this.

Hardware: Heltech WiFi LoRa 32 (v2)
Firmware: Heltech v2.0 1.2.45

**Comment by garthvh** [comment]
Can we close this we have 4 or 5 of these with a lot more detail.
