### ISSUE TITLE
allow any channel to be tagged as admin

### ISSUE THREAD

**Issue by sachaw** [meshtastic/Meshtastic-device#895]
Instead of relying on a channel with the name of `admin` to allow administration from, instead have a new protobuf field, i.e. `admin: Boolean` so multiple channels can be administered, allowing for administration zones.

**Comment by a-f-G-U-C** [comment]
I like the idea, and I don't see any glaring security red flags.
It's not a quick job as the "bound channel" logic (which I think Admin currently relies on) would need to be redesigned, but still doable.

**Comment by rxt1077** [comment]
Do you mean like adding an option for a node to specify it's admin channel name and then have that node listen on that specific channel? You could put some nodes on "admin-1" others on "admin-2", etc. If so, that should just be a matter of adding an option, I think the boundChannel logic will work with it as is.

Am I misunderstanding your original Issue?

**Comment by andrekir** [comment]
an ADMIN enum role could be added to Channel proto: https://github.com/meshtastic/Meshtastic-protobufs/blob/master/channel.proto#L123

**Comment by sachaw** [comment]
I think a field isAdministerable may be simpler, basically enabling this seems any traffic received on that channel as authoritative and node will comply

**Comment by garthvh** [comment]
Would this mostly correct the magic string of admin issue or would we allow multiple Admin channels on one mesh?
