### ISSUE TITLE
Cannot set lat&lon via CLI

### ISSUE THREAD

**Issue by osmanovv** [meshtastic/Meshtastic-device#900]
With the latest changes in coordinates handling (probably #875 or later) there is no way to set fixed coordinates via CLI:
```
meshtastic --setlat 55.0000000 --setlon 37.0000000 --setalt 133
```
Could someone confirm it?

@syund, @a-f-G-U-C, please check it. With the previous firmware it works fine.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/device-firmware-1-2-47-alpha/4298/1

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/device-firmware-release-1-2-47-alpha/4299/1
