### ISSUE TITLE
https, the device received a request, and either fails the handshake or just hangs up, then seems to cause a WiFi disconnect

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#903]
Report from @sachaw 

sachaw — Yesterday at 6:49 PM
also @MC Hamster I'm getting issues over https, the device received a request, and either fails the handshake or just hangs up, then seems to cause a WiFi disconnect (may be unrelated)
[HTTPS:I] New connection. Socket FID=60
[HTTPS:I] Request: GET /api/v1/fromradio?all=false (FID=60)
[D][esp32-hal-cpu.c:189] setCpuFrequencyMhz(): PLL: 320 / 2 = 160 Mhz, APB: 80000000 Hz
[HTTPS:I] Request: GET /api/v1/fromradio?all=false (FID=60)
[HTTPS:I] Request: GET /api/v1/fromradio?all=false (FID=60)
[HTTPS:I] Request: GET /api/v1/fromradio?all=false (FID=60)
Expand
message.txt
8 KB
a mix of working (http) and non-working (https) requests
and ideas, and I can take a look
MC Hamster — Yesterday at 6:51 PM
re: oneof -- if that's the case, it's the same thing trickled down on the bluetooth api, http api and serial api. That's at a lower level and would need to loop in K 
re: https disconnect wifi -- My best guess is it's unrelated but I can't discount it all together.
Will need more information
MC Hamster — Today at 6:03 PM
Are you referring to the line for setCpuFrequency? That's intended behavior and calls to an internal espressif API.
sachaw — Today at 6:11 PM
no, just that whenever I make a request over tls, it hangs up and wifi gets reconnected, and is it's just over http, all is fine
MC Hamster — Today at 6:22 PM
hmm
Has this been happening since .... March this year? That's when the arduino-esp32 library was updated. 
sachaw — Today at 6:25 PM
not sure sorry, I don't use tls in dev due to it's lower throughput
MC Hamster — Today at 6:26 PM
soon i'll be off work for 6 weeks to recover from knee surgery, i'll be able to look then.
that's just two weeks away

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/protoman-example-using-http-api/4147/3

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/protoman-example-using-http-api/4147/5

**Comment by mc-hamster** [comment]
closing. can't reproduce.
