### ISSUE TITLE
just wondered

### ISSUE THREAD

**Issue by jamieduk** [meshtastic/Meshtastic-device#907]
I have https://www.aliexpress.com/item/4001181421596.html?spm=a2g0s.9042311.0.0.103e4c4dWhKHIV  LILYGO® TTGO T-Beam V1.1 ESP32 433/868/915/923Mhz WiFi Bluetooth Module ESP32 GPS NEO-6M SMA 18650 Battery Holder With OLED

what firmware is best for this ?

**Comment by sachaw** [comment]
Please bring questions like this to the discord server.
