### ISSUE TITLE
"Cache disabled but cache memory region accessed" during radio interrupt when writing SPIFFS

### ISSUE THREAD

**Issue by rxt1077** [meshtastic/Meshtastic-device#909]
_This is only an issue when performing SPIFFS functions on the ESP32 (such as is the case with the RangeTest plugin)._
Could be the cause of [issue #606](https://github.com/meshtastic/Meshtastic-device/issues/606#issuecomment-754429574) and [issue #700](https://github.com/meshtastic/Meshtastic-device/issues/700)

SPIFFS writes will temporarily turn off access to flash meaning that interrupt handlers need to be stored in IRAM, which they should be thanks to the use of the INTERRUPT_ATTR macro (which expands to IRAM_ATTR):

src/mesh/SX126xInterface.cpp
```
template<typename T>
void INTERRUPT_ATTR SX126xInterface<T>::disableInterrupt()
{
    lora.clearDio1Action();
}
```

Unfortunately [IRAM_ATTR isn't currently honored for templated functions](https://github.com/espressif/esp-idf/issues/4542). This means that occasionally (or often if you're doing a bunch of SPIFF stuff) you can get a "Cache disabled but cache memory region accessed" panic and a backtrace that looks like this:

```
PC: 0x400812f8 is in RadioLibInterface::isrLevel0Common(RadioLibInterface::PendingISR) (src/mesh/RadioLibInterface.cpp:37).
BT-0: 0x400812f8 is in RadioLibInterface::isrLevel0Common(RadioLibInterface::PendingISR) (src/mesh/RadioLibInterface.cpp:37).
BT-1: 0x40081321 is in RadioLibInterface::isrRxLevel0() (src/mesh/RadioLibInterface.cpp:50).
BT-2: 0x40081389 is in __onPinInterrupt (C:\Users\rxt1077\.platformio\packages\framework-arduinoespressif32\cores\esp32/esp32-hal-gpio.c:220).
BT-3: 0x40082401 is at /home/kevinh/development/meshtastic/esp32-arduino-lib-builder/esp-idf/components/freertos/xtensa_vectors.S:1154.
BT-5: 0x400967cd is in esp_rom_spiflash_read_status (/home/kevinh/development/meshtastic/esp32-arduino-lib-builder/esp-idf/components/spi_flash/spi_flash_rom_patch.c:261).
```

An objectdump of firmware.elf reveals that the SX126x version of `disableInterrupt` isn't in IRAM, but the  rf95 version is:

```
...
400812e0 g     F .iram0.text	0000000b _ZN13RF95Interface16disableInterruptEv
...
400e042c  w    F .flash.text	0000000d _ZN15SX126xInterfaceI6SX1262E16disableInterruptEv
....
```

The difference being that the rf95 function isn't templated.

src/mesh/RF95Interface.cpp:
```
void INTERRUPT_ATTR RF95Interface::disableInterrupt()
{
    lora->clearDio0Action();
}
```

If anyone has an idea of a workaround, I'm all ears!

**Comment by rxt1077** [comment]
So my first attempt was moving `disableInterrupt` out of `SX126xInterface` as a templated function and making non-templated functions in `SX1262Interface` and `SX1268Interface` that did the same thing (clearDio1Action). This was successful in getting the code into IRAM as evidenced via an objdump, but the panic still occurred.

I then followed [this advice](https://www.esp32.com/viewtopic.php?t=7684) and tried compiling arduino-esp32 with `SPI_MASTER_ISR_IN_IRAM` disabled, but the panic still occurred. At least I was able to [update the documentation for building arduino-esp32](https://github.com/meshtastic/Meshtastic/pull/77), so I got that going for me, which is nice.

**Comment by rxt1077** [comment]
I'm going to close this as I don't think it's something we can fix on our end. SPIFFS seem to have all sort of interrupt issues when used heavily. As far as I can tell, the meshtastic-device code seems to be setting everything correctly for its interrupt handlers.

**Comment by sachaw** [comment]
Hopefully we can put all related issues behind us with the a move to littlefs
