### ISSUE TITLE
T-Echo capacitive touch sensor

### ISSUE THREAD

**Issue by ajorg** [meshtastic/Meshtastic-device#910]
Please - if you just have a question (i.e. not a bug report or a feature proposal), post in our [forum](https://meshtastic.discourse.group/) instead.

**Describe the bug**
The T-Echo has a capacitive "touch" sensor on the top, but it's not used to anything in Meshtastic. It seems to me it would be better to have this sensor used as the Program Button, and the current program button could serve as the Power Button.

**To Reproduce**
1. Sensor is labeled "Touch" "P0.11" on [the diagram](https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo#pinout-)
2. Example [code is available](https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo/blob/main/lib/AceButton/examples/CapacitiveButton/CapacitiveButton.ino)

**Expected behavior**
Tapping, double-tapping, etc., on this sensor could behave as the Program Button.
The lower Button2 P1.10 could serve as the Power Button.

**Screenshots**
![](https://raw.githubusercontent.com/Xinyuan-LilyGO/LilyGO-T-Echo/main/image/T-ECHO.jpg)

**Device info:**
 - Device model: T-Echo
 - Software Version 1.2.46

**Additional context**
Just a suggestion. I won't be the least annoyed if it isn't a good one.

**Comment by mc-hamster** [comment]
Closed

this is done.
