### ISSUE TITLE
Fonts use up a lot of storage on device. This needs to be cleaned up.

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#920]
Flash Memory analysis shows that fonts use a disproportionally large amount of memory due to duplication.

This needs to be cleaned up to reduce the foot print. Code now takes up 92% of total available space.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/12804989/142512058-64fd43b0-861d-474a-9566-d466d5b141c7.png">

**Comment by runestone74** [comment]
What kind of cleaning is needed? High level or low level?

**Comment by mc-hamster** [comment]
@runestone74 The font "ArialMT_Plain_10" is being stored 5 times and "ArialMT_Plain_16" is being stored twice. They should be stored once and then reused.

See screenshots from the analysis (I should have also included these earlier, thanks for asking!)

<img width="819" alt="image" src="https://user-images.githubusercontent.com/12804989/143668829-3068c8f9-5865-4e91-ba62-cb21782792e3.png">

<img width="811" alt="image" src="https://user-images.githubusercontent.com/12804989/143668801-1fd3dfd6-5a09-4486-9442-072ab2f6a4fb.png">

<img width="824" alt="image" src="https://user-images.githubusercontent.com/12804989/143668794-6b833541-41a0-40e7-87fb-cec36716d23a.png">

**Comment by caveman99** [comment]
this can also be seen from the output.map generated during buildtime. Actually 2 more embeds of 10 and 16 size popped up with the CannedReply Plugin. 

```
output.map: .rodata._ZL16ArialMT_Plain_24
output.map-                0x3f401e88     0x25ab .pio/build/heltec-v1/src/graphics/Screen.cpp.o
output.map: .rodata._ZL16ArialMT_Plain_16
output.map-                0x3f404433     0x13b9 .pio/build/heltec-v1/src/graphics/Screen.cpp.o
output.map: .rodata._ZL16ArialMT_Plain_10
output.map-                0x3f4057ec      0xaab .pio/build/heltec-v1/src/graphics/Screen.cpp.o
output.map: .rodata._ZL16ArialMT_Plain_16
output.map-                0x3f40c3c4     0x13b9 .pio/build/heltec-v1/src/plugins/CannedMessagePlugin.cpp.o
output.map: .rodata._ZL16ArialMT_Plain_10
output.map-                0x3f40d77d      0xaab .pio/build/heltec-v1/src/plugins/CannedMessagePlugin.cpp.o
output.map: .rodata._ZL16ArialMT_Plain_16
output.map-                0x3f40eef8     0x13b9 .pio/build/heltec-v1/src/plugins/esp32/EnvironmentalMeasurementPlugin.cpp.o
output.map: .rodata._ZL16ArialMT_Plain_10
output.map-                0x3f4102b1      0xaab .pio/build/heltec-v1/src/plugins/esp32/EnvironmentalMeasurementPlugin.cpp.o
output.map: .rodata._ZL16ArialMT_Plain_10
output.map-                0x3f411d8c      0xaab .pio/build/heltec-v1/lib0c6/libESP8266_SSD1306.a(OLEDDisplay.cpp.o)
output.map: .rodata._ZL16ArialMT_Plain_10
output.map-                0x3f412847      0xaab .pio/build/heltec-v1/lib0c6/libESP8266_SSD1306.a(OLEDDisplayUi.cpp.o)

```

**Comment by caveman99** [comment]
There's something fundamentally wrong here. Even including the SSD1306 lib has the Plain_10 font packed twice. I see we include our own version of that lib, maybe something got broken during customization?

**Comment by caveman99** [comment]
I think i have solved this ... T-Beam flash sizes before/after:

Flash: [========= ]  94.2% (used 1729091 bytes from 1835008 bytes)
Flash: [========= ]  93.1% (used 1708595 bytes from 1835008 bytes)

Problem is, to solve this the Screen lib needs to be modified. There's a flaw in the font definition logic. I'll send in a PR there.

**Comment by mc-hamster** [comment]
Thanks @caveman99 !!!!
