### ISSUE TITLE
Remove non-existing nodes

### ISSUE THREAD

**Issue by Beiri22** [meshtastic/Meshtastic-device#922]
The device shows nodes that it has seen previously. But after seing some nodes they seem to stick in the list.
My T-Echo "knows" 3 devices (maybe from manufacturers testing), that are now present here. I'd like to remove
these devices from the "known list". Is there any way to do that? (See https://github.com/meshtastic/Meshtastic-Android/issues/310)

**Comment by garthvh** [comment]
If you do a meshtastic --set factory_reset 1 from the python CLI it will clear out the node list.

**Comment by Beiri22** [comment]
Thanks for that advice. But at a long run, maybe a kind of selective reset would be nice :-)
