### ISSUE TITLE
[Question] Is firmware supported for ESP32-C3

### ISSUE THREAD

**Issue by cuongpham2110** [meshtastic/Meshtastic-device#925]
Hi all, 
I intend to use meshtastic-device firmware in **ESP32-C3** module. Is latest firmware supported for **ESP32-C3** modules in the market
Thank you

**Comment by sachaw** [comment]
The key feature of this project utilizes a LORA radio, if there are any specific LORA&ESP32-C3 boards that you want us to support, feel free to open a new issue with the details.
