### ISSUE TITLE
LLCC68 LoRa module processing without SF12 support

### ISSUE THREAD

**Issue by osmanovv** [meshtastic/Meshtastic-device#926]
Recently I have added support for the LLCC68 module in DIY devices (#918).

This module can work with the current firmware to a limited extent since it does not support Spreading Factor 12 (13.4.5.2 LoRa® Modulation Parameters, [LLCC68 Data Sheet](https://www.semtech.com/products/wireless-rf/lora-core/llcc68)), therefore will not work on the default "Long Slow" channel. The firmware throws `Critical Error #3` and would be nice to see a hint about channel switching or the limitations of this module.

It should be remembered that this [LLCC68 module is implemented over SX1262](https://jgromes.github.io/RadioLib/class_l_l_c_c68.html) and could be functioning on firmware for SX1262/SX1268 modules.

Discussion link: https://meshtastic.discourse.group/t/meshtastic-diy-project/3831/20

**Comment by sachaw** [comment]
As hints are something that are implemented in clients this is out-of-scope for the firmware, however there is an approaches that would prevent the error:
Perform a check when the sf is set to 12 and for the presence of a LLCC68 if so, don't do anything, then clients could set any value they want and the troublesome one just gets ignored.
