### ISSUE TITLE
When generating SSL certs, display "Please wait..." on the screen.

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#927]
When generating SSL certs, display "Please wait..." on the screen or some other message/animation to indicate that the device is busy.

This happens the first reboot after wifi settings are applied on the device.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-48-alpha/4359/1
