### ISSUE TITLE
T-Echo does not show sent messages on screen, only received messages (1.2.46.dce2fe4 alpha)

### ISSUE THREAD

**Issue by Kollensperger** [meshtastic/Meshtastic-device#928]
**Describe the bug**
T-Echo displays received messages on e-paper screen, but not sent/outgoing messages. This is different to e.g. T-beams, where also messages sent from the device are displayed on the radios screen. In the app, all shows as expected

**To Reproduce**
1. Send a message from app (confirmed with iOS and Android) via connected T-Echo to another radio
2. Message shows up on the remote radio, but not on T-Echo Epaper screen
3. Sending message from e.g. a t-beam to T-Echo, the message will show up correctly on the T-Echos e-paper screen

**Expected behavior**
T-Echo should show outgoing messages on e-paper screen

**Device info:**
 - Device model: T-Echo v1
 - Software Version 1.2.46.dce2fe4 alpha

**Smartphone information (if relevant):**
 - tested both with Android (1.2.50) and iOS apps

**Comment by mc-hamster** [comment]
@Kollensperger FYI - A change was just merged into for the esp32 firmware to make the tbeams behave like the devices with e-paper screen -- Device won't display sent messages.

Thanks for the report. Will close it once the new esp32 firmware gets released.
