### ISSUE TITLE
Smart Location Beaconing feature

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#934]
Create a Smart Location Beacon feature where if the device has been moved by 100m since the location transmission, retransmit the device's GPS location.

This would be a good work to keep radio airtime use down for the location service and only transmit when device is in motion

**Comment by mc-hamster** [comment]
Changes would be in PositionPlugin and radioconfig.proto

**Comment by mc-hamster** [comment]
This is merged into upstream.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-48-alpha/4359/1
