### ISSUE TITLE
Wifi admin mode no longer works

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#939]
Reported by Lance on Discord.

Wifi admin mode no longer works.

Reproduction on tbeam:

- Hold down the middle button, press reset, wait to seconds, release middle button.

Device should now be in wifi admin, it does not.

**Comment by mc-hamster** [comment]
Done

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-48-alpha/4359/1
