### ISSUE TITLE
Upgrade to OneButton 2.0.3

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#941]
Upgrade to OneButton 2.0.3. Our version is about a year and a half old.

**Comment by mc-hamster** [comment]
Merged to upstream.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-device-1-2-48-alpha/4359/1
