### ISSUE TITLE
promote-release.sh breaks with 'git push root'

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#947]
promote-release.sh breaks with 'git push root'.

reported by @andrekir

**Comment by mc-hamster** [comment]
Switched to "git push origin"

**Comment by sachaw** [comment]
yeah, origin/upstream commands are the way to go:
`git push origin master`,
`git push upstream master` (forks)

**Comment by mc-hamster** [comment]
@sachaw you're watching me :)

**Comment by sachaw** [comment]
GitHub mobile notifications keep me in the loop
