### ISSUE TITLE
Feature request: add the hop limit info to range test plugin

### ISSUE THREAD

**Issue by ANS-spb** [meshtastic/Meshtastic-device#967]
Please add hop limit information to range test csv output
Maybe it should look something like this:
`time,from,sender name,sender lat,sender long,rx lat,rx long,rx elevation,rx snr,distance,hoplimit,payload
19:57:29,-1468062744,username,59.855139,30.392396,59.961005,30.485132,80,-19.000000,11972.889648,2,"Test message"`

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/new-meshtastic-python-v1-2-44/4356/4

**Comment by mc-hamster** [comment]
This is done.
