### ISSUE TITLE
Feature request: add airtime to NodeInfo

### ISSUE THREAD

**Issue by PlumRugOfDoom** [meshtastic/Meshtastic-device#970]
Add airtime to NodeInfo, useful for additional features like packet rate limit / duty cycle limit to stay within region specific regulations

**Comment by mc-hamster** [comment]
What will go into nodeInfo will be three arrays

- periodTX - 48 time windows of 1hr each with the airtime transmitted out of the device per hour.

- periodRX - 48 time windows of 1hr each with the airtime of valid packets for your mesh.

- periodRX_ALL - 48 time windows of 1hr each with the airtime of valid lora packets. If you subtract periodRX from periodRX_ALL, you'll get something that looks like the measure of noise on the selected frequency.

**Comment by mc-hamster** [comment]
this is done
