### ISSUE TITLE
Utilize FSCommon files

### ISSUE THREAD

**Issue by rxt1077** [meshtastic/Meshtastic-device#977]
Use src/FSCommon.cpp and src/FSCommon.h. There are still some places that use the SPIFFS explicitly and this will make it easier to transition to LittleFS.

**Comment by caveman99** [comment]
This is part of https://github.com/meshtastic/Meshtastic-device/pull/1150 but will go into 1.3 only

**Comment by caveman99** [comment]
this is done for 1.3, no backport
