### ISSUE TITLE
GPS format Issue when using DD MM SS.SSSS

### ISSUE THREAD

**Issue by snake0073** [meshtastic/Meshtastic-device#982]
When setting the gps_format to option 1 (DD MM SS.SSSS), the on-device screen's GPS page does not properly update and will show all 0's for the position.  The location is properly reported to the app and other radios on the mesh. 

Hardware: T-beam Lora32
Firmware: 1.2.48

**Comment by sachaw** [comment]
Hi, can you please provide the firmware version you are running, thanks.

**Comment by snake0073** [comment]
1.2.48

**Comment by garthvh** [comment]
Verified as an issue with fixed_position as well

**Comment by garthvh** [comment]
Are any of these actually working? Should we just delete them all?

**Comment by garthvh** [comment]
I tested all of these and they are all working as expected with 1.2.65
