### ISSUE TITLE
T-echo node ID mismatch

### ISSUE THREAD

**Issue by jazap** [meshtastic/Meshtastic-device#997]
**Describe the bug**
The node ID on the unit's display does not match the node ID it reports to the Meshtastic App

**To Reproduce**
1. Press the unit's page flip button until you get tot he display showing the unit node ID on the upper right side of the display.
2. Open Meshtastic 1.2.45 and go to the node connection page.
3. Choose the node that shows available and connect.
4. Note the node ID you chose does not match the node ID on the unit, but you are connected to the unit.

**Comment by mc-hamster** [comment]
@jazap Do you have screen shots or pictures of the problem? I'm trying to track this down.

**Comment by mc-hamster** [comment]
Bug is likely in:

main-nrf52.cpp
   void getMacAddr(uint8_t *dmac)

**Comment by jazap** [comment]
Jason Piazza
*operor vos ingredior ingredior?*

**Comment by garthvh** [comment]
Can you check if this pull fixed your issue https://github.com/meshtastic/Meshtastic-device/pull/1017

**Comment by andrekir** [comment]
installed latest firmware from artifact: https://github.com/meshtastic/Meshtastic-device/actions/runs/1631731764


no change. user id: **!495a8cdd**

<img width="512" alt="Captura de Tela 2021-12-28 às 21 17 40" src="https://user-images.githubusercontent.com/48680741/147616739-4ae7f503-61d3-4222-967f-72f26c4dedf0.png">

**Comment by andrekir** [comment]
correction, looks like the bug is fixed

didn't notice any changes immediately after factory_reset, but after a while owner/longname, user ID and Bluetooth ID (Meshtastic_89b0) all changed to reflect the same 4 letter ID (89b0) on the screen


![Screenshot_20211228-220040](https://user-images.githubusercontent.com/48680741/147618739-0cc69056-2b29-452b-9a4f-79c65747163f.jpg) ![Screenshot_20211228-220217](https://user-images.githubusercontent.com/48680741/147618749-55bb7b03-f68b-4f1c-9420-5fc78a2a2ee1.jpg)

**Comment by thebentern** [comment]
Woohoo! I was worried this one would be more insidious, but I like the fixes where I can just eliminate code

**Comment by runestone74** [comment]
Is this related? The latest FW firmware-t-echo-1.2.50.41dcfdd.uf2 changed my device name from Meshtastic_1cf2 to Meshtastic_c773

**Comment by garthvh** [comment]
Probably, check if that value properly matches the last four of your Mac and user.id now.  Sometimes takes a factory_reset to get synced back up.

**Comment by runestone74** [comment]
meshtastic --set factory_reset 1 did not work. MAC: 73:c7:bf:9b:1c:f2 and still Meshtastic_c773 as the name, which seems derived from 73:c7 in the beginning of the MAC address

**Comment by jazap** [comment]
That fixed it.
The node ID now matches the display in the Meshtastic app.

Jason Piazza
*operor vos ingredior ingredior?*
